var searchData=
[
  ['calculate_5findex',['calculate_index',['../class_gadgetron_1_1ho_n_d_image.html#aad32931f04071ad2a30ed214db38d7a5',1,'Gadgetron::hoNDImage']]],
  ['calculate_5foffset',['calculate_offset',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html#a953fb165121730ad8dad063b27b087ad',1,'Gadgetron::gtPlus::gtplusBSplineFFD::calculate_offset()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#a86b15c41138f25c3b5cfa25d96c0b004',1,'Gadgetron::gtPlus::gtplusFFDBase::calculate_offset()']]],
  ['calibrationbuffercounter',['CalibrationBufferCounter',['../class_gadgetron_1_1_calibration_buffer_counter.html',1,'Gadgetron']]],
  ['call',['call',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1call.html',1,'crow::detail::routing_handler_call_helper']]],
  ['call_3c_20f_2c_20nint_2c_20nuint_2c_20ndouble_2c_20nstring_2c_20black_5fmagic_3a_3as_3c_20double_2c_20args1_2e_2e_2e_3e_2c_20black_5fmagic_3a_3as_3c_20args2_2e_2e_2e_3e_20_3e',['call&lt; F, NInt, NUint, NDouble, NString, black_magic::S&lt; double, Args1...&gt;, black_magic::S&lt; Args2...&gt; &gt;',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1call_3_01_f_00_01_n_int_00_01_n_uint_0b30fc35e23f441513a63571edf36fc02.html',1,'crow::detail::routing_handler_call_helper']]],
  ['call_3c_20f_2c_20nint_2c_20nuint_2c_20ndouble_2c_20nstring_2c_20black_5fmagic_3a_3as_3c_20int64_5ft_2c_20args1_2e_2e_2e_3e_2c_20black_5fmagic_3a_3as_3c_20args2_2e_2e_2e_3e_20_3e',['call&lt; F, NInt, NUint, NDouble, NString, black_magic::S&lt; int64_t, Args1...&gt;, black_magic::S&lt; Args2...&gt; &gt;',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1call_3_01_f_00_01_n_int_00_01_n_uint_0b6a35a476dfcab9d942547331be456a9.html',1,'crow::detail::routing_handler_call_helper']]],
  ['call_3c_20f_2c_20nint_2c_20nuint_2c_20ndouble_2c_20nstring_2c_20black_5fmagic_3a_3as_3c_20std_3a_3astring_2c_20args1_2e_2e_2e_3e_2c_20black_5fmagic_3a_3as_3c_20args2_2e_2e_2e_3e_20_3e',['call&lt; F, NInt, NUint, NDouble, NString, black_magic::S&lt; std::string, Args1...&gt;, black_magic::S&lt; Args2...&gt; &gt;',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1call_3_01_f_00_01_n_int_00_01_n_uint_0d6c3c1bf426d7dfb9e3165c9ff3fd2f3.html',1,'crow::detail::routing_handler_call_helper']]],
  ['call_3c_20f_2c_20nint_2c_20nuint_2c_20ndouble_2c_20nstring_2c_20black_5fmagic_3a_3as_3c_20uint64_5ft_2c_20args1_2e_2e_2e_3e_2c_20black_5fmagic_3a_3as_3c_20args2_2e_2e_2e_3e_20_3e',['call&lt; F, NInt, NUint, NDouble, NString, black_magic::S&lt; uint64_t, Args1...&gt;, black_magic::S&lt; Args2...&gt; &gt;',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1call_3_01_f_00_01_n_int_00_01_n_uint_00ad4e6269b7fa1968d50bbffd43a8f02.html',1,'crow::detail::routing_handler_call_helper']]],
  ['call_3c_20f_2c_20nint_2c_20nuint_2c_20ndouble_2c_20nstring_2c_20black_5fmagic_3a_3as_3c_3e_2c_20black_5fmagic_3a_3as_3c_20args1_2e_2e_2e_3e_20_3e',['call&lt; F, NInt, NUint, NDouble, NString, black_magic::S&lt;&gt;, black_magic::S&lt; Args1...&gt; &gt;',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1call_3_01_f_00_01_n_int_00_01_n_uint_0d7ef20f9a959e64c78052cf52ae9f097.html',1,'crow::detail::routing_handler_call_helper']]],
  ['call_5fpair',['call_pair',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1call__pair.html',1,'crow::detail::routing_handler_call_helper']]],
  ['call_5fparams',['call_params',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1call__params.html',1,'crow::detail::routing_handler_call_helper']]],
  ['callhelper',['CallHelper',['../structcrow_1_1black__magic_1_1_call_helper.html',1,'crow::black_magic']]],
  ['callhelper_3c_20f_2c_20s_3c_20args_2e_2e_2e_3e_20_3e',['CallHelper&lt; F, S&lt; Args...&gt; &gt;',['../structcrow_1_1black__magic_1_1_call_helper_3_01_f_00_01_s_3_01_args_8_8_8_4_01_4.html',1,'crow::black_magic']]],
  ['cartesiantogenericgadget',['CartesianToGenericGadget',['../class_gadgetron_1_1_cartesian_to_generic_gadget.html',1,'Gadgetron']]],
  ['cbct_5facquisition',['CBCT_acquisition',['../class_gadgetron_1_1_c_b_c_t__acquisition.html',1,'Gadgetron']]],
  ['cbct_5fbinning',['CBCT_binning',['../class_gadgetron_1_1_c_b_c_t__binning.html',1,'Gadgetron']]],
  ['cbct_5fgeometry',['CBCT_geometry',['../class_gadgetron_1_1_c_b_c_t__geometry.html',1,'Gadgetron']]],
  ['cc',['cc',['../class_gadgetron_1_1ho_image_reg_dissimilarity_local_c_c_r.html#a878b62b5aa4bc08d094c7101bbf0b00d',1,'Gadgetron::hoImageRegDissimilarityLocalCCR']]],
  ['cerrloghandler',['CerrLogHandler',['../classcrow_1_1_cerr_log_handler.html',1,'crow']]],
  ['cgcallback_2eh',['cgCallback.h',['../cg_callback_8h.html',1,'']]],
  ['cgpreconditioner',['cgPreconditioner',['../class_gadgetron_1_1cg_preconditioner.html',1,'Gadgetron']]],
  ['cgpreconditioner_2eh',['cgPreconditioner.h',['../cg_preconditioner_8h.html',1,'']]],
  ['cgpreconditioner_3c_20cundarray_3c_20t_20_3e_20_3e',['cgPreconditioner&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1cg_preconditioner.html',1,'Gadgetron']]],
  ['cgpreconditioner_3c_20hondarray_3c_20t_20_3e_20_3e',['cgPreconditioner&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1cg_preconditioner.html',1,'Gadgetron']]],
  ['cgsolver',['cgSolver',['../class_gadgetron_1_1cg_solver.html',1,'Gadgetron']]],
  ['cgsolver_2eh',['cgSolver.h',['../cg_solver_8h.html',1,'']]],
  ['cgsolver_3c_20cundarray_3c_20float_5fcomplext_20_3e_20_3e',['cgSolver&lt; cuNDArray&lt; float_complext &gt; &gt;',['../class_gadgetron_1_1cg_solver.html',1,'Gadgetron']]],
  ['cgsolver_3c_20cundarray_3c_20gadgetron_3a_3acomplext_20_3e_20_3e',['cgSolver&lt; cuNDArray&lt; Gadgetron::complext &gt; &gt;',['../class_gadgetron_1_1cg_solver.html',1,'Gadgetron']]],
  ['cgsolver_3c_20cundarray_3c_20t_20_3e_20_3e',['cgSolver&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1cg_solver.html',1,'Gadgetron']]],
  ['cgsolver_3c_20hocundarray_3c_20t_20_3e_20_3e',['cgSolver&lt; hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1cg_solver.html',1,'Gadgetron']]],
  ['cgsolver_3c_20hondarray_3c_20t_20_3e_20_3e',['cgSolver&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1cg_solver.html',1,'Gadgetron']]],
  ['cgterminationcallback',['cgTerminationCallback',['../class_gadgetron_1_1cg_termination_callback.html',1,'Gadgetron']]],
  ['check_5fafter_5fhandle_5farity_5f3',['check_after_handle_arity_3',['../structcrow_1_1detail_1_1check__after__handle__arity__3.html',1,'crow::detail']]],
  ['check_5fafter_5fhandle_5farity_5f3_5fconst',['check_after_handle_arity_3_const',['../structcrow_1_1detail_1_1check__after__handle__arity__3__const.html',1,'crow::detail']]],
  ['check_5fbefore_5fhandle_5farity_5f3',['check_before_handle_arity_3',['../structcrow_1_1detail_1_1check__before__handle__arity__3.html',1,'crow::detail']]],
  ['check_5fbefore_5fhandle_5farity_5f3_5fconst',['check_before_handle_arity_3_const',['../structcrow_1_1detail_1_1check__before__handle__arity__3__const.html',1,'crow::detail']]],
  ['check_5fcuda_2eh',['check_CUDA.h',['../check___c_u_d_a_8h.html',1,'']]],
  ['check_5ffor_5fcuda_5ferror',['CHECK_FOR_CUDA_ERROR',['../check___c_u_d_a_8h.html#ab600ea9f092550a3df26f2eaa2c8451f',1,'CHECK_FOR_CUDA_ERROR():&#160;check_CUDA.h'],['../namespace_gadgetron.html#a810de248e14fe335e04d92105a68ca10',1,'Gadgetron::CHECK_FOR_CUDA_ERROR()']]],
  ['ci_5fhash',['ci_hash',['../structcrow_1_1ci__hash.html',1,'crow']]],
  ['ci_5fkey_5feq',['ci_key_eq',['../structcrow_1_1ci__key__eq.html',1,'crow']]],
  ['clamp',['clamp',['../namespace_gadgetron.html#a5fdb706a013a10bf8653a4047c413c2e',1,'Gadgetron::clamp(hoNDArray&lt; T &gt; *x, typename realType&lt; T &gt;::Type min, typename realType&lt; T &gt;::Type max, T min_val, T max_val)'],['../namespace_gadgetron.html#acf6b1ce350936f1e39832d5ff053468a',1,'Gadgetron::clamp(hoNDArray&lt; T &gt; *x, typename realType&lt; T &gt;::Type min, typename realType&lt; T &gt;::Type max)'],['../namespace_gadgetron.html#a6ea45a90e05466cdd9313165ca32fd2e',1,'Gadgetron::clamp(cuNDArray&lt; T &gt; *x, typename realType&lt; T &gt;::Type min, typename realType&lt; T &gt;::Type max, T min_val, T max_val)'],['../namespace_gadgetron.html#a6d77c6aae34312af5c7e1d36f44f441e',1,'Gadgetron::clamp(cuNDArray&lt; T &gt; *x, typename realType&lt; T &gt;::Type min, typename realType&lt; T &gt;::Type max)']]],
  ['clamp_5fmax',['clamp_max',['../namespace_gadgetron.html#a66385e6403e0bffcfad5d37b0cd8944e',1,'Gadgetron::clamp_max(hoNDArray&lt; T &gt; *x, typename realType&lt; T &gt;::Type max)'],['../namespace_gadgetron.html#a6ba4d6e4d809455a262da24be7b78ee7',1,'Gadgetron::clamp_max(cuNDArray&lt; T &gt; *x, typename realType&lt; T &gt;::Type max)']]],
  ['clamp_5fmin',['clamp_min',['../namespace_gadgetron.html#a938a115bd7829fccb5c6ea01d6a42eb3',1,'Gadgetron::clamp_min(hoNDArray&lt; T &gt; *x, typename realType&lt; T &gt;::Type min)'],['../namespace_gadgetron.html#a956648915c8793fed4ac915ac7a3626e',1,'Gadgetron::clamp_min(cuNDArray&lt; T &gt; *x, typename realType&lt; T &gt;::Type min)']]],
  ['clear',['clear',['../class_gadgetron_1_1ho_n_d_image.html#a523a5db8f49915f875a058cba9882dc0',1,'Gadgetron::hoNDImage::clear()'],['../class_gadgetron_1_1ho_n_d_image_container2_d.html#aa8d02abb939de552cf5c6b708b24d3b6',1,'Gadgetron::hoNDImageContainer2D::clear()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#a89c88053ed82b9ead61cb320a523d980',1,'Gadgetron::gtPlus::gtplusFFDBase::clear()'],['../namespace_gadgetron.html#aaa657ae09c5ee05e5a5ba71c57fb0243',1,'Gadgetron::clear(hoNDArray&lt; T &gt; *x)'],['../namespace_gadgetron.html#a2860e78d36c2b382908a5a8a3356f90a',1,'Gadgetron::clear(cuNDArray&lt; T &gt; *x)']]],
  ['close',['close',['../class_gadgetron_1_1_physio_interpolation_gadget.html#a1faea96310b70c1dd8ff394c5d07818b',1,'Gadgetron::PhysioInterpolationGadget']]],
  ['cloudbus',['CloudBus',['../class_gadgetron_1_1_cloud_bus.html',1,'Gadgetron']]],
  ['cloudbus',['CloudBus',['../struct_gadgetron_x_m_l_1_1_cloud_bus.html',1,'GadgetronXML']]],
  ['cloudbus',['CloudBus',['../class_gadgetron_1_1_cloud_bus.html#a64c3885fe700e7b8011e6645f72e14fe',1,'Gadgetron::CloudBus']]],
  ['cloudbusnodecontroller',['CloudBusNodeController',['../class_gadgetron_1_1_cloud_bus_node_controller.html',1,'Gadgetron']]],
  ['cloudbusreadertask',['CloudBusReaderTask',['../class_gadgetron_1_1_cloud_bus_reader_task.html',1,'Gadgetron']]],
  ['cloudbusrelayacceptor',['CloudBusRelayAcceptor',['../class_gadgetron_1_1_cloud_bus_relay_acceptor.html',1,'Gadgetron']]],
  ['cloudcomputing_5f',['CloudComputing_',['../class_gadgetron_1_1_gt_plus_recon_gadget.html#ace05e4ea8b3809375102659d6f7cde1c',1,'Gadgetron::GtPlusReconGadget::CloudComputing_()'],['../class_gadgetron_1_1_gt_plus_recon_job2_d_t_gadget_cloud.html#a323438713bd3d4af63c3a78e3f2bfb1a',1,'Gadgetron::GtPlusReconJob2DTGadgetCloud::CloudComputing_()']]],
  ['cloudreadertask',['CloudReaderTask',['../class_gadgetron_1_1_cloud_reader_task.html',1,'Gadgetron']]],
  ['cloudwritertask',['CloudWriterTask',['../class_gadgetron_1_1_cloud_writer_task.html',1,'Gadgetron']]],
  ['cmrt3dgadget',['CMRT3DGadget',['../class_gadgetron_1_1_c_m_r_t3_d_gadget.html',1,'Gadgetron']]],
  ['cmrtgadget',['CMRTGadget',['../class_gadgetron_1_1_c_m_r_t_gadget.html',1,'Gadgetron']]],
  ['cmrtoperator',['CMRTOperator',['../class_gadgetron_1_1_c_m_r_t_operator.html',1,'Gadgetron']]],
  ['coil_5fcombine',['coil_combine',['../namespace_gadgetron.html#a1a5adc42a48854bf080a036d4aa9e752',1,'Gadgetron']]],
  ['coil_5fmap_5f',['coil_map_',['../class_gadgetron_1_1ho_wavelet_operator.html#ab922e776a23bc3a0ee28241028714d73',1,'Gadgetron::hoWaveletOperator::coil_map_()'],['../class_gadgetron_1_1_generic_recon_cartesian_grappa_obj.html#aa9b1f88a2be87c47fb88200a328d6dac',1,'Gadgetron::GenericReconCartesianGrappaObj::coil_map_()']]],
  ['coilreduce',['CoilReduce',['../classtpat__snr__scale_1_1_coil_reduce.html',1,'tpat_snr_scale']]],
  ['coilreductiongadget',['CoilReductionGadget',['../class_gadgetron_1_1_coil_reduction_gadget.html',1,'Gadgetron']]],
  ['collectgadget',['CollectGadget',['../class_gadgetron_1_1_collect_gadget.html',1,'Gadgetron']]],
  ['combinegadget',['CombineGadget',['../class_gadgetron_1_1_combine_gadget.html',1,'Gadgetron']]],
  ['commandlineparameter',['CommandLineParameter',['../class_gadgetron_1_1_command_line_parameter.html',1,'Gadgetron']]],
  ['complex_5fim_5frecon_5fbuf_5f',['complex_im_recon_buf_',['../class_gadgetron_1_1_generic_recon_gadget.html#a4b3e2bf20af62f197e60020316e9dce0',1,'Gadgetron::GenericReconGadget']]],
  ['complex_5fto_5fimag',['complex_to_imag',['../namespace_gadgetron.html#a8030bf762d05730f5f2fe383a8bd2d31',1,'Gadgetron']]],
  ['complex_5fto_5freal',['complex_to_real',['../namespace_gadgetron.html#a07f6aecd64395df601545673596f339c',1,'Gadgetron']]],
  ['complex_5fto_5freal_5fimag',['complex_to_real_imag',['../namespace_gadgetron.html#a6383c2390320674990a2a71e54c052aa',1,'Gadgetron']]],
  ['complext',['complext',['../class_gadgetron_1_1complext.html',1,'Gadgetron']]],
  ['complext_2eh',['complext.h',['../complext_8h.html',1,'']]],
  ['complextofloatgadget',['ComplexToFloatGadget',['../class_gadgetron_1_1_complex_to_float_gadget.html',1,'Gadgetron']]],
  ['complextofloatgadget_2eh',['ComplexToFloatGadget.h',['../_complex_to_float_gadget_8h.html',1,'']]],
  ['compute',['compute',['../class_gadgetron_1_1cu_n_f_f_t__plan.html#af7dbeb6c603cdbc095e5171d19d44dcb',1,'Gadgetron::cuNFFT_plan']]],
  ['compute_5f2d_5ffilter',['compute_2d_filter',['../namespace_gadgetron.html#ae1c3d4c0af18629a8ba257369e45e8f9',1,'Gadgetron']]],
  ['compute_5f3d_5ffilter',['compute_3d_filter',['../namespace_gadgetron.html#a62730bd2e1f8b7c020f66ba8199cfc4a',1,'Gadgetron']]],
  ['compute_5faveraged_5fdata_5fn_5fs',['compute_averaged_data_N_S',['../namespace_gadgetron.html#a4d535a7c20a1847d01678a280a47941e',1,'Gadgetron']]],
  ['compute_5feigen_5fchannel_5fcoefficients',['compute_eigen_channel_coefficients',['../namespace_gadgetron.html#ac95f78cf7ce87c439b7a875e1476d335',1,'Gadgetron']]],
  ['compute_5feigen_5fvector',['compute_eigen_vector',['../class_gadgetron_1_1ho_n_d_k_l_t.html#a6e890bd073f3c6e297e60c6a14e7f4e8',1,'Gadgetron::hoNDKLT']]],
  ['compute_5ffilter_5fsnr_5funit_5fscale_5ffactor',['compute_filter_SNR_unit_scale_factor',['../namespace_gadgetron.html#af3bb9522554d738cca9f60379282a36c',1,'Gadgetron']]],
  ['compute_5fnum_5fkept',['compute_num_kept',['../class_gadgetron_1_1ho_n_d_k_l_t.html#ab84a5fd91b41b6e2d4d0a643de30b672',1,'Gadgetron::hoNDKLT']]],
  ['compute_5fparameter_5ftag_5ffrom_5fargs_5flist',['compute_parameter_tag_from_args_list',['../structcrow_1_1black__magic_1_1compute__parameter__tag__from__args__list.html',1,'crow::black_magic']]],
  ['compute_5fparameter_5ftag_5ffrom_5fargs_5flist_3c_20arg_2c_20args_2e_2e_2e_3e',['compute_parameter_tag_from_args_list&lt; Arg, Args...&gt;',['../structcrow_1_1black__magic_1_1compute__parameter__tag__from__args__list_3_01_arg_00_01_args_8_8_8_4.html',1,'crow::black_magic']]],
  ['compute_5fparameter_5ftag_5ffrom_5fargs_5flist_3c_3e',['compute_parameter_tag_from_args_list&lt;&gt;',['../structcrow_1_1black__magic_1_1compute__parameter__tag__from__args__list_3_4.html',1,'crow::black_magic']]],
  ['compute_5frigh_5fhand_5fside',['compute_righ_hand_side',['../class_gadgetron_1_1ho_redundant_wavelet_operator.html#a93f8d7540c7d8ed869c619a484b01cb2',1,'Gadgetron::hoRedundantWaveletOperator::compute_righ_hand_side()'],['../class_gadgetron_1_1ho_s_p_i_r_i_t2_d_t_operator.html#a0661d30a7da2eb27404c18772b5293b5',1,'Gadgetron::hoSPIRIT2DTOperator::compute_righ_hand_side()'],['../class_gadgetron_1_1ho_s_p_i_r_i_t_operator.html#a66fe2f359046b232c90a00afdd2bc66c',1,'Gadgetron::hoSPIRITOperator::compute_righ_hand_side()']]],
  ['compute_5fwavelet_5ffilter',['compute_wavelet_filter',['../class_gadgetron_1_1ho_n_d_redundant_wavelet.html#afe60e0a546b22fe8f81911e8c1994c91',1,'Gadgetron::hoNDRedundantWavelet::compute_wavelet_filter(const std::string &amp;wav_name)'],['../class_gadgetron_1_1ho_n_d_redundant_wavelet.html#ab43bd0d9a2f765485471c557dfe0d2be',1,'Gadgetron::hoNDRedundantWavelet::compute_wavelet_filter(const std::vector&lt; T &gt; &amp;s)']]],
  ['computebsplinecoefficients',['computeBSplineCoefficients',['../class_gadgetron_1_1ho_n_d_b_spline.html#ad0526b00f0a56fc81c4baca102e06b95',1,'Gadgetron::hoNDBSpline']]],
  ['computebsplinederivative',['computeBSplineDerivative',['../class_gadgetron_1_1ho_n_d_b_spline.html#a8d076608999952a252cc1204ed9fed79',1,'Gadgetron::hoNDBSpline']]],
  ['computebsplineinterpolationlocationsandweights',['computeBSplineInterpolationLocationsAndWeights',['../class_gadgetron_1_1ho_n_d_b_spline.html#a3a88cca4655d4aaf7075eca309af6ac6',1,'Gadgetron::hoNDBSpline']]],
  ['computeperiodicboundaryvalues',['computePeriodicBoundaryValues',['../namespace_gadgetron.html#a81a6f0a9bea9d9db4947b4a4217fea93',1,'Gadgetron::computePeriodicBoundaryValues(const hoNDArray&lt; CoordType &gt; &amp;x, const hoNDArray&lt; T &gt; &amp;y, CoordType start, CoordType end, hoNDArray&lt; CoordType &gt; &amp;vx, hoNDArray&lt; T &gt; &amp;vy)'],['../namespace_gadgetron.html#adf4785b9291e5d4db88bb8f790c6be5d',1,'Gadgetron::computePeriodicBoundaryValues(const hoNDArray&lt; CoordType &gt; &amp;x, const hoNDArray&lt; T &gt; &amp;y, CoordType start, CoordType end, hoNDArray&lt; CoordType &gt; &amp;vx, hoNDArray&lt; T &gt; &amp;vy)']]],
  ['concat',['concat',['../structcrow_1_1black__magic_1_1concat.html',1,'crow::black_magic']]],
  ['concat_3c_20seq_3c_20i1_2e_2e_2e_3e_2c_20seq_3c_20i2_2e_2e_2e_3e_20_3e',['concat&lt; seq&lt; I1...&gt;, seq&lt; I2...&gt; &gt;',['../structcrow_1_1black__magic_1_1concat_3_01seq_3_01_i1_8_8_8_4_00_01seq_3_01_i2_8_8_8_4_01_4.html',1,'crow::black_magic']]],
  ['conebeam_5fforwards_5fprojection',['conebeam_forwards_projection',['../namespace_gadgetron.html#a3067321a42b5df3eff9a639a68b27e92',1,'Gadgetron']]],
  ['conj',['conj',['../namespace_gadgetron.html#a30cb03db8db7edb163195db42528518c',1,'Gadgetron::conj(hoNDArray&lt; T &gt; *x)'],['../namespace_gadgetron.html#a6a6db85413732aaf096f9154194b1a35',1,'Gadgetron::conj(cuNDArray&lt; T &gt; *x)']]],
  ['conjugate',['conjugate',['../namespace_gadgetron.html#ad037a9da730f5ecf99426ebd9baeae8e',1,'Gadgetron']]],
  ['connection',['Connection',['../classcrow_1_1_connection.html',1,'crow']]],
  ['const_5fstr',['const_str',['../classcrow_1_1black__magic_1_1const__str.html',1,'crow::black_magic']]],
  ['construct',['construct',['../struct_gadgetron_1_1ho_n_d_array__from__numpy__array.html#a7896f7931060c263dacf5c6609868887',1,'Gadgetron::hoNDArray_from_numpy_array::construct()'],['../struct_gadgetron_1_1ho_n_d_array__from__numpy__array_3_01_i_s_m_r_m_r_d_1_1_acquisition_header_01_4.html#a1d33fc427347b59bd88b5a5f693a0d49',1,'Gadgetron::hoNDArray_from_numpy_array&lt; ISMRMRD::AcquisitionHeader &gt;::construct()'],['../struct_gadgetron_1_1_acquisition_header__from___python_acquisition_header.html#a841454a2340fdfe16d01cce29b124493',1,'Gadgetron::AcquisitionHeader_from_PythonAcquisitionHeader::construct()'],['../struct_gadgetron_1_1_image_header__from___python_image_header.html#a483231f6eda7122cd4d9cdf06497f8f9',1,'Gadgetron::ImageHeader_from_PythonImageHeader::construct()'],['../struct_gadgetron_1_1_ismrmrd_recon_data__from__python__object.html#a8a665b8e8257838db3142c3af5a1fa99',1,'Gadgetron::IsmrmrdReconData_from_python_object::construct()'],['../struct_gadgetron_1_1cpptuple__from__python__tuple.html#a4644002f720393071ca2dd6a86208ab1',1,'Gadgetron::cpptuple_from_python_tuple::construct()']]],
  ['container_5freg_5fmode_5f',['container_reg_mode_',['../class_gadgetron_1_1ho_image_reg_container2_d_registration.html#a561df27465e322c46284259ea24b23fe',1,'Gadgetron::hoImageRegContainer2DRegistration']]],
  ['container_5freg_5ftransformation_5f',['container_reg_transformation_',['../class_gadgetron_1_1ho_image_reg_container2_d_registration.html#a39b45712cddf318dafe69d801cdb247f',1,'Gadgetron::hoImageRegContainer2DRegistration']]],
  ['contains',['contains',['../structcrow_1_1black__magic_1_1contains.html',1,'crow::black_magic']]],
  ['contains_3c_20tp_20_3e',['contains&lt; Tp &gt;',['../structcrow_1_1black__magic_1_1contains_3_01_tp_01_4.html',1,'crow::black_magic']]],
  ['contains_3c_20tp_2c_20head_2c_20rest_2e_2e_2e_3e',['contains&lt; Tp, Head, Rest...&gt;',['../structcrow_1_1black__magic_1_1contains_3_01_tp_00_01_head_00_01_rest_8_8_8_4.html',1,'crow::black_magic']]],
  ['context',['context',['../structcrow_1_1_cookie_parser_1_1context.html',1,'crow::CookieParser']]],
  ['context',['context',['../structcrow_1_1detail_1_1context.html',1,'crow::detail']]],
  ['context_3c_20middlewares_2e_2e_2e_3e',['context&lt; Middlewares...&gt;',['../structcrow_1_1detail_1_1context.html',1,'crow::detail']]],
  ['conv2',['conv2',['../namespace_gadgetron.html#ac46e1ce995f4b88e8ea1703962b33e2e',1,'Gadgetron']]],
  ['conv3',['conv3',['../namespace_gadgetron.html#ac5ee01e7d384af19e1700a42b98f4110',1,'Gadgetron']]],
  ['convert_5fto',['convert_to',['../namespace_gadgetron.html#a3e34ecf898f37540ec5dec5f9944749a',1,'Gadgetron::convert_to(cuNDArray&lt; T &gt; *x)'],['../namespace_gadgetron.html#a8d44c16ed46bc7801b6364c8040330af',1,'Gadgetron::convert_to(cuNDArray&lt; T &gt; *x, cuNDArray&lt; T2 &gt; *y)']]],
  ['convert_5fto_5fimage',['convert_to_image',['../class_gadgetron_1_1ho_redundant_wavelet_operator.html#a41df77c29b9a2a76a19db8e622caea3d',1,'Gadgetron::hoRedundantWaveletOperator::convert_to_image()'],['../class_gadgetron_1_1ho_s_p_i_r_i_t2_d_operator.html#aba5e2597c6613cdc3c3306a0292cf730',1,'Gadgetron::hoSPIRIT2DOperator::convert_to_image()'],['../class_gadgetron_1_1ho_s_p_i_r_i_t2_d_t_operator.html#a6c9b1e2a2189fc3d9c788853bb51553e',1,'Gadgetron::hoSPIRIT2DTOperator::convert_to_image()'],['../class_gadgetron_1_1ho_s_p_i_r_i_t3_d_operator.html#afa3833e72871bc346f824cc75e6a4f4e',1,'Gadgetron::hoSPIRIT3DOperator::convert_to_image()'],['../class_gadgetron_1_1ho_s_p_i_r_i_t_operator.html#ae780aa340f9430fb74cf46930b0bc104',1,'Gadgetron::hoSPIRITOperator::convert_to_image()']]],
  ['convert_5fto_5fkspace',['convert_to_kspace',['../class_gadgetron_1_1ho_s_p_i_r_i_t3_d_operator.html#ad9bb63642805ea2f111a4b0f15e651a2',1,'Gadgetron::hoSPIRIT3DOperator']]],
  ['convertible',['convertible',['../struct_gadgetron_1_1ho_n_d_array__from__numpy__array.html#afc723a9a9501bdd97b2a0cb2d4aea019',1,'Gadgetron::hoNDArray_from_numpy_array::convertible()'],['../struct_gadgetron_1_1ho_n_d_array__from__numpy__array_3_01_i_s_m_r_m_r_d_1_1_acquisition_header_01_4.html#ae94dd73bcc876c9456edbefb3909419f',1,'Gadgetron::hoNDArray_from_numpy_array&lt; ISMRMRD::AcquisitionHeader &gt;::convertible()'],['../struct_gadgetron_1_1_acquisition_header__from___python_acquisition_header.html#a3a2ab058b21dbac85d7c65308f9919ac',1,'Gadgetron::AcquisitionHeader_from_PythonAcquisitionHeader::convertible()'],['../struct_gadgetron_1_1_image_header__from___python_image_header.html#ab521516bf3b5b9ec1d3cdcdf8bda954b',1,'Gadgetron::ImageHeader_from_PythonImageHeader::convertible()'],['../struct_gadgetron_1_1_ismrmrd_recon_data__from__python__object.html#a224ac9be3b320108b7f16f92f096ce5e',1,'Gadgetron::IsmrmrdReconData_from_python_object::convertible()'],['../struct_gadgetron_1_1cpptuple__from__python__tuple.html#a459c8166c537eb285d82e70a03a11acc',1,'Gadgetron::cpptuple_from_python_tuple::convertible()']]],
  ['converttointerpolationcoefficients',['ConvertToInterpolationCoefficients',['../class_gadgetron_1_1ho_n_d_b_spline.html#a76e12797659948b308c855c263ec6e04',1,'Gadgetron::hoNDBSpline']]],
  ['convolutionoperator',['convolutionOperator',['../class_gadgetron_1_1convolution_operator.html',1,'Gadgetron']]],
  ['convolutionoperator_2eh',['convolutionOperator.h',['../convolution_operator_8h.html',1,'']]],
  ['convolutionoperator_3c_20cundarray_3c_20complext_3c_20real_20_3e_20_3e_2c_20d_20_3e',['convolutionOperator&lt; cuNDArray&lt; complext&lt; REAL &gt; &gt;, D &gt;',['../class_gadgetron_1_1convolution_operator.html',1,'Gadgetron']]],
  ['convolve',['convolve',['../class_gadgetron_1_1cu_n_f_f_t__plan.html#adb1edf9e9720ea66cb343327061cc118',1,'Gadgetron::cuNFFT_plan']]],
  ['cookieparser',['CookieParser',['../structcrow_1_1_cookie_parser.html',1,'crow']]],
  ['coordarraytype',['CoordArrayType',['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#aa467c9da13e593663bc399ab464aabf7',1,'Gadgetron::gtPlus::gtplusFFDBase']]],
  ['copy_5fand_5freset_5ftransform',['copy_and_reset_transform',['../class_gadgetron_1_1ho_n_d_k_l_t.html#aaec716c5a3a3c8764ed4c127a44a679a',1,'Gadgetron::hoNDKLT']]],
  ['copyfrom',['copyFrom',['../class_gadgetron_1_1ho_n_d_image_container2_d.html#a1568b4870a3bfcbbfb45625917c2ec9d',1,'Gadgetron::hoNDImageContainer2D']]],
  ['copyreconresultssecond',['copyReconResultsSecond',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian.html#a04cffd63bdb9ecc7ae2b48ed515371d1',1,'Gadgetron::gtPlus::gtPlusISMRMRDReconWorkFlowCartesian']]],
  ['core_5fdefines_2eh',['core_defines.h',['../core__defines_8h.html',1,'']]],
  ['corrcoef',['corrCoef',['../namespace_gadgetron.html#a7655b0cbaec1434d7f5c51eceba6d510',1,'Gadgetron']]],
  ['cplxdumpgadget',['CplxDumpGadget',['../class_gadgetron_1_1_cplx_dump_gadget.html',1,'Gadgetron']]],
  ['cpptuple2pytuple',['cpptuple2pytuple',['../namespace_gadgetron.html#a7d23d02b14ebb66dec21f6a62e2ea23a',1,'Gadgetron']]],
  ['cpptuple2pytuple_5fwrapper',['cpptuple2pytuple_wrapper',['../struct_gadgetron_1_1cpptuple2pytuple__wrapper.html',1,'Gadgetron']]],
  ['cpptuple_5ffrom_5fpython_5ftuple',['cpptuple_from_python_tuple',['../struct_gadgetron_1_1cpptuple__from__python__tuple.html',1,'Gadgetron']]],
  ['cpptuple_5fto_5fpython_5ftuple',['cpptuple_to_python_tuple',['../struct_gadgetron_1_1cpptuple__to__python__tuple.html',1,'Gadgetron']]],
  ['cpucore_5fexport_2eh',['cpucore_export.h',['../cpucore__export_8h.html',1,'']]],
  ['cpucore_5fmath_5fexport_2eh',['cpucore_math_export.h',['../cpucore__math__export_8h.html',1,'']]],
  ['cpufft_5fexport_2eh',['cpufft_export.h',['../cpufft__export_8h.html',1,'']]],
  ['cpuklt_5fexport_2eh',['cpuklt_export.h',['../cpuklt__export_8h.html',1,'']]],
  ['cpuoperatorexport_2eh',['cpuOperatorExport.h',['../cpu_operator_export_8h.html',1,'']]],
  ['cpuregistrationaveraginggadget2d',['cpuRegistrationAveragingGadget2D',['../class_gadgetron_1_1cpu_registration_averaging_gadget2_d.html',1,'Gadgetron']]],
  ['cpusolver_5fexport_2eh',['cpusolver_export.h',['../cpusolver__export_8h.html',1,'']]],
  ['create',['create',['../class_gadgetron_1_1ho_n_d_image.html#a293b53108c585e9fe2ff71ebf576db07',1,'Gadgetron::hoNDImage::create(const std::vector&lt; size_t &gt; &amp;dimensions)'],['../class_gadgetron_1_1ho_n_d_image.html#a6a5a752565ca8ce5dd02886ced609fa0',1,'Gadgetron::hoNDImage::create(const hoNDImage&lt; T2, D &gt; &amp;im)'],['../class_gadgetron_1_1ho_n_d_image_container2_d.html#aa3be8e3f8bbb3a7b18bbadc01728ccb9',1,'Gadgetron::hoNDImageContainer2D::create(const std::vector&lt; size_t &gt; &amp;col, bool createImage=true)'],['../class_gadgetron_1_1ho_n_d_image_container2_d.html#a65c1c89fc601ae1731de11158345886a',1,'Gadgetron::hoNDImageContainer2D::create(const std::vector&lt; size_t &gt; &amp;col, const std::vector&lt; size_t &gt; &amp;dimensions)'],['../class_gadgetron_1_1ho_n_d_image_container2_d.html#a876e4e2508185405b499a8617defb515',1,'Gadgetron::hoNDImageContainer2D::create(value_type *buf, const std::vector&lt; size_t &gt; &amp;dim)']]],
  ['create_5fhondarray_5fconverter',['create_hoNDArray_converter',['../namespace_gadgetron.html#ab0ff6f18e8c1256210089f003bec74a9',1,'Gadgetron']]],
  ['create_5fismrmrd_5facquisitionheader_5fconverter',['create_ismrmrd_AcquisitionHeader_converter',['../namespace_gadgetron.html#aa345ecb9201968edbc0c6f882ef57ac1',1,'Gadgetron']]],
  ['create_5fismrmrd_5fimageheader_5fconverter',['create_ismrmrd_ImageHeader_converter',['../namespace_gadgetron.html#a03d26ae62b82d9bd394e090499440d0a',1,'Gadgetron']]],
  ['create_5ftuple_5fconverter',['create_tuple_converter',['../namespace_gadgetron.html#aeae37dabdb2097095ce2489a51dc9b69',1,'Gadgetron']]],
  ['create_5fvector_5fconverter',['create_vector_converter',['../namespace_gadgetron.html#afb3b2dfc4b227eae7bd4d45e67cac5fc',1,'Gadgetron']]],
  ['createdissimilarity',['createDissimilarity',['../class_gadgetron_1_1ho_image_reg_register.html#ae9fdaaa4ba8d7a582721703bc3d4daa8',1,'Gadgetron::hoImageRegRegister']]],
  ['createfrom',['createFrom',['../class_gadgetron_1_1ho_n_d_image.html#a44e506bf1025ba86b1995f1ce943f637',1,'Gadgetron::hoNDImage']]],
  ['createparametricsolver',['createParametricSolver',['../class_gadgetron_1_1ho_image_reg_parametric_register.html#a978257a8b58ff37e63a7bec08f953fd9',1,'Gadgetron::hoImageRegParametricRegister']]],
  ['crop',['crop',['../namespace_gadgetron.html#a7b440908acbe7e426fbfa40257e9e3e7',1,'Gadgetron::crop(const vector_td&lt; size_t, D &gt; &amp;crop_offset, const vector_td&lt; size_t, D &gt; &amp;crop_size, hoNDArray&lt; T &gt; *in, hoNDArray&lt; T &gt; *out)'],['../namespace_gadgetron.html#adebc8c353d1bc199ece1c4036166d08b',1,'Gadgetron::crop(const vector_td&lt; size_t, D &gt; &amp;crop_size, hoNDArray&lt; T &gt; *in, hoNDArray&lt; T &gt; *out)'],['../namespace_gadgetron.html#a79d2b7f27db05274a1a798b19c766832',1,'Gadgetron::crop(typename uint64d&lt; D &gt;::Type crop_offset, typename uint64d&lt; D &gt;::Type crop_size, cuNDArray&lt; T &gt; *in)'],['../namespace_gadgetron.html#a81dff177e8c459445a85707551f4efed',1,'Gadgetron::crop(typename uint64d&lt; D &gt;::Type crop_offset, cuNDArray&lt; T &gt; *in, cuNDArray&lt; T &gt; *out)']]],
  ['cropandcombinegadget',['CropAndCombineGadget',['../class_gadgetron_1_1_crop_and_combine_gadget.html',1,'Gadgetron']]],
  ['cropover3rddimension',['cropOver3rdDimension',['../namespace_gadgetron.html#ab443f98b0c4b0b88ab79f3bfecd54082',1,'Gadgetron::cropOver3rdDimension(const hoNDArray&lt; T &gt; &amp;x, hoNDArray&lt; T &gt; &amp;r, size_t start, size_t end)'],['../namespace_gadgetron.html#a618d5c24f61d274f6b7034d86c082deb',1,'Gadgetron::cropOver3rdDimension(const hoNDArray&lt; T &gt; &amp;x, hoNDArray&lt; T &gt; &amp;r, size_t start, size_t end)']]],
  ['cropupto11darray',['cropUpTo11DArray',['../namespace_gadgetron.html#a9f758d1043a1d071d2e3a498ba202a4f',1,'Gadgetron::cropUpTo11DArray(const hoNDArray&lt; T &gt; &amp;x, hoNDArray&lt; T &gt; &amp;r, const std::vector&lt; size_t &gt; &amp;startND, std::vector&lt; size_t &gt; &amp;size)'],['../namespace_gadgetron.html#a8906c226f4508024d164af4e3473ecce',1,'Gadgetron::cropUpTo11DArray(const hoNDArray&lt; T &gt; &amp;x, hoNDArray&lt; T &gt; &amp;r, const std::vector&lt; size_t &gt; &amp;startND, std::vector&lt; size_t &gt; &amp;size)']]],
  ['crow',['Crow',['../classcrow_1_1_crow.html',1,'crow']]],
  ['csfreqoperator',['CSfreqOperator',['../class_gadgetron_1_1_c_sfreq_operator.html',1,'Gadgetron']]],
  ['csi_5fdft',['CSI_dft',['../namespace_gadgetron.html#a9ad2712306e565ae66dc23c7c6970179',1,'Gadgetron']]],
  ['csi_5fdfth',['CSI_dftH',['../namespace_gadgetron.html#ab9f82aca211f740f1d9f23765247bd10',1,'Gadgetron']]],
  ['csigadget',['CSIGadget',['../class_gadgetron_1_1_c_s_i_gadget.html',1,'Gadgetron']]],
  ['csioperator',['CSIOperator',['../class_gadgetron_1_1_c_s_i_operator.html',1,'Gadgetron']]],
  ['ctrl_5fpt_5f',['ctrl_pt_',['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#a770a7053fa024b2802397f68900d1ebd',1,'Gadgetron::gtPlus::gtplusFFDBase']]],
  ['cublascontextprovider',['CUBLASContextProvider',['../class_c_u_b_l_a_s_context_provider.html',1,'']]],
  ['cubuffer',['cuBuffer',['../class_gadgetron_1_1cu_buffer.html',1,'Gadgetron']]],
  ['cubuffer_3c_20double_2c_20d_2c_20true_20_3e',['cuBuffer&lt; double, D, true &gt;',['../class_gadgetron_1_1cu_buffer_3_01double_00_01_d_00_01true_01_4.html',1,'Gadgetron']]],
  ['cucartesiansenseoperator',['cuCartesianSenseOperator',['../class_gadgetron_1_1cu_cartesian_sense_operator.html',1,'Gadgetron']]],
  ['cucartesiansenseoperator_2eh',['cuCartesianSenseOperator.h',['../cu_cartesian_sense_operator_8h.html',1,'']]],
  ['cucghsofsolver',['cuCGHSOFSolver',['../class_gadgetron_1_1cu_c_g_h_s_o_f_solver.html',1,'Gadgetron']]],
  ['cucgpreconditioner',['cuCgPreconditioner',['../class_gadgetron_1_1cu_cg_preconditioner.html',1,'Gadgetron']]],
  ['cucgsolver',['cuCgSolver',['../class_gadgetron_1_1cu_cg_solver.html',1,'Gadgetron']]],
  ['cucgsolver_2eh',['cuCgSolver.h',['../cu_cg_solver_8h.html',1,'']]],
  ['cucgsolver_3c_20float_5fcomplext_20_3e',['cuCgSolver&lt; float_complext &gt;',['../class_gadgetron_1_1cu_cg_solver.html',1,'Gadgetron']]],
  ['cucgsolver_3c_20gadgetron_3a_3acomplext_20_3e',['cuCgSolver&lt; Gadgetron::complext &gt;',['../class_gadgetron_1_1cu_cg_solver.html',1,'Gadgetron']]],
  ['cuckopticalflowsolver',['cuCKOpticalFlowSolver',['../class_gadgetron_1_1cu_c_k_optical_flow_solver.html',1,'Gadgetron']]],
  ['cuckopticalflowsolver_2eh',['cuCKOpticalFlowSolver.h',['../cu_c_k_optical_flow_solver_8h.html',1,'']]],
  ['cuconvolutionoperator',['cuConvolutionOperator',['../class_gadgetron_1_1cu_convolution_operator.html',1,'Gadgetron']]],
  ['cuconvolutionoperator_2eh',['cuConvolutionOperator.h',['../cu_convolution_operator_8h.html',1,'']]],
  ['cucsrmatrix',['cuCsrMatrix',['../struct_gadgetron_1_1cu_csr_matrix.html',1,'Gadgetron']]],
  ['cuda_5fcall',['CUDA_CALL',['../check___c_u_d_a_8h.html#af7f053aeb05fa4889b8746907b71c1c1',1,'check_CUDA.h']]],
  ['cuda_5ferror',['cuda_error',['../class_gadgetron_1_1cuda__error.html',1,'Gadgetron']]],
  ['cudadevicemanager',['cudaDeviceManager',['../class_gadgetron_1_1cuda_device_manager.html',1,'Gadgetron']]],
  ['cudiagonaloperator',['cuDiagonalOperator',['../class_gadgetron_1_1cu_diagonal_operator.html',1,'Gadgetron']]],
  ['cudiagonaloperator_2eh',['cuDiagonalOperator.h',['../cu_diagonal_operator_8h.html',1,'']]],
  ['cudiagonalsumoperator',['cuDiagonalSumOperator',['../class_gadgetron_1_1cu_diagonal_sum_operator.html',1,'Gadgetron']]],
  ['cudiagonalsumoperator_2eh',['cuDiagonalSumOperator.h',['../cu_diagonal_sum_operator_8h.html',1,'']]],
  ['cudownsampleoperator',['cuDownsampleOperator',['../class_gadgetron_1_1cu_downsample_operator.html',1,'Gadgetron']]],
  ['cudownsampleoperator_2eh',['cuDownsampleOperator.h',['../cu_downsample_operator_8h.html',1,'']]],
  ['cudwtoperator',['cuDWTOperator',['../class_gadgetron_1_1cu_d_w_t_operator.html',1,'Gadgetron']]],
  ['cufftgadget',['cuFFTGadget',['../class_gadgetron_1_1cu_f_f_t_gadget.html',1,'Gadgetron']]],
  ['cufftoperator',['cuFFTOperator',['../class_gadgetron_1_1cu_f_f_t_operator.html',1,'Gadgetron']]],
  ['cufftoperator_2eh',['cuFFTOperator.h',['../cu_f_f_t_operator_8h.html',1,'']]],
  ['cuglreconwidget',['cuGLReconWidget',['../classcu_g_l_recon_widget.html',1,'']]],
  ['cugpbbsolver',['cuGpBbSolver',['../class_gadgetron_1_1cu_gp_bb_solver.html',1,'Gadgetron']]],
  ['cuhaarwaveletoperator',['cuHaarWaveletOperator',['../class_gadgetron_1_1cu_haar_wavelet_operator.html',1,'Gadgetron']]],
  ['cuhsopticalflowsolver',['cuHSOpticalFlowSolver',['../class_gadgetron_1_1cu_h_s_optical_flow_solver.html',1,'Gadgetron']]],
  ['cuhsopticalflowsolver_2eh',['cuHSOpticalFlowSolver.h',['../cu_h_s_optical_flow_solver_8h.html',1,'']]],
  ['cuidentityoperator',['cuIdentityOperator',['../class_gadgetron_1_1cu_identity_operator.html',1,'Gadgetron']]],
  ['cuidentityoperator_2eh',['cuIdentityOperator.h',['../cu_identity_operator_8h.html',1,'']]],
  ['cuimageoperator',['cuImageOperator',['../class_gadgetron_1_1cu_image_operator.html',1,'Gadgetron']]],
  ['cuimageoperator_2eh',['cuImageOperator.h',['../cu_image_operator_8h.html',1,'']]],
  ['culaplaceoperator',['cuLaplaceOperator',['../class_gadgetron_1_1cu_laplace_operator.html',1,'Gadgetron']]],
  ['culaplaceoperator_2eh',['cuLaplaceOperator.h',['../cu_laplace_operator_8h.html',1,'']]],
  ['culbfgssolver',['cuLbfgsSolver',['../class_gadgetron_1_1cu_lbfgs_solver.html',1,'Gadgetron']]],
  ['culinearresampleoperator',['cuLinearResampleOperator',['../class_gadgetron_1_1cu_linear_resample_operator.html',1,'Gadgetron']]],
  ['culwsolver',['cuLwSolver',['../class_gadgetron_1_1cu_lw_solver.html',1,'Gadgetron']]],
  ['cumultiplicationoperatorcontainer',['cuMultiplicationOperatorContainer',['../class_gadgetron_1_1cu_multiplication_operator_container.html',1,'Gadgetron']]],
  ['cumultiplicationoperatorcontainer_2eh',['cuMultiplicationOperatorContainer.h',['../cu_multiplication_operator_container_8h.html',1,'']]],
  ['cundarray',['cuNDArray',['../class_gadgetron_1_1cu_n_d_array.html',1,'Gadgetron']]],
  ['cundarray_2eh',['cuNDArray.h',['../cu_n_d_array_8h.html',1,'']]],
  ['cundarray_3c_20float_20_3e',['cuNDArray&lt; float &gt;',['../class_gadgetron_1_1cu_n_d_array.html',1,'Gadgetron']]],
  ['cundarray_3c_20float_5fcomplext_20_3e',['cuNDArray&lt; float_complext &gt;',['../class_gadgetron_1_1cu_n_d_array.html',1,'Gadgetron']]],
  ['cundarray_3c_20gadgetron_3a_3acomplext_20_3e',['cuNDArray&lt; Gadgetron::complext &gt;',['../class_gadgetron_1_1cu_n_d_array.html',1,'Gadgetron']]],
  ['cundarray_3c_20realtype_3c_20gadgetron_3a_3acomplext_20_3e_3a_3atype_20_3e',['cuNDArray&lt; realType&lt; Gadgetron::complext &gt;::Type &gt;',['../class_gadgetron_1_1cu_n_d_array.html',1,'Gadgetron']]],
  ['cundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e',['cuNDArray&lt; realType&lt; T &gt;::type &gt;',['../class_gadgetron_1_1cu_n_d_array.html',1,'Gadgetron::cuNDArray&lt; realType&lt; T &gt;::type &gt;'],['../class_gadgetron_1_1cu_n_d_array.html',1,'Gadgetron::cuNDArray&lt; realType&lt; T &gt;::Type &gt;']]],
  ['cundarray_5fblas_2eh',['cuNDArray_blas.h',['../cu_n_d_array__blas_8h.html',1,'']]],
  ['cundarray_5felemwise_2eh',['cuNDArray_elemwise.h',['../cu_n_d_array__elemwise_8h.html',1,'']]],
  ['cundarray_5foperators_2eh',['cuNDArray_operators.h',['../cu_n_d_array__operators_8h.html',1,'']]],
  ['cundarray_5futils_2eh',['cuNDArray_utils.h',['../cu_n_d_array__utils_8h.html',1,'']]],
  ['cundfft',['cuNDFFT',['../class_gadgetron_1_1cu_n_d_f_f_t.html',1,'Gadgetron']]],
  ['cundfft_2eh',['cuNDFFT.h',['../cu_n_d_f_f_t_8h.html',1,'']]],
  ['cunfft_2eh',['cuNFFT.h',['../cu_n_f_f_t_8h.html',1,'']]],
  ['cunfft_5fplan',['cuNFFT_plan',['../class_gadgetron_1_1cu_n_f_f_t__plan.html',1,'Gadgetron']]],
  ['cunfft_5fplan',['cuNFFT_plan',['../class_gadgetron_1_1cu_n_f_f_t__plan.html#a2027742a5acda480a2cc5b2204d3a387',1,'Gadgetron::cuNFFT_plan::cuNFFT_plan()'],['../class_gadgetron_1_1cu_n_f_f_t__plan.html#a03bc15161a4ded9d16badd23ff56ba3d',1,'Gadgetron::cuNFFT_plan::cuNFFT_plan(typename uint64d&lt; D &gt;::Type matrix_size, typename uint64d&lt; D &gt;::Type matrix_size_os, REAL W, int device=-1)']]],
  ['cunfft_5fplan_3c_20double_2c_20d_2c_20true_20_3e',['cuNFFT_plan&lt; double, D, true &gt;',['../class_gadgetron_1_1cu_n_f_f_t__plan_3_01double_00_01_d_00_01true_01_4.html',1,'Gadgetron']]],
  ['cunfft_5fplan_3c_20float_2c_202_20_3e',['cuNFFT_plan&lt; float, 2 &gt;',['../class_gadgetron_1_1cu_n_f_f_t__plan.html',1,'Gadgetron']]],
  ['cunfftoperator',['cuNFFTOperator',['../class_gadgetron_1_1cu_n_f_f_t_operator.html',1,'Gadgetron']]],
  ['cunfftoperator_3c_20real_2c_202_20_3e',['cuNFFTOperator&lt; REAL, 2 &gt;',['../class_gadgetron_1_1cu_n_f_f_t_operator.html',1,'Gadgetron']]],
  ['cunlcgsolver',['cuNlcgSolver',['../class_gadgetron_1_1cu_nlcg_solver.html',1,'Gadgetron']]],
  ['cunlcgsolver_3c_20gadgetron_3a_3acomplext_20_3e',['cuNlcgSolver&lt; Gadgetron::complext &gt;',['../class_gadgetron_1_1cu_nlcg_solver.html',1,'Gadgetron']]],
  ['cunoncartesianktsenseoperator',['cuNonCartesianKtSenseOperator',['../class_gadgetron_1_1cu_non_cartesian_kt_sense_operator.html',1,'Gadgetron']]],
  ['cunoncartesianktsenseoperator_2eh',['cuNonCartesianKtSenseOperator.h',['../cu_non_cartesian_kt_sense_operator_8h.html',1,'']]],
  ['cunoncartesiansenseoperator',['cuNonCartesianSenseOperator',['../class_gadgetron_1_1cu_non_cartesian_sense_operator.html',1,'Gadgetron']]],
  ['cunoncartesiansenseoperator_2eh',['cuNonCartesianSenseOperator.h',['../cu_non_cartesian_sense_operator_8h.html',1,'']]],
  ['cunoncartesiansenseoperator_3c_20double_2c_20d_2c_20true_20_3e',['cuNonCartesianSenseOperator&lt; double, D, true &gt;',['../class_gadgetron_1_1cu_non_cartesian_sense_operator_3_01double_00_01_d_00_01true_01_4.html',1,'Gadgetron']]],
  ['cunoncartesiansenseoperator_3c_20real_2c_20d_20_3e',['cuNonCartesianSenseOperator&lt; REAL, D &gt;',['../class_gadgetron_1_1cu_non_cartesian_sense_operator.html',1,'Gadgetron']]],
  ['cuopticalflowsolver',['cuOpticalFlowSolver',['../class_gadgetron_1_1cu_optical_flow_solver.html',1,'Gadgetron']]],
  ['cuopticalflowsolver_2eh',['cuOpticalFlowSolver.h',['../cu_optical_flow_solver_8h.html',1,'']]],
  ['cupartialderivativeoperator',['cuPartialDerivativeOperator',['../class_gadgetron_1_1cu_partial_derivative_operator.html',1,'Gadgetron']]],
  ['cupartialderivativeoperator_2eh',['cuPartialDerivativeOperator.h',['../cu_partial_derivative_operator_8h.html',1,'']]],
  ['cupartialderivativeoperator2',['cuPartialDerivativeOperator2',['../class_gadgetron_1_1cu_partial_derivative_operator2.html',1,'Gadgetron']]],
  ['curesampleoperator',['cuResampleOperator',['../class_gadgetron_1_1cu_resample_operator.html',1,'Gadgetron']]],
  ['cusbccgsolver',['cuSbcCgSolver',['../class_gadgetron_1_1cu_sbc_cg_solver.html',1,'Gadgetron']]],
  ['cusbccgsolver_3c_20gadgetron_3a_3acomplext_20_3e',['cuSbcCgSolver&lt; Gadgetron::complext &gt;',['../class_gadgetron_1_1cu_sbc_cg_solver.html',1,'Gadgetron']]],
  ['cusbcgsolver',['cuSbCgSolver',['../class_gadgetron_1_1cu_sb_cg_solver.html',1,'Gadgetron']]],
  ['cusbclwsolver',['cuSbcLwSolver',['../class_gadgetron_1_1cu_sbc_lw_solver.html',1,'Gadgetron']]],
  ['cusblwsolver',['cuSbLwSolver',['../classcu_sb_lw_solver.html',1,'']]],
  ['cusensebuffer',['cuSenseBuffer',['../class_gadgetron_1_1cu_sense_buffer.html',1,'Gadgetron']]],
  ['cusensebuffer_3c_20double_2c_20d_2c_20true_20_3e',['cuSenseBuffer&lt; double, D, true &gt;',['../class_gadgetron_1_1cu_sense_buffer_3_01double_00_01_d_00_01true_01_4.html',1,'Gadgetron']]],
  ['cusensebuffercg',['cuSenseBufferCg',['../class_gadgetron_1_1cu_sense_buffer_cg.html',1,'Gadgetron']]],
  ['cusensebuffercg_3c_20double_2c_20d_2c_20true_20_3e',['cuSenseBufferCg&lt; double, D, true &gt;',['../class_gadgetron_1_1cu_sense_buffer_cg_3_01double_00_01_d_00_01true_01_4.html',1,'Gadgetron']]],
  ['cusensedata',['cuSenseData',['../struct_gadgetron_1_1cu_sense_data.html',1,'Gadgetron']]],
  ['cusenseoperator',['cuSenseOperator',['../class_gadgetron_1_1cu_sense_operator.html',1,'Gadgetron']]],
  ['cusenseoperator_2eh',['cuSenseOperator.h',['../cu_sense_operator_8h.html',1,'']]],
  ['cuspirit2doperator',['cuSpirit2DOperator',['../class_gadgetron_1_1cu_spirit2_d_operator.html',1,'Gadgetron']]],
  ['cuspiritbuffer',['cuSpiritBuffer',['../class_gadgetron_1_1cu_spirit_buffer.html',1,'Gadgetron']]],
  ['cuspiritbuffer_3c_20double_2c_20d_2c_20true_20_3e',['cuSpiritBuffer&lt; double, D, true &gt;',['../class_gadgetron_1_1cu_spirit_buffer_3_01double_00_01_d_00_01true_01_4.html',1,'Gadgetron']]],
  ['cuspiritoperator_2eh',['cuSpiritOperator.h',['../cu_spirit_operator_8h.html',1,'']]],
  ['cutv1doperator',['cuTv1DOperator',['../class_gadgetron_1_1cu_tv1_d_operator.html',1,'Gadgetron']]],
  ['cutvoperator',['cuTvOperator',['../class_gadgetron_1_1cu_tv_operator.html',1,'Gadgetron']]],
  ['cutvoperator_2eh',['cuTvOperator.h',['../cu_tv_operator_8h.html',1,'']]],
  ['cutvpicsoperator',['cuTvPicsOperator',['../class_gadgetron_1_1cu_tv_pics_operator.html',1,'Gadgetron']]],
  ['cutxgadget',['CutXGadget',['../class_gadgetron_1_1_cut_x_gadget.html',1,'Gadgetron']]],
  ['cuupsampleoperator',['cuUpsampleOperator',['../class_gadgetron_1_1cu_upsample_operator.html',1,'Gadgetron']]],
  ['cuupsampleoperator_2eh',['cuUpsampleOperator.h',['../cu_upsample_operator_8h.html',1,'']]]
];
