var searchData=
[
  ['gadget',['Gadget',['../class_gadgetron_1_1_gadget.html',1,'Gadgetron::Gadget'],['../classgadgetron_1_1_gadget.html',1,'gadgetron.Gadget']]],
  ['gadget',['Gadget',['../struct_gadgetron_x_m_l_1_1_gadget.html',1,'GadgetronXML']]],
  ['gadget1',['Gadget1',['../class_gadgetron_1_1_gadget1.html',1,'Gadgetron']]],
  ['gadget1_3c_20cusensedata_20_3e',['Gadget1&lt; cuSenseData &gt;',['../class_gadgetron_1_1_gadget1.html',1,'Gadgetron']]],
  ['gadget1_3c_20ismrmrd_3a_3aimageheader_20_3e',['Gadget1&lt; ISMRMRD::ImageHeader &gt;',['../class_gadgetron_1_1_gadget1.html',1,'Gadgetron']]],
  ['gadget1_3c_20ismrmrdacquisitionbucket_20_3e',['Gadget1&lt; IsmrmrdAcquisitionBucket &gt;',['../class_gadgetron_1_1_gadget1.html',1,'Gadgetron']]],
  ['gadget1_3c_20ismrmrdimagearray_20_3e',['Gadget1&lt; IsmrmrdImageArray &gt;',['../class_gadgetron_1_1_gadget1.html',1,'Gadgetron']]],
  ['gadget1_3c_20ismrmrdrecondata_20_3e',['Gadget1&lt; IsmrmrdReconData &gt;',['../class_gadgetron_1_1_gadget1.html',1,'Gadgetron']]],
  ['gadget1_3c_20t_20_3e',['Gadget1&lt; T &gt;',['../class_gadgetron_1_1_gadget1.html',1,'Gadgetron']]],
  ['gadget2',['Gadget2',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20gtplusgadgetimagearray_2c_20gadgetron_3a_3agtplus_3a_3agtplusreconworkorder_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e_20_3e',['Gadget2&lt; GtPlusGadgetImageArray, Gadgetron::gtPlus::gtPlusReconWorkOrder&lt; std::complex&lt; float &gt; &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20int_2c_20gtplusrecon2dtcloudpackagecpfl_20_3e',['Gadget2&lt; int, GtPlusRecon2DTCloudPackageCPFL &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20int_2c_20gtplusreconjobtypecpfl_20_3e',['Gadget2&lt; int, GtPlusReconJobTypeCPFL &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aacquisitionheader_2c_20hondarray_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e_20_3e',['Gadget2&lt; ISMRMRD::AcquisitionHeader, hoNDArray&lt; std::complex&lt; float &gt; &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aimageheader_2c_20genericreconjob_20_3e',['Gadget2&lt; ISMRMRD::ImageHeader, GenericReconJob &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aimageheader_2c_20hondarray_3c_20ace_5fuint16_20_3e_20_3e',['Gadget2&lt; ISMRMRD::ImageHeader, hoNDArray&lt; ACE_UINT16 &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aimageheader_2c_20hondarray_3c_20array_5ftype_3a_3aelement_5ftype_20_3e_20_3e',['Gadget2&lt; ISMRMRD::ImageHeader, hoNDArray&lt; ARRAY_TYPE::element_type &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aimageheader_2c_20hondarray_3c_20cundarray_3c_20float_20_3e_3a_3aelement_5ftype_20_3e_20_3e',['Gadget2&lt; ISMRMRD::ImageHeader, hoNDArray&lt; cuNDArray&lt; float &gt;::element_type &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aimageheader_2c_20hondarray_3c_20float_20_3e_20_3e',['Gadget2&lt; ISMRMRD::ImageHeader, hoNDArray&lt; float &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aimageheader_2c_20hondarray_3c_20hondarray_3c_20float_20_3e_3a_3aelement_5ftype_20_3e_20_3e',['Gadget2&lt; ISMRMRD::ImageHeader, hoNDArray&lt; hoNDArray&lt; float &gt;::element_type &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aimageheader_2c_20hondarray_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e_20_3e',['Gadget2&lt; ISMRMRD::ImageHeader, hoNDArray&lt; std::complex&lt; float &gt; &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20ismrmrd_3a_3aimageheader_2c_20hondarray_3c_20t_20_3e_20_3e',['Gadget2&lt; ISMRMRD::ImageHeader, hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget2_3c_20t_2c_20hondarray_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e_20_3e',['Gadget2&lt; T, hoNDArray&lt; std::complex&lt; float &gt; &gt; &gt;',['../class_gadgetron_1_1_gadget2.html',1,'Gadgetron']]],
  ['gadget3',['Gadget3',['../class_gadgetron_1_1_gadget3.html',1,'Gadgetron']]],
  ['gadget3_3c_20grappaunmixingjob_2c_20ismrmrd_3a_3aimageheader_2c_20hondarray_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e_20_3e',['Gadget3&lt; GrappaUnmixingJob, ISMRMRD::ImageHeader, hoNDArray&lt; std::complex&lt; float &gt; &gt; &gt;',['../class_gadgetron_1_1_gadget3.html',1,'Gadgetron']]],
  ['gadget3_3c_20ismrmrd_3a_3aacquisitionheader_2c_20hondarray_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e_2c_20hondarray_3c_20float_20_3e_20_3e',['Gadget3&lt; ISMRMRD::AcquisitionHeader, hoNDArray&lt; std::complex&lt; float &gt; &gt;, hoNDArray&lt; float &gt; &gt;',['../class_gadgetron_1_1_gadget3.html',1,'Gadgetron']]],
  ['gadget_5fmessage_5facquisition',['GADGET_MESSAGE_ACQUISITION',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa3f720b72ee362a925d3f7cd316b0f8db',1,'Gadgetron']]],
  ['gadget_5fmessage_5fdicom',['GADGET_MESSAGE_DICOM',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa8ada0e1b1d85fbc9359d7239d8532cab',1,'Gadgetron']]],
  ['gadget_5fmessage_5fempty',['GADGET_MESSAGE_EMPTY',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaabfd881e31b57cebf24f97780fb226dac',1,'Gadgetron']]],
  ['gadget_5fmessage_5fend_5fof_5fscan',['GADGET_MESSAGE_END_OF_SCAN',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa87fe309c127e497d1a9c2fe950d1366f',1,'Gadgetron']]],
  ['gadget_5fmessage_5fimage_5fcplx_5ffloat',['GADGET_MESSAGE_IMAGE_CPLX_FLOAT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa04095dbeac1de5a8332186ed06195c71',1,'Gadgetron']]],
  ['gadget_5fmessage_5fimage_5freal_5ffloat',['GADGET_MESSAGE_IMAGE_REAL_FLOAT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaafc70a4970755763c21b96f596d6973cf',1,'Gadgetron']]],
  ['gadget_5fmessage_5fimage_5freal_5fushort',['GADGET_MESSAGE_IMAGE_REAL_USHORT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa8a75a15bef4f816f3d996f80b42d6fed',1,'Gadgetron']]],
  ['gadget_5fmessage_5fismrmrd_5fimage_5fcplx_5ffloat',['GADGET_MESSAGE_ISMRMRD_IMAGE_CPLX_FLOAT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaaae0cfe05124f17955350cb11549a7a63',1,'Gadgetron']]],
  ['gadget_5fmessage_5fismrmrd_5fimage_5freal_5ffloat',['GADGET_MESSAGE_ISMRMRD_IMAGE_REAL_FLOAT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa16b467b5abeaa4c493a5df096499646d',1,'Gadgetron']]],
  ['gadget_5fmessage_5fismrmrd_5fimage_5freal_5fshort',['GADGET_MESSAGE_ISMRMRD_IMAGE_REAL_SHORT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa474fd7d8ab99911002b070c0a2d1ce27',1,'Gadgetron']]],
  ['gadget_5fmessage_5fismrmrd_5fimage_5freal_5fushort',['GADGET_MESSAGE_ISMRMRD_IMAGE_REAL_USHORT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaaabf0834d7e9038d523977f413236e2bd',1,'Gadgetron']]],
  ['gadget_5fmessage_5fismrmrd_5fimagewithattrib_5fcplx_5ffloat',['GADGET_MESSAGE_ISMRMRD_IMAGEWITHATTRIB_CPLX_FLOAT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaab575c7ca62d4b61ede83028cd489d7da',1,'Gadgetron']]],
  ['gadget_5fmessage_5fismrmrd_5fimagewithattrib_5freal_5ffloat',['GADGET_MESSAGE_ISMRMRD_IMAGEWITHATTRIB_REAL_FLOAT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa7cd9efbd030a95c13a380370feb0cbb6',1,'Gadgetron']]],
  ['gadget_5fmessage_5fismrmrd_5fimagewithattrib_5freal_5fshort',['GADGET_MESSAGE_ISMRMRD_IMAGEWITHATTRIB_REAL_SHORT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa57b8dd704933a6d419ea64df29f19c42',1,'Gadgetron']]],
  ['gadget_5fmessage_5fismrmrd_5fimagewithattrib_5freal_5fushort',['GADGET_MESSAGE_ISMRMRD_IMAGEWITHATTRIB_REAL_USHORT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa39194a5184a16b850252367f3f2986bc',1,'Gadgetron']]],
  ['gadget_5fmessage_5fnew_5fmeasurement',['GADGET_MESSAGE_NEW_MEASUREMENT',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cbaa9d1c46b7d50e125d63f8affd2ea3cb9f',1,'Gadgetron']]],
  ['gadget_5fproperty',['GADGET_PROPERTY',['../class_gadgetron_1_1_gt_plus_accumulator_work_order_trigger_gadget.html#a56cab0122da1041e909e2a4b74bb784d',1,'Gadgetron::GtPlusAccumulatorWorkOrderTriggerGadget::GADGET_PROPERTY()'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#a549d8f9b659cecf9e6db6bc1fd3c65ee',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY(min_intensity_value, int,&quot;Minimal intensity value for auto image scaling&quot;, 64)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#adc5080f65f0c72c320d741636ec2916e',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY(image_series, int,&quot;Image series number&quot;, 0)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#ad993fd1d8e3889b75170898472f86611',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY(CloudComputing, bool,&quot;Whether to use cloud&quot;, false)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#a474677f4bd76b5d507d64814553eb3d2',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY(upstream_coil_compression, bool,&quot;Whether to perform upstream coil compression&quot;, false)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#a707f78ccf9d1b54d74624fb958a58f90',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY(grappa_kSize_RO, int,&quot;Grappa kernel size RO&quot;, 5)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#a0354e71cc7a126761ef03c21430055bc',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY(spirit_kSize_RO, int,&quot;Spirit kernel size RO&quot;, 7)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#affd8841f1a3d918c6d56764841271d3f',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY(retro_gated_interp_method, std::string,&quot;Interpolation method used for retro-gating&quot;,&quot;ISMRMRD_INTERP_RETRO_GATING_LINEAR&quot;)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#afddf4b20b823dad7582ad4c2bb7b50d3',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY(job_split_by_S, bool,&quot;Every S leads to a recon job&quot;, false)'],['../class_gadgetron_1_1_gt_plus_recon_job2_d_t_gadget_cloud.html#aa93f51d84eff3cc1c5100c704c375a12',1,'Gadgetron::GtPlusReconJob2DTGadgetCloud::GADGET_PROPERTY(CloudComputing, bool,&quot;Whether to use cloud&quot;, false)'],['../class_gadgetron_1_1_gt_plus_recon_job2_d_t_gadget_cloud.html#adea187e5ccff84cc61f190a6dad2c3bb',1,'Gadgetron::GtPlusReconJob2DTGadgetCloud::GADGET_PROPERTY(job_split_by_S, bool,&quot;Every S leads to a recon job&quot;, false)'],['../class_gadgetron_1_1_generic_recon_base.html#a9407554ada32606dbd6ccfccd5072359',1,'Gadgetron::GenericReconBase::GADGET_PROPERTY()'],['../class_gadgetron_1_1_generic_recon_cartesian_grappa_gadget.html#ad48e391f9f3b34a6a022f34d09251f53',1,'Gadgetron::GenericReconCartesianGrappaGadget::GADGET_PROPERTY(send_out_gfactor, bool,&quot;Whether to send out gfactor map&quot;, false)'],['../class_gadgetron_1_1_generic_recon_cartesian_grappa_gadget.html#a2ab20d56dc6d9bfb3187fdbb623c55a8',1,'Gadgetron::GenericReconCartesianGrappaGadget::GADGET_PROPERTY(grappa_kSize_RO, int,&quot;Grappa kernel size RO&quot;, 5)'],['../class_gadgetron_1_1_generic_recon_cartesian_grappa_gadget.html#aede5149b962c711d40c6ac1d5ef443b6',1,'Gadgetron::GenericReconCartesianGrappaGadget::GADGET_PROPERTY(downstream_coil_compression, bool,&quot;Whether to perform downstream coil compression&quot;, true)'],['../class_gadgetron_1_1_generic_recon_cartesian_reference_prep_gadget.html#a068e867dd1ee1b9169ba7ab78dd930ab',1,'Gadgetron::GenericReconCartesianReferencePrepGadget::GADGET_PROPERTY(average_all_ref_N, bool,&quot;Whether to average all N for ref generation&quot;, true)'],['../class_gadgetron_1_1_generic_recon_cartesian_reference_prep_gadget.html#a4db4cc2827d5732783190eb45fd3e8e1',1,'Gadgetron::GenericReconCartesianReferencePrepGadget::GADGET_PROPERTY(average_all_ref_S, bool,&quot;Whether to average all S for ref generation&quot;, false)'],['../class_gadgetron_1_1_generic_recon_cartesian_reference_prep_gadget.html#aa5301b7f8d4c2ec3f42b0e512f813abf',1,'Gadgetron::GenericReconCartesianReferencePrepGadget::GADGET_PROPERTY(prepare_ref_always, bool,&quot;Whether to prepare ref for every incoming IsmrmrdReconData&quot;, true)'],['../class_gadgetron_1_1_generic_recon_eigen_channel_gadget.html#a36069e4b705d193d57320179fecdb4cf',1,'Gadgetron::GenericReconEigenChannelGadget::GADGET_PROPERTY(average_all_ref_N, bool,&quot;Whether to average all N for ref generation&quot;, true)'],['../class_gadgetron_1_1_generic_recon_eigen_channel_gadget.html#a7b8192f1d8f633b6f92d757ec6b43abc',1,'Gadgetron::GenericReconEigenChannelGadget::GADGET_PROPERTY(average_all_ref_S, bool,&quot;Whether to average all S for ref generation&quot;, false)'],['../class_gadgetron_1_1_generic_recon_eigen_channel_gadget.html#a8d249557750cf34bdf6e47c731d75121',1,'Gadgetron::GenericReconEigenChannelGadget::GADGET_PROPERTY(update_eigen_channel_coefficients, bool,&quot;Whether to update KLT coeffients for eigen channel computation&quot;, false)'],['../class_gadgetron_1_1_generic_recon_eigen_channel_gadget.html#af717a1a794afdc28e4b8400bc91707f8',1,'Gadgetron::GenericReconEigenChannelGadget::GADGET_PROPERTY(upstream_coil_compression, bool,&quot;Whether to perform upstream coil compression&quot;, true)'],['../class_gadgetron_1_1_generic_recon_eigen_channel_gadget.html#a3c8c30ef56bff10492cb91114d81cec7',1,'Gadgetron::GenericReconEigenChannelGadget::GADGET_PROPERTY(upstream_coil_compression_thres, double,&quot;Threadhold for upstream coil compression&quot;,-1)'],['../class_gadgetron_1_1_generic_recon_gadget.html#aa92db3d775fcf65355dae3aa54aa2df4',1,'Gadgetron::GenericReconGadget::GADGET_PROPERTY()'],['../class_gadgetron_1_1_generic_recon_image_array_scaling_gadget.html#a8f618f71e72e416105e38ed74738c350',1,'Gadgetron::GenericReconImageArrayScalingGadget::GADGET_PROPERTY()'],['../class_gadgetron_1_1_generic_recon_k_space_filtering_gadget.html#a8f94b0a66bd12bc8955ecf01833d35ef',1,'Gadgetron::GenericReconKSpaceFilteringGadget::GADGET_PROPERTY()'],['../class_gadgetron_1_1_generic_recon_noise_std_map_computing_gadget.html#af290e69d309dc71431f8bc15b295ec82',1,'Gadgetron::GenericReconNoiseStdMapComputingGadget::GADGET_PROPERTY()'],['../class_gadgetron_1_1_generic_recon_partial_fourier_handling_filter_gadget.html#ab64edcfdc79f936af4f77d90088f3a65',1,'Gadgetron::GenericReconPartialFourierHandlingFilterGadget::GADGET_PROPERTY()'],['../class_gadgetron_1_1_generic_recon_partial_fourier_handling_gadget.html#a198a8da10d99f019bd6b56a2de8bba45',1,'Gadgetron::GenericReconPartialFourierHandlingGadget::GADGET_PROPERTY()'],['../class_gadgetron_1_1_generic_recon_partial_fourier_handling_p_o_c_s_gadget.html#a7074078dee1dc59b80adfab8b8337b5b',1,'Gadgetron::GenericReconPartialFourierHandlingPOCSGadget::GADGET_PROPERTY()']]],
  ['gadget_5fproperty_5flimits',['GADGET_PROPERTY_LIMITS',['../class_gadgetron_1_1_gt_plus_recon_gadget.html#a9d135db57b10cd5cb521f1b25228a57b',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY_LIMITS(filterRO, std::string,&quot;Kspace filter for RO dimension&quot;,&quot;Gaussian&quot;, GadgetPropertyLimitsEnumeration,&quot;Gaussian&quot;,&quot;Hanning&quot;,&quot;TaperedHanning&quot;,&quot;None&quot;)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#ae4d7d36108528d00ec9ec47f7424d04e',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY_LIMITS(coil_map_algorithm, std::string,&quot;Coil map estimation method&quot;,&quot;ISMRMRD_SOUHEIL&quot;, GadgetPropertyLimitsEnumeration,&quot;ISMRMRD_SOUHEIL&quot;,&quot;ISMRMRD_SOUHEIL_ITER&quot;)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#af555d7b93a588ad70bb89dc02839295d',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY_LIMITS(recon_algorithm, std::string,&quot;Reconstruction algorithm&quot;,&quot;ISMRMRD_GRAPPA&quot;, GadgetPropertyLimitsEnumeration,&quot;ISMRMRD_GRAPPA&quot;,&quot;ISMRMRD_SENSE&quot;,&quot;ISMRMRD_SPIRIT&quot;,&quot;ISMRMRD_SOFTSENSE&quot;,&quot;ISMRMRD_L1SOFTSENSE&quot;,&quot;ISMRMRD_2DTBINNING&quot;,&quot;ISMRMRD_2DTBINNING_FLOW&quot;,&quot;ISMRMRD_L1SPIRIT_SLEP&quot;,&quot;ISMRMRD_L1SPIRIT_SLEP_MOTION_COMP&quot;,&quot;ISMRMRD_NONE&quot;)'],['../class_gadgetron_1_1_gt_plus_recon_gadget.html#ae5b268180d2e4d95107355db1b97ec8f',1,'Gadgetron::GtPlusReconGadget::GADGET_PROPERTY_LIMITS(partialFourier_algo, std::string,&quot;Partial fourier handling method&quot;,&quot;ISMRMRD_PF_ZEROFILLING_FILTER&quot;, GadgetPropertyLimitsEnumeration,&quot;ISMRMRD_PF_HOMODYNE&quot;,&quot;ISMRMRD_PF_FENGHUANG&quot;,&quot;ISMRMRD_PF_POCS&quot;,&quot;ISMRMRD_PF_ZEROFILLING_FILTER&quot;,&quot;ISMRMRD_PF_ZEROFILLING&quot;,&quot;ISMRMRD_PF_NONE&quot;)'],['../class_gadgetron_1_1_gt_plus_recon_job2_d_t_gadget_cloud.html#af73cfde1ecc1854f6896e9b7d7d85a74',1,'Gadgetron::GtPlusReconJob2DTGadgetCloud::GADGET_PROPERTY_LIMITS()'],['../class_gadgetron_1_1_generic_recon_gadget.html#aceaea00916d414eaaee2ce79154fb8d1',1,'Gadgetron::GenericReconGadget::GADGET_PROPERTY_LIMITS()'],['../class_gadgetron_1_1_generic_recon_k_space_filtering_gadget.html#af3ca0ea8a5aa90411e11c488d1e40d57',1,'Gadgetron::GenericReconKSpaceFilteringGadget::GADGET_PROPERTY_LIMITS()']]],
  ['gadgetcloudcontroller',['GadgetCloudController',['../class_gadgetron_1_1_gadget_cloud_controller.html',1,'Gadgetron']]],
  ['gadgetcloudcontroller_3c_20cloudpackagetype_20_3e',['GadgetCloudController&lt; CloudPackageType &gt;',['../class_gadgetron_1_1_gadget_cloud_controller.html',1,'Gadgetron']]],
  ['gadgetcloudjobmessagereader',['GadgetCloudJobMessageReader',['../class_gadgetron_1_1_gadget_cloud_job_message_reader.html',1,'Gadgetron']]],
  ['gadgetcloudjobmessagereader_3c_20gtplusrecon2dtcloudpackagecpfl_20_3e',['GadgetCloudJobMessageReader&lt; GtPlusRecon2DTCloudPackageCPFL &gt;',['../class_gadgetron_1_1_gadget_cloud_job_message_reader.html',1,'Gadgetron']]],
  ['gadgetcloudjobmessagereader_3c_20gtplusreconjobtypecpfl_20_3e',['GadgetCloudJobMessageReader&lt; GtPlusReconJobTypeCPFL &gt;',['../class_gadgetron_1_1_gadget_cloud_job_message_reader.html',1,'Gadgetron']]],
  ['gadgetcloudjobmessagewriter',['GadgetCloudJobMessageWriter',['../class_gadgetron_1_1_gadget_cloud_job_message_writer.html',1,'Gadgetron']]],
  ['gadgetcloudjobmessagewriter_3c_20gtplusrecon2dtcloudpackagecpfl_20_3e',['GadgetCloudJobMessageWriter&lt; GtPlusRecon2DTCloudPackageCPFL &gt;',['../class_gadgetron_1_1_gadget_cloud_job_message_writer.html',1,'Gadgetron']]],
  ['gadgetcloudjobmessagewriter_3c_20gtplusreconjobtypecpfl_20_3e',['GadgetCloudJobMessageWriter&lt; GtPlusReconJobTypeCPFL &gt;',['../class_gadgetron_1_1_gadget_cloud_job_message_writer.html',1,'Gadgetron']]],
  ['gadgetcloudjobprocesshandler',['GadgetCloudJobProcessHandler',['../class_gadgetron_1_1_gadget_cloud_job_process_handler.html',1,'Gadgetron']]],
  ['gadgetcloudjobprocesshandler_3c_20cloudpackagetype_20_3e',['GadgetCloudJobProcessHandler&lt; CloudPackageType &gt;',['../class_gadgetron_1_1_gadget_cloud_job_process_handler.html',1,'Gadgetron']]],
  ['gadgetcloudjobprocesshandler_3c_20gtplusrecon2dtcloudpackage_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e_20_3e',['GadgetCloudJobProcessHandler&lt; GtPlusRecon2DTCloudPackage&lt; std::complex&lt; float &gt; &gt; &gt;',['../class_gadgetron_1_1_gadget_cloud_job_process_handler.html',1,'Gadgetron']]],
  ['gadgetcontainermessage',['GadgetContainerMessage',['../class_gadgetron_1_1_gadget_container_message.html',1,'Gadgetron']]],
  ['gadgetcontainermessage',['GadgetContainerMessage',['../class_gadgetron_1_1_gadget_container_message.html#adc5c195822ba2273cff15527aacdd0f2',1,'Gadgetron::GadgetContainerMessage']]],
  ['gadgetcontainermessage_3c_20gadgetron_3a_3ahondarray_3c_20float_20_3e_20_3e',['GadgetContainerMessage&lt; Gadgetron::hoNDArray&lt; float &gt; &gt;',['../class_gadgetron_1_1_gadget_container_message.html',1,'Gadgetron']]],
  ['gadgetcontainermessage_3c_20gadgetron_3a_3ahondarray_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e_20_3e',['GadgetContainerMessage&lt; Gadgetron::hoNDArray&lt; std::complex&lt; float &gt; &gt; &gt;',['../class_gadgetron_1_1_gadget_container_message.html',1,'Gadgetron']]],
  ['gadgetcontainermessage_3c_20ismrmrd_3a_3aacquisitionheader_20_3e',['GadgetContainerMessage&lt; ISMRMRD::AcquisitionHeader &gt;',['../class_gadgetron_1_1_gadget_container_message.html',1,'Gadgetron']]],
  ['gadgetcontainermessage_3c_20ismrmrd_3a_3aimageheader_20_3e',['GadgetContainerMessage&lt; ISMRMRD::ImageHeader &gt;',['../class_gadgetron_1_1_gadget_container_message.html',1,'Gadgetron']]],
  ['gadgetcontainermessagebase',['GadgetContainerMessageBase',['../class_gadgetron_1_1_gadget_container_message_base.html',1,'Gadgetron']]],
  ['gadgetimageattribmessagereader',['GadgetImageAttribMessageReader',['../class_gadgetron_1_1_gadget_image_attrib_message_reader.html',1,'Gadgetron']]],
  ['gadgetimagemessagereader',['GadgetImageMessageReader',['../class_gadgetron_1_1_gadget_image_message_reader.html',1,'Gadgetron']]],
  ['gadgetimagemessagewriter',['GadgetImageMessageWriter',['../class_gadgetron_1_1_gadget_image_message_writer.html',1,'Gadgetron']]],
  ['gadgetinstrumentationstreamcontroller',['GadgetInstrumentationStreamController',['../class_gadgetron_1_1_gadget_instrumentation_stream_controller.html',1,'Gadgetron']]],
  ['gadgetinstrumentationstreamcontrollerwrapper',['GadgetInstrumentationStreamControllerWrapper',['../class_gadgetron_1_1_gadget_instrumentation_stream_controller_wrapper.html',1,'Gadgetron']]],
  ['gadgetismrmrdacquisitionmessagereader',['GadgetIsmrmrdAcquisitionMessageReader',['../class_gadgetron_1_1_gadget_ismrmrd_acquisition_message_reader.html',1,'Gadgetron']]],
  ['gadgetismrmrdacquisitionmessagewriter',['GadgetIsmrmrdAcquisitionMessageWriter',['../class_gadgetron_1_1_gadget_ismrmrd_acquisition_message_writer.html',1,'Gadgetron']]],
  ['gadgetmessageconfigfilereader',['GadgetMessageConfigFileReader',['../class_gadgetron_1_1_gadget_message_config_file_reader.html',1,'Gadgetron']]],
  ['gadgetmessageconfigurationfile',['GadgetMessageConfigurationFile',['../struct_gadgetron_1_1_gadget_message_configuration_file.html',1,'Gadgetron']]],
  ['gadgetmessageconfigurationfile',['GadgetMessageConfigurationFile',['../struct_gadget_message_configuration_file.html',1,'']]],
  ['gadgetmessageid',['GadgetMessageID',['../namespace_gadgetron.html#a7a02aa8f0ebc8b923d26cde8005a7cba',1,'Gadgetron']]],
  ['gadgetmessageidentifier',['GadgetMessageIdentifier',['../struct_gadgetron_1_1_gadget_message_identifier.html',1,'Gadgetron']]],
  ['gadgetmessageidentifier',['GadgetMessageIdentifier',['../struct_gadget_message_identifier.html',1,'']]],
  ['gadgetmessagereader',['GadgetMessageReader',['../class_gadgetron_1_1_gadget_message_reader.html',1,'Gadgetron']]],
  ['gadgetmessagereadercontainer',['GadgetMessageReaderContainer',['../class_gadgetron_1_1_gadget_message_reader_container.html',1,'Gadgetron']]],
  ['gadgetmessagescript',['GadgetMessageScript',['../struct_gadgetron_1_1_gadget_message_script.html',1,'Gadgetron']]],
  ['gadgetmessagescript',['GadgetMessageScript',['../struct_gadget_message_script.html',1,'']]],
  ['gadgetmessagescriptreader',['GadgetMessageScriptReader',['../class_gadgetron_1_1_gadget_message_script_reader.html',1,'Gadgetron']]],
  ['gadgetmessagetextwriter',['GadgetMessageTextWriter',['../class_gadgetron_1_1_gadget_message_text_writer.html',1,'Gadgetron']]],
  ['gadgetmessagewriter',['GadgetMessageWriter',['../class_gadgetron_1_1_gadget_message_writer.html',1,'Gadgetron']]],
  ['gadgetmessagewritercontainer',['GadgetMessageWriterContainer',['../class_gadgetron_1_1_gadget_message_writer_container.html',1,'Gadgetron']]],
  ['gadgetproperty',['GadgetProperty',['../class_gadgetron_1_1_gadget_property.html',1,'Gadgetron']]],
  ['gadgetproperty_3c_20bool_2c_20gadgetron_3a_3agadgetpropertylimitsnolimits_3c_20bool_20_3e_20_3e',['GadgetProperty&lt; bool, Gadgetron::GadgetPropertyLimitsNoLimits&lt; bool &gt; &gt;',['../class_gadgetron_1_1_gadget_property.html',1,'Gadgetron']]],
  ['gadgetproperty_3c_20int_2c_20gadgetron_3a_3agadgetpropertylimitsnolimits_3c_20int_20_3e_20_3e',['GadgetProperty&lt; int, Gadgetron::GadgetPropertyLimitsNoLimits&lt; int &gt; &gt;',['../class_gadgetron_1_1_gadget_property.html',1,'Gadgetron']]],
  ['gadgetproperty_3c_20std_3a_3astring_2c_20gadgetron_3a_3agadgetpropertylimitsnolimits_3c_20std_3a_3astring_20_3e_20_3e',['GadgetProperty&lt; std::string, Gadgetron::GadgetPropertyLimitsNoLimits&lt; std::string &gt; &gt;',['../class_gadgetron_1_1_gadget_property.html',1,'Gadgetron']]],
  ['gadgetproperty_3c_20std_3a_3avector_3c_20t_20_3e_2c_20l_20_3e',['GadgetProperty&lt; std::vector&lt; T &gt;, L &gt;',['../class_gadgetron_1_1_gadget_property_3_01std_1_1vector_3_01_t_01_4_00_01_l_01_4.html',1,'Gadgetron']]],
  ['gadgetpropertybase',['GadgetPropertyBase',['../class_gadgetron_1_1_gadget_property_base.html',1,'Gadgetron']]],
  ['gadgetpropertylimits',['GadgetPropertyLimits',['../class_gadgetron_1_1_gadget_property_limits.html',1,'Gadgetron']]],
  ['gadgetpropertylimits_3c_20bool_20_3e',['GadgetPropertyLimits&lt; bool &gt;',['../class_gadgetron_1_1_gadget_property_limits.html',1,'Gadgetron']]],
  ['gadgetpropertylimits_3c_20int_20_3e',['GadgetPropertyLimits&lt; int &gt;',['../class_gadgetron_1_1_gadget_property_limits.html',1,'Gadgetron']]],
  ['gadgetpropertylimits_3c_20std_3a_3astring_20_3e',['GadgetPropertyLimits&lt; std::string &gt;',['../class_gadgetron_1_1_gadget_property_limits.html',1,'Gadgetron']]],
  ['gadgetpropertylimitsenumeration',['GadgetPropertyLimitsEnumeration',['../class_gadgetron_1_1_gadget_property_limits_enumeration.html',1,'Gadgetron']]],
  ['gadgetpropertylimitsnolimits',['GadgetPropertyLimitsNoLimits',['../class_gadgetron_1_1_gadget_property_limits_no_limits.html',1,'Gadgetron']]],
  ['gadgetpropertylimitsnolimits_3c_20bool_20_3e',['GadgetPropertyLimitsNoLimits&lt; bool &gt;',['../class_gadgetron_1_1_gadget_property_limits_no_limits.html',1,'Gadgetron']]],
  ['gadgetpropertylimitsnolimits_3c_20int_20_3e',['GadgetPropertyLimitsNoLimits&lt; int &gt;',['../class_gadgetron_1_1_gadget_property_limits_no_limits.html',1,'Gadgetron']]],
  ['gadgetpropertylimitsnolimits_3c_20std_3a_3astring_20_3e',['GadgetPropertyLimitsNoLimits&lt; std::string &gt;',['../class_gadgetron_1_1_gadget_property_limits_no_limits.html',1,'Gadgetron']]],
  ['gadgetpropertylimitsrange',['GadgetPropertyLimitsRange',['../class_gadgetron_1_1_gadget_property_limits_range.html',1,'Gadgetron']]],
  ['gadgetreference',['GadgetReference',['../class_gadgetron_1_1_gadget_reference.html',1,'Gadgetron']]],
  ['gadgetron',['Gadgetron',['../namespace_gadgetron.html',1,'']]],
  ['gadgetron_5fdata_5frole',['GADGETRON_DATA_ROLE',['../mri__core__def_8h.html#a52501e35e67b0468566239cc507a1524',1,'mri_core_def.h']]],
  ['gadgetron_5fimage_5frecon_5ffigure',['GADGETRON_IMAGE_RECON_FIGURE',['../mri__core__def_8h.html#a104c52ea0ec05928e3d122817778b91b',1,'mri_core_def.h']]],
  ['gadgetron_5fimage_5fsurfacecoilcorrection',['GADGETRON_IMAGE_SURFACECOILCORRECTION',['../mri__core__def_8h.html#a7d9761b486c1fce3431f36c2e459fb99',1,'mri_core_def.h']]],
  ['gadgetron_5fimagenumber',['GADGETRON_IMAGENUMBER',['../mri__core__def_8h.html#a4ce62ae0ae5896783258de6e4f782a8a',1,'mri_core_def.h']]],
  ['gadgetron_5flog_5flevel_5fdebug',['GADGETRON_LOG_LEVEL_DEBUG',['../namespace_gadgetron.html#ab02a3b793f740d45b820e95e5e1cb1d7a6bf6ee31d8c1ccd65414b18b3de68254',1,'Gadgetron']]],
  ['gadgetron_5flog_5flevel_5ferror',['GADGETRON_LOG_LEVEL_ERROR',['../namespace_gadgetron.html#ab02a3b793f740d45b820e95e5e1cb1d7ad88e0564dd6a7f2584c44c5a763541f5',1,'Gadgetron']]],
  ['gadgetron_5flog_5flevel_5finfo',['GADGETRON_LOG_LEVEL_INFO',['../namespace_gadgetron.html#ab02a3b793f740d45b820e95e5e1cb1d7a9ccaec700800cf5a0a1010a2e6394825',1,'Gadgetron']]],
  ['gadgetron_5flog_5flevel_5fmax',['GADGETRON_LOG_LEVEL_MAX',['../namespace_gadgetron.html#ab02a3b793f740d45b820e95e5e1cb1d7a658469c793fc5e9480cb987190e50844',1,'Gadgetron']]],
  ['gadgetron_5flog_5flevel_5fverbose',['GADGETRON_LOG_LEVEL_VERBOSE',['../namespace_gadgetron.html#ab02a3b793f740d45b820e95e5e1cb1d7adb2f76ea7ff48c037a163387fc4b99ea',1,'Gadgetron']]],
  ['gadgetron_5flog_5flevel_5fwarning',['GADGETRON_LOG_LEVEL_WARNING',['../namespace_gadgetron.html#ab02a3b793f740d45b820e95e5e1cb1d7a8a04e04f430297c2488b0831354c5f7a',1,'Gadgetron']]],
  ['gadgetron_5flog_5fprint_5fdatetime',['GADGETRON_LOG_PRINT_DATETIME',['../namespace_gadgetron.html#a98e7db4ccd54586519599e392ae1349ea10b0f2f1feb7181ad1fb977ad6ffd2e3',1,'Gadgetron']]],
  ['gadgetron_5flog_5fprint_5ffileloc',['GADGETRON_LOG_PRINT_FILELOC',['../namespace_gadgetron.html#a98e7db4ccd54586519599e392ae1349ea5e11571836f900c60e2c49c5afe033d9',1,'Gadgetron']]],
  ['gadgetron_5flog_5fprint_5ffolder',['GADGETRON_LOG_PRINT_FOLDER',['../namespace_gadgetron.html#a98e7db4ccd54586519599e392ae1349ea00bd0b3b2df5463a83bcbd534807bec7',1,'Gadgetron']]],
  ['gadgetron_5flog_5fprint_5flevel',['GADGETRON_LOG_PRINT_LEVEL',['../namespace_gadgetron.html#a98e7db4ccd54586519599e392ae1349eac5c7db6c2c4ae25d7fbb0bffc4257957',1,'Gadgetron']]],
  ['gadgetron_5flog_5fprint_5fmax',['GADGETRON_LOG_PRINT_MAX',['../namespace_gadgetron.html#a98e7db4ccd54586519599e392ae1349ea347701b41d0ea921ad32f52ac031a3c8',1,'Gadgetron']]],
  ['gadgetron_5fpass_5fimmediate',['GADGETRON_PASS_IMMEDIATE',['../gt_plus_i_s_m_r_m_r_d_recon_util_8h.html#a9ad0a7c14b938f2c231a5d34665e40e8',1,'gtPlusISMRMRDReconUtil.h']]],
  ['gadgetron_5fplplot_5fexport_2eh',['gadgetron_plplot_export.h',['../gadgetron__plplot__export_8h.html',1,'']]],
  ['gadgetron_5fro',['GADGETRON_RO',['../gt_plus_i_s_m_r_m_r_d_recon_util_8h.html#aff172e2cde05cacfd221479356cdcd10',1,'gtPlusISMRMRDReconUtil.h']]],
  ['gadgetron_5fskip_5fprocessing_5fafter_5frecon',['GADGETRON_SKIP_PROCESSING_AFTER_RECON',['../mri__core__def_8h.html#a05b633840346be909f1bfdbcf504ecd2',1,'mri_core_def.h']]],
  ['gadgetronclientanalyzeimagemessagereader',['GadgetronClientAnalyzeImageMessageReader',['../class_gadgetron_client_analyze_image_message_reader.html',1,'']]],
  ['gadgetronclientblobmessagereader',['GadgetronClientBlobMessageReader',['../class_gadgetron_client_blob_message_reader.html',1,'']]],
  ['gadgetronclientconnector',['GadgetronClientConnector',['../class_gadgetron_client_connector.html',1,'']]],
  ['gadgetronclientdependencyqueryreader',['GadgetronClientDependencyQueryReader',['../class_gadgetron_client_dependency_query_reader.html',1,'']]],
  ['gadgetronclientexception',['GadgetronClientException',['../class_gadgetron_client_exception.html',1,'']]],
  ['gadgetronclientimagemessagereader',['GadgetronClientImageMessageReader',['../class_gadgetron_client_image_message_reader.html',1,'']]],
  ['gadgetronclientmessagereader',['GadgetronClientMessageReader',['../class_gadgetron_client_message_reader.html',1,'']]],
  ['gadgetronclienttextreader',['GadgetronClientTextReader',['../class_gadgetron_client_text_reader.html',1,'']]],
  ['gadgetroncloudconnector',['GadgetronCloudConnector',['../class_gadgetron_1_1_gadgetron_cloud_connector.html',1,'Gadgetron']]],
  ['gadgetronconfiguration',['GadgetronConfiguration',['../struct_gadgetron_x_m_l_1_1_gadgetron_configuration.html',1,'GadgetronXML']]],
  ['gadgetronconnector',['GadgetronConnector',['../class_gadgetron_1_1_gadgetron_connector.html',1,'Gadgetron']]],
  ['gadgetronexception_2eh',['GadgetronException.h',['../_gadgetron_exception_8h.html',1,'']]],
  ['gadgetroninfogadget',['GadgetronInfoGadget',['../class_gadgetron_1_1_gadgetron_info_gadget.html',1,'Gadgetron']]],
  ['gadgetronlogger',['GadgetronLogger',['../class_gadgetron_1_1_gadgetron_logger.html',1,'Gadgetron']]],
  ['gadgetronloglevel',['GadgetronLogLevel',['../namespace_gadgetron.html#ab02a3b793f740d45b820e95e5e1cb1d7',1,'Gadgetron']]],
  ['gadgetronlogoutput',['GadgetronLogOutput',['../namespace_gadgetron.html#a98e7db4ccd54586519599e392ae1349e',1,'Gadgetron']]],
  ['gadgetronlogresource',['GadgetronLogResource',['../classgadgetron__web__app_1_1_gadgetron_log_resource.html',1,'gadgetron_web_app']]],
  ['gadgetronmath_2eh',['gadgetronmath.h',['../gadgetronmath_8h.html',1,'']]],
  ['gadgetronnodeinfo',['GadgetronNodeInfo',['../struct_gadgetron_1_1_gadgetron_node_info.html',1,'Gadgetron']]],
  ['gadgetronparameter',['GadgetronParameter',['../struct_gadgetron_x_m_l_1_1_gadgetron_parameter.html',1,'GadgetronXML']]],
  ['gadgetronresource',['GadgetronResource',['../classgadgetron__web__app_1_1_gadgetron_resource.html',1,'gadgetron_web_app']]],
  ['gadgetronslotcontainer',['GadgetronSlotContainer',['../class_gadgetron_slot_container.html',1,'']]],
  ['gadgetronslotcontainer_3c_20gadgetron_3a_3agadgetmessagereader_20_3e',['GadgetronSlotContainer&lt; Gadgetron::GadgetMessageReader &gt;',['../class_gadgetron_slot_container.html',1,'']]],
  ['gadgetronslotcontainer_3c_20gadgetron_3a_3agadgetmessagewriter_20_3e',['GadgetronSlotContainer&lt; Gadgetron::GadgetMessageWriter &gt;',['../class_gadgetron_slot_container.html',1,'']]],
  ['gadgetrontimer',['GadgetronTimer',['../class_gadgetron_1_1_gadgetron_timer.html',1,'Gadgetron']]],
  ['gadgetrontimer_2eh',['GadgetronTimer.h',['../_gadgetron_timer_8h.html',1,'']]],
  ['gadgetserveracceptor',['GadgetServerAcceptor',['../class_gadgetron_1_1_gadget_server_acceptor.html',1,'Gadgetron']]],
  ['gadgetstreamconfiguration',['GadgetStreamConfiguration',['../struct_gadgetron_x_m_l_1_1_gadget_stream_configuration.html',1,'GadgetronXML']]],
  ['gadgetstreamcontroller',['GadgetStreamController',['../class_gadgetron_1_1_gadget_stream_controller.html',1,'Gadgetron']]],
  ['gadgetstreaminterface',['GadgetStreamInterface',['../class_gadgetron_1_1_gadget_stream_interface.html',1,'Gadgetron']]],
  ['gadgettools_5fexport_2eh',['gadgettools_export.h',['../gadgettools__export_8h.html',1,'']]],
  ['gaussiankernel',['gaussianKernel',['../namespace_gadgetron.html#ac33ba9f28fd04419f27a6a7ae5307b87',1,'Gadgetron']]],
  ['gemm',['gemm',['../namespace_gadgetron.html#a320490a5f9910cd1d6ddc476d204bf96',1,'Gadgetron::gemm(hoNDArray&lt; std::complex&lt; float &gt; &gt; &amp;C, const hoNDArray&lt; std::complex&lt; float &gt; &gt; &amp;A, const hoNDArray&lt; std::complex&lt; float &gt; &gt; &amp;B)'],['../namespace_gadgetron.html#a4b131616eca0d8850a616afc0cdbc565',1,'Gadgetron::gemm(hoNDArray&lt; T &gt; &amp;C, const hoNDArray&lt; T &gt; &amp;A, bool transA, const hoNDArray&lt; T &gt; &amp;B, bool transB)']]],
  ['gen_5fseq',['gen_seq',['../structcrow_1_1black__magic_1_1gen__seq.html',1,'crow::black_magic']]],
  ['gen_5fseq_3c_200_20_3e',['gen_seq&lt; 0 &gt;',['../structcrow_1_1black__magic_1_1gen__seq_3_010_01_4.html',1,'crow::black_magic']]],
  ['gen_5fseq_3c_201_20_3e',['gen_seq&lt; 1 &gt;',['../structcrow_1_1black__magic_1_1gen__seq_3_011_01_4.html',1,'crow::black_magic']]],
  ['generaloperator',['generalOperator',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_2eh',['generalOperator.h',['../general_operator_8h.html',1,'']]],
  ['generaloperator_3c_20array_5ftype_20_3e',['generalOperator&lt; ARRAY_TYPE &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20array_5ftype_5felement_20_3e',['generalOperator&lt; ARRAY_TYPE_ELEMENT &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20array_5ftype_5foperator_20_3e',['generalOperator&lt; ARRAY_TYPE_OPERATOR &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20complex_5farray_5ftype_20_3e',['generalOperator&lt; COMPLEX_ARRAY_TYPE &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20cundarray_3c_20complext_3c_20real_20_3e_20_3e_20_3e',['generalOperator&lt; cuNDArray&lt; complext&lt; REAL &gt; &gt; &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20cundarray_3c_20complext_3c_20t_20_3e_20_3e_20_3e',['generalOperator&lt; cuNDArray&lt; complext&lt; T &gt; &gt; &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20cundarray_3c_20float_5fcomplext_20_3e_20_3e',['generalOperator&lt; cuNDArray&lt; float_complext &gt; &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20cundarray_3c_20t_20_3e_20_3e',['generalOperator&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20hocundarray_3c_20float_20_3e_20_3e',['generalOperator&lt; hoCuNDArray&lt; float &gt; &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20hocundarray_3c_20t_20_3e_20_3e',['generalOperator&lt; hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20hondarray_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e_20_3e',['generalOperator&lt; hoNDArray&lt; std::complex&lt; T &gt; &gt; &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20hondarray_3c_20t_20_3e_20_3e',['generalOperator&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generaloperator_3c_20real_20_3e',['generalOperator&lt; REAL &gt;',['../class_gadgetron_1_1general_operator.html',1,'Gadgetron']]],
  ['generate_5fasymmetric_5ffilter',['generate_asymmetric_filter',['../namespace_gadgetron.html#a016984c874deb1be3b9c77ec1eed6848',1,'Gadgetron']]],
  ['generate_5fsymmetric_5ffilter',['generate_symmetric_filter',['../namespace_gadgetron.html#a6f8e10b94fd61a735ee41501168657cb',1,'Gadgetron']]],
  ['generate_5fsymmetric_5ffilter_5fref',['generate_symmetric_filter_ref',['../namespace_gadgetron.html#a9afc7d3fd3f36ae01ec18c4787a38e39',1,'Gadgetron']]],
  ['genericreconbase',['GenericReconBase',['../class_gadgetron_1_1_generic_recon_base.html',1,'Gadgetron']]],
  ['genericreconbase_2eh',['GenericReconBase.h',['../_generic_recon_base_8h.html',1,'']]],
  ['genericreconbase_3c_20ismrmrdimagearray_20_3e',['GenericReconBase&lt; IsmrmrdImageArray &gt;',['../class_gadgetron_1_1_generic_recon_base.html',1,'Gadgetron']]],
  ['genericreconbase_3c_20ismrmrdrecondata_20_3e',['GenericReconBase&lt; IsmrmrdReconData &gt;',['../class_gadgetron_1_1_generic_recon_base.html',1,'Gadgetron']]],
  ['genericreconcartesiangrappagadget',['GenericReconCartesianGrappaGadget',['../class_gadgetron_1_1_generic_recon_cartesian_grappa_gadget.html',1,'Gadgetron']]],
  ['genericreconcartesiangrappagadget_2eh',['GenericReconCartesianGrappaGadget.h',['../_generic_recon_cartesian_grappa_gadget_8h.html',1,'']]],
  ['genericreconcartesiangrappaobj',['GenericReconCartesianGrappaObj',['../class_gadgetron_1_1_generic_recon_cartesian_grappa_obj.html',1,'Gadgetron']]],
  ['genericreconcartesianreferenceprepgadget',['GenericReconCartesianReferencePrepGadget',['../class_gadgetron_1_1_generic_recon_cartesian_reference_prep_gadget.html',1,'Gadgetron']]],
  ['genericreconcartesianreferenceprepgadget_2eh',['GenericReconCartesianReferencePrepGadget.h',['../_generic_recon_cartesian_reference_prep_gadget_8h.html',1,'']]],
  ['genericrecondatabase',['GenericReconDataBase',['../class_gadgetron_1_1_generic_recon_data_base.html',1,'Gadgetron']]],
  ['genericreconeigenchannelgadget',['GenericReconEigenChannelGadget',['../class_gadgetron_1_1_generic_recon_eigen_channel_gadget.html',1,'Gadgetron']]],
  ['genericreconeigenchannelgadget_2eh',['GenericReconEigenChannelGadget.h',['../_generic_recon_eigen_channel_gadget_8h.html',1,'']]],
  ['genericreconfieldofviewadjustmentgadget',['GenericReconFieldOfViewAdjustmentGadget',['../class_gadgetron_1_1_generic_recon_field_of_view_adjustment_gadget.html',1,'Gadgetron']]],
  ['genericreconfieldofviewadjustmentgadget_2eh',['GenericReconFieldOfViewAdjustmentGadget.h',['../_generic_recon_field_of_view_adjustment_gadget_8h.html',1,'']]],
  ['genericrecongadget',['GenericReconGadget',['../class_gadgetron_1_1_generic_recon_gadget.html',1,'Gadgetron']]],
  ['genericrecongadget_2eh',['GenericReconGadget.h',['../_generic_recon_gadget_8h.html',1,'']]],
  ['genericreconimagearrayscalinggadget',['GenericReconImageArrayScalingGadget',['../class_gadgetron_1_1_generic_recon_image_array_scaling_gadget.html',1,'Gadgetron']]],
  ['genericreconimagebase',['GenericReconImageBase',['../class_gadgetron_1_1_generic_recon_image_base.html',1,'Gadgetron']]],
  ['genericreconjob',['GenericReconJob',['../class_gadgetron_1_1_generic_recon_job.html',1,'Gadgetron']]],
  ['genericreconkspacefilteringgadget',['GenericReconKSpaceFilteringGadget',['../class_gadgetron_1_1_generic_recon_k_space_filtering_gadget.html',1,'Gadgetron']]],
  ['genericreconkspacefilteringgadget_2eh',['GenericReconKSpaceFilteringGadget.h',['../_generic_recon_k_space_filtering_gadget_8h.html',1,'']]],
  ['genericreconnoisestdmapcomputinggadget',['GenericReconNoiseStdMapComputingGadget',['../class_gadgetron_1_1_generic_recon_noise_std_map_computing_gadget.html',1,'Gadgetron']]],
  ['genericreconnoisestdmapcomputinggadget_2eh',['GenericReconNoiseStdMapComputingGadget.h',['../_generic_recon_noise_std_map_computing_gadget_8h.html',1,'']]],
  ['genericreconpartialfourierhandlingfiltergadget',['GenericReconPartialFourierHandlingFilterGadget',['../class_gadgetron_1_1_generic_recon_partial_fourier_handling_filter_gadget.html',1,'Gadgetron']]],
  ['genericreconpartialfourierhandlingfiltergadget_2eh',['GenericReconPartialFourierHandlingFilterGadget.h',['../_generic_recon_partial_fourier_handling_filter_gadget_8h.html',1,'']]],
  ['genericreconpartialfourierhandlinggadget',['GenericReconPartialFourierHandlingGadget',['../class_gadgetron_1_1_generic_recon_partial_fourier_handling_gadget.html',1,'Gadgetron']]],
  ['genericreconpartialfourierhandlinggadget_2eh',['GenericReconPartialFourierHandlingGadget.h',['../_generic_recon_partial_fourier_handling_gadget_8h.html',1,'']]],
  ['genericreconpartialfourierhandlingpocsgadget',['GenericReconPartialFourierHandlingPOCSGadget',['../class_gadgetron_1_1_generic_recon_partial_fourier_handling_p_o_c_s_gadget.html',1,'Gadgetron']]],
  ['genericreconpartialfourierhandlingpocsgadget_2eh',['GenericReconPartialFourierHandlingPOCSGadget.h',['../_generic_recon_partial_fourier_handling_p_o_c_s_gadget_8h.html',1,'']]],
  ['gens',['gens',['../struct_gadgetron_1_1gens.html',1,'Gadgetron']]],
  ['gens_3c_200_2c_20s_2e_2e_2e_3e',['gens&lt; 0, S...&gt;',['../struct_gadgetron_1_1gens_3_010_00_01_s_8_8_8_4.html',1,'Gadgetron']]],
  ['gesv',['gesv',['../namespace_gadgetron.html#a3ddf424d272112c172ef5825853445be',1,'Gadgetron']]],
  ['get',['get',['../structcrow_1_1detail_1_1check__before__handle__arity__3__const_1_1get.html',1,'crow::detail::check_before_handle_arity_3_const']]],
  ['get',['get',['../structcrow_1_1detail_1_1check__before__handle__arity__3_1_1get.html',1,'crow::detail::check_before_handle_arity_3']]],
  ['get',['get',['../structcrow_1_1detail_1_1check__after__handle__arity__3__const_1_1get.html',1,'crow::detail::check_after_handle_arity_3_const']]],
  ['get',['get',['../class_gadgetron_1_1ho_n_d_image_container2_d.html#a914032cca69afc4bc7ba4dc0c7c8282d',1,'Gadgetron::hoNDImageContainer2D::get(size_t row, size_t col)'],['../class_gadgetron_1_1ho_n_d_image_container2_d.html#a873d8b52081740893401d2783b885d5f',1,'Gadgetron::hoNDImageContainer2D::get(std::vector&lt; ImageType * &gt; &amp;im_array, size_t row) const '],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html#a09dd301e9266d2bc86461e1fb5209b9e',1,'Gadgetron::gtPlus::gtplusBSplineFFD::get()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#aed5abbb2a8544dfe559292eb5c66115c',1,'Gadgetron::gtPlus::gtplusFFDBase::get()']]],
  ['get',['get',['../structcrow_1_1detail_1_1check__after__handle__arity__3_1_1get.html',1,'crow::detail::check_after_handle_arity_3']]],
  ['get_5fall_5fimages',['get_all_images',['../class_gadgetron_1_1ho_n_d_image_container2_d.html#a769ad43bfbad70009fad76cb5bcb852b',1,'Gadgetron::hoNDImageContainer2D']]],
  ['get_5faxis',['get_axis',['../class_gadgetron_1_1ho_n_d_image.html#a485e9b0e5bac6dc4d742b3ab5e8db619',1,'Gadgetron::hoNDImage']]],
  ['get_5fctrl_5fpt',['get_ctrl_pt',['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#af9280b871da99e14213b811ee9ee366f',1,'Gadgetron::gtPlus::gtplusFFDBase']]],
  ['get_5fdevice',['get_device',['../class_gadgetron_1_1cu_n_f_f_t__plan.html#af0b82603c588e3123b588a1341cece81',1,'Gadgetron::cuNFFT_plan']]],
  ['get_5fdomain_5fdimensions',['get_domain_dimensions',['../class_gadgetron_1_1encoding_operator_container.html#ad0a722190ce0e86f34106bcba83aeaf7',1,'Gadgetron::encodingOperatorContainer::get_domain_dimensions()'],['../class_gadgetron_1_1general_operator.html#a350f59e594ba0e5bb1f72e0ede18b010',1,'Gadgetron::generalOperator::get_domain_dimensions()'],['../class_gadgetron_1_1ho_cu_operator.html#a45c4660cc8689dd0572990bed8dc0a54',1,'Gadgetron::hoCuOperator::get_domain_dimensions()'],['../class_gadgetron_1_1multiplication_operator_container.html#a5d7f865ab5d0cc9e2177e56d3b672f7d',1,'Gadgetron::multiplicationOperatorContainer::get_domain_dimensions()']]],
  ['get_5fimage_5forientation',['get_image_orientation',['../class_gadgetron_1_1ho_n_d_image.html#ad1b19f5715f0e968a454d1595debc62e',1,'Gadgetron::hoNDImage::get_image_orientation(unsigned int d, coord_type ori[3]) const '],['../class_gadgetron_1_1ho_n_d_image.html#aaed5a5b16a03d8be95db3f2a5fe1ca6a',1,'Gadgetron::hoNDImage::get_image_orientation(unsigned int d, unsigned int ind, coord_type &amp;ori) const '],['../class_gadgetron_1_1ho_n_d_image.html#a8d15b25ea75a381fa13d0d33a79fa16d',1,'Gadgetron::hoNDImage::get_image_orientation(coord_type quat[4]) const ']]],
  ['get_5fimage_5fposition',['get_image_position',['../class_gadgetron_1_1ho_n_d_image.html#aee841fbf7d2a1a38c5a3c0dda38f679d',1,'Gadgetron::hoNDImage']]],
  ['get_5findex_5fof_5felement_5ffrom_5ftuple_5fby_5ftype_5fimpl',['get_index_of_element_from_tuple_by_type_impl',['../structcrow_1_1detail_1_1get__index__of__element__from__tuple__by__type__impl.html',1,'crow::detail']]],
  ['get_5findex_5fof_5felement_5ffrom_5ftuple_5fby_5ftype_5fimpl_3c_20t_2c_20n_2c_20t_2c_20args_2e_2e_2e_3e',['get_index_of_element_from_tuple_by_type_impl&lt; T, N, T, Args...&gt;',['../structcrow_1_1detail_1_1get__index__of__element__from__tuple__by__type__impl_3_01_t_00_01_n_00_01_t_00_01_args_8_8_8_4.html',1,'crow::detail']]],
  ['get_5findex_5fof_5felement_5ffrom_5ftuple_5fby_5ftype_5fimpl_3c_20t_2c_20n_2c_20u_2c_20args_2e_2e_2e_3e',['get_index_of_element_from_tuple_by_type_impl&lt; T, N, U, Args...&gt;',['../structcrow_1_1detail_1_1get__index__of__element__from__tuple__by__type__impl_3_01_t_00_01_n_00_01_u_00_01_args_8_8_8_4.html',1,'crow::detail']]],
  ['get_5flocation',['get_location',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html#aea760864671d17a05b299accff7d3919',1,'Gadgetron::gtPlus::gtplusBSplineFFD::get_location()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#a0e33c9dc0e2ccbae5707374b45762bd6',1,'Gadgetron::gtPlus::gtplusFFDBase::get_location()']]],
  ['get_5fmatrix_5fsize',['get_matrix_size',['../class_gadgetron_1_1cu_n_f_f_t__plan.html#a2117c4abc456795b3c2c1ef1645f1872',1,'Gadgetron::cuNFFT_plan']]],
  ['get_5fmatrix_5fsize_5fos',['get_matrix_size_os',['../class_gadgetron_1_1cu_n_f_f_t__plan.html#ad56ce5a2c0ce97e4afba8054ca0c3475',1,'Gadgetron::cuNFFT_plan']]],
  ['get_5fnumber_5fof_5fall_5fimages',['get_number_of_all_images',['../class_gadgetron_1_1ho_n_d_image_container2_d.html#ab60846d9709e01b31316ecb87d45f546',1,'Gadgetron::hoNDImageContainer2D']]],
  ['get_5fnumpy_5ftype',['get_numpy_type',['../namespace_gadgetron.html#af5048ce8f633cd5e5b468fa870965e4c',1,'Gadgetron']]],
  ['get_5forigin',['get_origin',['../class_gadgetron_1_1ho_n_d_image.html#a9503d66998090801785b934f857a6408',1,'Gadgetron::hoNDImage']]],
  ['get_5fpixel_5fsize',['get_pixel_size',['../class_gadgetron_1_1ho_n_d_image.html#a45598efc1f2a3d8194ef2a8385ab48f4',1,'Gadgetron::hoNDImage']]],
  ['get_5fsize',['get_size',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html#a60c44c61fabe6b1b9f4f500075ea4d9a',1,'Gadgetron::gtPlus::gtplusBSplineFFD::get_size()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#ab27474d6de6cc89957cbb84172e80d91',1,'Gadgetron::gtPlus::gtplusFFDBase::get_size()']]],
  ['get_5fspacing',['get_spacing',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html#a6a26ae6f5748a4342d009c327abe07c6',1,'Gadgetron::gtPlus::gtplusBSplineFFD::get_spacing()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#a4bf0bac9bbf432b318d7ae5bc220c3bf',1,'Gadgetron::gtPlus::gtplusFFDBase::get_spacing()']]],
  ['get_5fsub_5fimage',['get_sub_image',['../class_gadgetron_1_1ho_n_d_image.html#a292ad4f3108cc98cca8f5bb3da4de8bd',1,'Gadgetron::hoNDImage']]],
  ['get_5fw',['get_W',['../class_gadgetron_1_1cu_n_f_f_t__plan.html#a7b672d5493dccfecaf120eb71d116114',1,'Gadgetron::cuNFFT_plan']]],
  ['get_5fweight',['get_weight',['../class_gadgetron_1_1general_operator.html#a643a2936bfec1a399e24e8a7be314057',1,'Gadgetron::generalOperator::get_weight()'],['../class_gadgetron_1_1ho_cu_operator.html#a796e8436dd0c7782a89c4f4823e9f336',1,'Gadgetron::hoCuOperator::get_weight()'],['../class_gadgetron_1_1tv_pics_operator.html#aa2ec9aa8126421b9a1576cd6e2cf678d',1,'Gadgetron::tvPicsOperator::get_weight()']]],
  ['getdeformationfield',['getDeformationField',['../class_gadgetron_1_1ho_image_reg_deformation_field.html#a051822ca4960353cad947f1488ebe43c',1,'Gadgetron::hoImageRegDeformationField']]],
  ['getffdarray',['getFFDArray',['../class_gadgetron_1_1gt_plus_1_1gtplus_m_l_f_f_d.html#a21a2089b7ac2037fe4ff1ffa3bedbdb7',1,'Gadgetron::gtPlus::gtplusMLFFD']]],
  ['getrf',['getrf',['../namespace_gadgetron.html#a3c88679e36cae81ae717fa359690a686',1,'Gadgetron']]],
  ['getri',['getri',['../namespace_gadgetron.html#aac3cd2892ea1bbd017ad8165d0df6a21',1,'Gadgetron']]],
  ['gfactor_5f',['gfactor_',['../class_gadgetron_1_1_generic_recon_cartesian_grappa_obj.html#a8a94845f34c5d4e97b5acaf79b1ffe9b',1,'Gadgetron::GenericReconCartesianGrappaObj']]],
  ['gillock',['GILLock',['../class_gadgetron_1_1_g_i_l_lock.html',1,'Gadgetron']]],
  ['glreconwidget',['GLReconWidget',['../class_g_l_recon_widget.html',1,'']]],
  ['gpbbsolver',['gpBbSolver',['../class_gadgetron_1_1gp_bb_solver.html',1,'Gadgetron']]],
  ['gpbbsolver_3c_20cundarray_3c_20t_20_3e_20_3e',['gpBbSolver&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1gp_bb_solver.html',1,'Gadgetron']]],
  ['gpbbsolver_3c_20hocundarray_3c_20t_20_3e_20_3e',['gpBbSolver&lt; hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1gp_bb_solver.html',1,'Gadgetron']]],
  ['gpbbsolver_3c_20hondarray_3c_20t_20_3e_20_3e',['gpBbSolver&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1gp_bb_solver.html',1,'Gadgetron']]],
  ['gpregularizationoperator',['gpRegularizationOperator',['../class_gadgetron_1_1gp_solver_1_1gp_regularization_operator.html',1,'Gadgetron::gpSolver']]],
  ['gpsolver',['gpSolver',['../class_gadgetron_1_1gp_solver.html',1,'Gadgetron']]],
  ['gpsolver_3c_20cundarray_3c_20gadgetron_3a_3acomplext_20_3e_20_3e',['gpSolver&lt; cuNDArray&lt; Gadgetron::complext &gt; &gt;',['../class_gadgetron_1_1gp_solver.html',1,'Gadgetron']]],
  ['gpsolver_3c_20cundarray_3c_20t_20_3e_20_3e',['gpSolver&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1gp_solver.html',1,'Gadgetron']]],
  ['gpsolver_3c_20hocundarray_3c_20t_20_3e_20_3e',['gpSolver&lt; hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1gp_solver.html',1,'Gadgetron']]],
  ['gpsolver_3c_20hondarray_3c_20t_20_3e_20_3e',['gpSolver&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1gp_solver.html',1,'Gadgetron']]],
  ['gpubuffersenseprepgadget',['gpuBufferSensePrepGadget',['../class_gadgetron_1_1gpu_buffer_sense_prep_gadget.html',1,'Gadgetron']]],
  ['gpucgktsensegadget',['gpuCgKtSenseGadget',['../class_gadgetron_1_1gpu_cg_kt_sense_gadget.html',1,'Gadgetron']]],
  ['gpucgsensegadget',['gpuCgSenseGadget',['../class_gadgetron_1_1gpu_cg_sense_gadget.html',1,'Gadgetron']]],
  ['gpucgspiritgadget',['gpuCgSpiritGadget',['../class_gadgetron_1_1gpu_cg_spirit_gadget.html',1,'Gadgetron']]],
  ['gpucore_5fexport_2eh',['gpucore_export.h',['../gpucore__export_8h.html',1,'']]],
  ['gpucsicoilestimationgadget',['gpuCSICoilEstimationGadget',['../class_gadgetron_1_1gpu_c_s_i_coil_estimation_gadget.html',1,'Gadgetron']]],
  ['gpufft_5fexport_2eh',['gpufft_export.h',['../gpufft__export_8h.html',1,'']]],
  ['gpugenericsenseprepgadget',['gpuGenericSensePrepGadget',['../class_gadgetron_1_1gpu_generic_sense_prep_gadget.html',1,'Gadgetron']]],
  ['gpulalmsensegadget',['gpuLALMSenseGadget',['../class_gadgetron_1_1gpu_l_a_l_m_sense_gadget.html',1,'Gadgetron']]],
  ['gpunfft_5fexport_2eh',['gpunfft_export.h',['../gpunfft__export_8h.html',1,'']]],
  ['gpunlcgsensegadget',['gpuNlcgSenseGadget',['../class_gadgetron_1_1gpu_nlcg_sense_gadget.html',1,'Gadgetron']]],
  ['gpuoperators_5fexport_2eh',['gpuoperators_export.h',['../gpuoperators__export_8h.html',1,'']]],
  ['gpuossensegadget',['gpuOsSenseGadget',['../class_gadgetron_1_1gpu_os_sense_gadget.html',1,'Gadgetron']]],
  ['gpupmri_5fexport_2eh',['gpupmri_export.h',['../gpupmri__export_8h.html',1,'']]],
  ['gpuradialprepgadget',['gpuRadialPrepGadget',['../class_gadgetron_1_1gpu_radial_prep_gadget.html',1,'Gadgetron']]],
  ['gpuradialsenseprepgadget',['gpuRadialSensePrepGadget',['../class_gadgetron_1_1gpu_radial_sense_prep_gadget.html',1,'Gadgetron']]],
  ['gpuradialspiritprepgadget',['gpuRadialSpiritPrepGadget',['../class_gadgetron_1_1gpu_radial_spirit_prep_gadget.html',1,'Gadgetron']]],
  ['gpuregistrationaveraginggadget2d',['gpuRegistrationAveragingGadget2D',['../class_gadgetron_1_1gpu_registration_averaging_gadget2_d.html',1,'Gadgetron']]],
  ['gpuregistrationscatteringgadget2d',['gpuRegistrationScatteringGadget2D',['../class_gadgetron_1_1gpu_registration_scattering_gadget2_d.html',1,'Gadgetron']]],
  ['gpuretrogatedsenseprepgadget',['gpuRetroGatedSensePrepGadget',['../class_gadgetron_1_1gpu_retro_gated_sense_prep_gadget.html',1,'Gadgetron']]],
  ['gpusbsensegadget',['gpuSbSenseGadget',['../class_gadgetron_1_1gpu_sb_sense_gadget.html',1,'Gadgetron']]],
  ['gpusensegadget',['gpuSenseGadget',['../class_gadgetron_1_1gpu_sense_gadget.html',1,'Gadgetron']]],
  ['gpusolvers_5fexport_2eh',['gpusolvers_export.h',['../gpusolvers__export_8h.html',1,'']]],
  ['gpuspiralsenseprepgadget',['gpuSpiralSensePrepGadget',['../class_gadgetron_1_1gpu_spiral_sense_prep_gadget.html',1,'Gadgetron']]],
  ['gputimer',['GPUTimer',['../class_gadgetron_1_1_g_p_u_timer.html',1,'Gadgetron']]],
  ['gpuxray_5fexport_2eh',['gpuxray_export.h',['../gpuxray__export_8h.html',1,'']]],
  ['gradient',['gradient',['../class_gadgetron_1_1ho_motion_compensation2_d_t_operator.html#a77d7f76691fc3d21b6f932799e075f69',1,'Gadgetron::hoMotionCompensation2DTOperator::gradient()'],['../class_gadgetron_1_1ho_redundant_wavelet_operator.html#a227ea2680280993bf4bc6fa474824550',1,'Gadgetron::hoRedundantWaveletOperator::gradient()'],['../class_gadgetron_1_1ho_s_p_i_r_i_t2_d_t_operator.html#a4a4e748de4f4a093119dadd6f17f165f',1,'Gadgetron::hoSPIRIT2DTOperator::gradient()'],['../class_gadgetron_1_1ho_s_p_i_r_i_t_operator.html#a442d03e7f8f5052e831518bf7d45e385',1,'Gadgetron::hoSPIRITOperator::gradient()'],['../class_gadgetron_1_1ho_tv_operator.html#a4093d0f6839b4ec1f4af7f26639f4224',1,'Gadgetron::hoTvOperator::gradient()'],['../class_gadgetron_1_1ho_wavelet1_d_base_operator.html#a31db105f53279378311aa887f6b4899b',1,'Gadgetron::hoWavelet1DBaseOperator::gradient()'],['../class_gadgetron_1_1ho_wavelet2_d_t_operator.html#a6c56d59566b2788f7dd8fc67e0d96df4',1,'Gadgetron::hoWavelet2DTOperator::gradient()'],['../class_gadgetron_1_1ho_wavelet_operator.html#a0e50b1d323152c769a79a1127d92be96',1,'Gadgetron::hoWaveletOperator::gradient()'],['../class_gadgetron_1_1general_operator.html#a37e7c004419a1c54857acb75422b847f',1,'Gadgetron::generalOperator::gradient()'],['../class_gadgetron_1_1cu_tv1_d_operator.html#aefc84d2792230cf9a0ab11d32ee63723',1,'Gadgetron::cuTv1DOperator::gradient()'],['../class_gadgetron_1_1cu_tv_operator.html#a9174a38456390c3e4f9e3abfda0ec22a',1,'Gadgetron::cuTvOperator::gradient()'],['../class_gadgetron_1_1ho_cu_operator.html#a1b39fd2f20113b3dfd89ca047daa0cfc',1,'Gadgetron::hoCuOperator::gradient()'],['../class_gadgetron_1_1ho_cu_tv_operator.html#a5a901013efeac1a2c0f4051586eb9c5f',1,'Gadgetron::hoCuTvOperator::gradient()'],['../class_gadgetron_1_1linear_operator.html#a71ba9841c70c97423b4dbf7ee1e58944',1,'Gadgetron::linearOperator::gradient()'],['../class_gadgetron_1_1tv_pics_operator.html#aad066421ae04dd97493485a986bc746f',1,'Gadgetron::tvPicsOperator::gradient()'],['../class_gadgetron_1_1gp_solver_1_1l2_g_p_regularization_operator.html#a31a2fe16e0bbcea349ac9a627e3516f8',1,'Gadgetron::gpSolver::l2GPRegularizationOperator::gradient()'],['../class_gadgetron_1_1gp_solver_1_1l1_g_p_regularization_operator.html#aa1dd9e4872f9109f58cd03315588e043',1,'Gadgetron::gpSolver::l1GPRegularizationOperator::gradient()'],['../class_gadgetron_1_1gp_solver_1_1l1_group_g_p_regularization_operator.html#a3073e629a54fd258478d103ce0f70872',1,'Gadgetron::gpSolver::l1GroupGPRegularizationOperator::gradient()'],['../namespace_gadgetron.html#a2ca9eb3607baadbcca27f6dc5bf253c9',1,'Gadgetron::gradient()']]],
  ['grappa2d_5fcalib',['grappa2d_calib',['../namespace_gadgetron.html#a9254941db8ddf8d599d6bf35e36661f0',1,'Gadgetron::grappa2d_calib(const hoNDArray&lt; T &gt; &amp;acsSrc, const hoNDArray&lt; T &gt; &amp;acsDst, double thres, size_t kRO, const std::vector&lt; int &gt; &amp;kE1, const std::vector&lt; int &gt; &amp;oE1, size_t startRO, size_t endRO, size_t startE1, size_t endE1, hoNDArray&lt; T &gt; &amp;ker)'],['../namespace_gadgetron.html#a1582cb38dd756704bee18716d06923e1',1,'Gadgetron::grappa2d_calib(const hoNDArray&lt; T &gt; &amp;acsSrc, const hoNDArray&lt; T &gt; &amp;acsDst, double thres, size_t kRO, const std::vector&lt; int &gt; &amp;kE1, const std::vector&lt; int &gt; &amp;oE1, hoNDArray&lt; T &gt; &amp;ker)']]],
  ['grappa2d_5fcalib_5fconvolution_5fkernel',['grappa2d_calib_convolution_kernel',['../namespace_gadgetron.html#a128ba3ef7a96442c97c214fd99b7e211',1,'Gadgetron::grappa2d_calib_convolution_kernel(const hoNDArray&lt; T &gt; &amp;acsSrc, const hoNDArray&lt; T &gt; &amp;acsDst, size_t accelFactor, double thres, size_t kRO, size_t kNE1, size_t startRO, size_t endRO, size_t startE1, size_t endE1, hoNDArray&lt; T &gt; &amp;convKer)'],['../namespace_gadgetron.html#ab9b78032bb6b70bd80abe0180392ffc0',1,'Gadgetron::grappa2d_calib_convolution_kernel(const hoNDArray&lt; T &gt; &amp;acsSrc, const hoNDArray&lt; T &gt; &amp;acsDst, size_t accelFactor, double thres, size_t kRO, size_t kNE1, hoNDArray&lt; T &gt; &amp;convKer)'],['../namespace_gadgetron.html#a3170fa6ca1639025496ad5a2b9a1ed53',1,'Gadgetron::grappa2d_calib_convolution_kernel(const hoNDArray&lt; T &gt; &amp;dataSrc, const hoNDArray&lt; T &gt; &amp;dataDst, hoNDArray&lt; unsigned short &gt; &amp;dataMask, size_t accelFactor, double thres, size_t kRO, size_t kNE1, hoNDArray&lt; T &gt; &amp;convKer)']]],
  ['grappa2d_5fconvert_5fto_5fconvolution_5fkernel',['grappa2d_convert_to_convolution_kernel',['../namespace_gadgetron.html#a58dfdac167ab3af1587c02bc8bff1008',1,'Gadgetron']]],
  ['grappa2d_5fimage_5fdomain_5fkernel',['grappa2d_image_domain_kernel',['../namespace_gadgetron.html#a1f1422627caba680af43a9bd14c2cc3c',1,'Gadgetron']]],
  ['grappa2d_5fkerpattern',['grappa2d_kerPattern',['../namespace_gadgetron.html#a5a824d41e4c21fff5ec10303d2a1c06e',1,'Gadgetron']]],
  ['grappa2d_5funmixing_5fcoeff',['grappa2d_unmixing_coeff',['../namespace_gadgetron.html#a975992abe6aed7a3b0d4db61f70ea2ff',1,'Gadgetron']]],
  ['grappa3d_5fcalib',['grappa3d_calib',['../namespace_gadgetron.html#a74e561a78b53db655ba7634670aa0f09',1,'Gadgetron']]],
  ['grappa3d_5fcalib_5fconvolution_5fkernel',['grappa3d_calib_convolution_kernel',['../namespace_gadgetron.html#ab88a4a909f7a13ebf0a4185cb8ad6340',1,'Gadgetron::grappa3d_calib_convolution_kernel(const hoNDArray&lt; T &gt; &amp;acsSrc, const hoNDArray&lt; T &gt; &amp;acsDst, size_t accelFactorE1, size_t accelFactorE2, double thres, double overDetermineRatio, size_t kRO, size_t kNE1, size_t kNE2, size_t startRO, size_t endRO, size_t startE1, size_t endE1, size_t startE2, size_t endE2, hoNDArray&lt; T &gt; &amp;convKer)'],['../namespace_gadgetron.html#ad01a31420051c030a7fcb85cb0b89b92',1,'Gadgetron::grappa3d_calib_convolution_kernel(const hoNDArray&lt; T &gt; &amp;acsSrc, const hoNDArray&lt; T &gt; &amp;acsDst, size_t accelFactorE1, size_t accelFactorE2, double thres, double overDetermineRatio, size_t kRO, size_t kNE1, size_t kNE2, hoNDArray&lt; T &gt; &amp;convKer)'],['../namespace_gadgetron.html#a46f29bbc5205f42fcf6fbe77cef701ed',1,'Gadgetron::grappa3d_calib_convolution_kernel(const hoNDArray&lt; T &gt; &amp;dataSrc, const hoNDArray&lt; T &gt; &amp;dataDst, hoNDArray&lt; unsigned short &gt; &amp;dataMask, size_t accelFactorE1, size_t accelFactorE2, double thres, double overDetermineRatio, size_t kRO, size_t kNE1, size_t kNE2, hoNDArray&lt; T &gt; &amp;convKer)']]],
  ['grappa3d_5fconvert_5fto_5fconvolution_5fkernel',['grappa3d_convert_to_convolution_kernel',['../namespace_gadgetron.html#a39c86a875fa7611fe46e0e2b692b4daf',1,'Gadgetron']]],
  ['grappa3d_5fimage_5fdomain_5fkernel',['grappa3d_image_domain_kernel',['../namespace_gadgetron.html#a3b6992ce2d706bca4f8ca1217fbd20eb',1,'Gadgetron']]],
  ['grappa3d_5fimage_5fdomain_5funwrapping',['grappa3d_image_domain_unwrapping',['../namespace_gadgetron.html#a56b3539744454f92987f7cd6c19298a2',1,'Gadgetron']]],
  ['grappa3d_5fimage_5fdomain_5funwrapping_5faliasedimage',['grappa3d_image_domain_unwrapping_aliasedImage',['../namespace_gadgetron.html#afd61aa74742fb4d11717426875379b8d',1,'Gadgetron']]],
  ['grappa3d_5fkerpattern',['grappa3d_kerPattern',['../namespace_gadgetron.html#a8627c34379ec30de33e73d43cdf0716a',1,'Gadgetron']]],
  ['grappa3d_5funmixing_5fcoeff',['grappa3d_unmixing_coeff',['../namespace_gadgetron.html#a7b8cf2c1b16844875f3ecaa4b6eed060',1,'Gadgetron']]],
  ['grappa_5fksize_5fro_5f',['grappa_kSize_RO_',['../struct_gadgetron_1_1gt_plus_1_1gt_plus_recon_work_order_para.html#ae0153c42d959857236b643acf2775039',1,'Gadgetron::gtPlus::gtPlusReconWorkOrderPara']]],
  ['grappabufferinfo',['GrappaBufferInfo',['../struct_gadgetron_1_1_grappa_buffer_info.html',1,'Gadgetron']]],
  ['grappacalibrationbuffer',['GrappaCalibrationBuffer',['../class_gadgetron_1_1_grappa_calibration_buffer.html',1,'Gadgetron']]],
  ['grappagadget',['GrappaGadget',['../class_gadgetron_1_1_grappa_gadget.html',1,'Gadgetron']]],
  ['grappaunmixinggadget',['GrappaUnmixingGadget',['../class_gadgetron_1_1_grappa_unmixing_gadget.html',1,'Gadgetron']]],
  ['grappaunmixingjob',['GrappaUnmixingJob',['../struct_gadgetron_1_1_grappa_unmixing_job.html',1,'Gadgetron']]],
  ['grappaweights',['GrappaWeights',['../class_gadgetron_1_1_grappa_weights.html',1,'Gadgetron']]],
  ['grappaweightscalculator',['GrappaWeightsCalculator',['../class_gadgetron_1_1_grappa_weights_calculator.html',1,'Gadgetron']]],
  ['grappaweightscalculator_3c_20float_20_3e',['GrappaWeightsCalculator&lt; float &gt;',['../class_gadgetron_1_1_grappa_weights_calculator.html',1,'Gadgetron']]],
  ['grappaweightsdescription',['GrappaWeightsDescription',['../class_gadgetron_1_1_grappa_weights_description.html',1,'Gadgetron']]],
  ['gt_5fexporter_5f',['gt_exporter_',['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#a4568506f9cb09d6da4611e5f63ccbbcf',1,'Gadgetron::gtPlus::gtplusFFDBase']]],
  ['gt_5fplplot_5ftest',['gt_plplot_Test',['../classgt__plplot___test.html',1,'']]],
  ['gt_5ftimer1_5f',['gt_timer1_',['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#ad8e65ed935f82f717f3ffc905ac78767',1,'Gadgetron::gtPlus::gtplusFFDBase']]],
  ['gtmatlabconverter',['gtMatlabConverter',['../class_gadgetron_1_1gt_matlab_converter.html',1,'Gadgetron']]],
  ['gtmatlabconvertercomplex',['gtMatlabConverterComplex',['../class_gadgetron_1_1gt_matlab_converter_complex.html',1,'Gadgetron']]],
  ['gtmatlabimageheader',['gtMatlabImageHeader',['../class_gadgetron_1_1gt_matlab_image_header.html',1,'Gadgetron']]],
  ['gtplplot_2ecpp',['GtPLplot.cpp',['../_gt_p_lplot_8cpp.html',1,'']]],
  ['gtplplot_2eh',['GtPLplot.h',['../_gt_p_lplot_8h.html',1,'']]],
  ['gtplus2dtgadgetcloudjobmessagereadercpfl',['GtPlus2DTGadgetCloudJobMessageReaderCPFL',['../class_gadgetron_1_1_gt_plus2_d_t_gadget_cloud_job_message_reader_c_p_f_l.html',1,'Gadgetron']]],
  ['gtplus2dtgadgetcloudjobmessagewritercpfl',['GtPlus2DTGadgetCloudJobMessageWriterCPFL',['../class_gadgetron_1_1_gt_plus2_d_t_gadget_cloud_job_message_writer_c_p_f_l.html',1,'Gadgetron']]],
  ['gtplus_5fgrappa_5ftest',['gtPlus_grappa_Test',['../classgt_plus__grappa___test.html',1,'']]],
  ['gtplus_5futil_5f',['gtPlus_util_',['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html#a8571e496b47bc83bee65b23307d7be67',1,'Gadgetron::gtPlus::gtplusFFDBase']]],
  ['gtplusaccumulatorworkordertriggergadget',['GtPlusAccumulatorWorkOrderTriggerGadget',['../class_gadgetron_1_1_gt_plus_accumulator_work_order_trigger_gadget.html',1,'Gadgetron']]],
  ['gtplusaccumulatorworkordertriggergadget_2eh',['GtPlusAccumulatorWorkOrderTriggerGadget.h',['../_gt_plus_accumulator_work_order_trigger_gadget_8h.html',1,'']]],
  ['gtplusalgorithmbase',['gtPlusAlgorithmBase',['../class_gadgetron_1_1gt_plus_1_1gt_plus_algorithm_base.html',1,'Gadgetron::gtPlus']]],
  ['gtplusalgorithmbase_2eh',['gtPlusAlgorithmBase.h',['../gt_plus_algorithm_base_8h.html',1,'']]],
  ['gtplusalgorithmbase_3c_20valuetype_20_3e',['gtPlusAlgorithmBase&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_algorithm_base.html',1,'Gadgetron::gtPlus']]],
  ['gtplusbsplineffd',['gtplusBSplineFFD',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html',1,'Gadgetron::gtPlus']]],
  ['gtplusbsplineffd_2eh',['gtplusBSplineFFD.h',['../gtplus_b_spline_f_f_d_8h.html',1,'']]],
  ['gtplusbsplineffd2d',['gtplusBSplineFFD2D',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d2_d.html#a4a837a6f9c5ac83355efdaa000583733',1,'Gadgetron::gtPlus::gtplusBSplineFFD2D::gtplusBSplineFFD2D()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d2_d.html#a6cb2ec926ab60c24b07ec2dbae0f11b0',1,'Gadgetron::gtPlus::gtplusBSplineFFD2D::gtplusBSplineFFD2D(const PointType &amp;start, const PointType &amp;end, CoordType dx, CoordType dy)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d2_d.html#aa296520484d42e317395adc1fe804033',1,'Gadgetron::gtPlus::gtplusBSplineFFD2D::gtplusBSplineFFD2D(const ImageType &amp;im, CoordType dx, CoordType dy)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d2_d.html#ab3f9b02ecb0b1e2f9b5c9290ed708229',1,'Gadgetron::gtPlus::gtplusBSplineFFD2D::gtplusBSplineFFD2D(const ImageType &amp;im, size_t sx, size_t sy)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d2_d.html#aa9f92b966b3bfaec2d5dc8d2963e1302',1,'Gadgetron::gtPlus::gtplusBSplineFFD2D::gtplusBSplineFFD2D(const ArrayType &amp;a, size_t sx, size_t sy)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d2_d.html#a4d8675f7effc91b76322f31b1f551989',1,'Gadgetron::gtPlus::gtplusBSplineFFD2D::gtplusBSplineFFD2D(const Self &amp;bffd)']]],
  ['gtplusbsplineffd2d',['gtplusBSplineFFD2D',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d2_d.html',1,'Gadgetron::gtPlus']]],
  ['gtplusbsplineffd2d_2eh',['gtplusBSplineFFD2D.h',['../gtplus_b_spline_f_f_d2_d_8h.html',1,'']]],
  ['gtplusbsplineffd3d',['gtplusBSplineFFD3D',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d3_d.html#a7481537b0d898081813a7c1ba91665db',1,'Gadgetron::gtPlus::gtplusBSplineFFD3D::gtplusBSplineFFD3D()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d3_d.html#abe5a08308465f2d4157e3d5a5bde420a',1,'Gadgetron::gtPlus::gtplusBSplineFFD3D::gtplusBSplineFFD3D(const PointType &amp;start, const PointType &amp;end, CoordType dx, CoordType dy, CoordType dz)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d3_d.html#a172313e4b660630c8961e8ba547fd8d1',1,'Gadgetron::gtPlus::gtplusBSplineFFD3D::gtplusBSplineFFD3D(const ImageType &amp;im, CoordType dx, CoordType dy, CoordType dz)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d3_d.html#a2a8465d9798b9e93f8e88a61c70312c5',1,'Gadgetron::gtPlus::gtplusBSplineFFD3D::gtplusBSplineFFD3D(const ImageType &amp;im, size_t sx, size_t sy, size_t sz)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d3_d.html#a5bb576a24a6c82b46511354320a20ba7',1,'Gadgetron::gtPlus::gtplusBSplineFFD3D::gtplusBSplineFFD3D(const ArrayType &amp;a, size_t sx, size_t sy, size_t sz)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d3_d.html#a6142266bc59aa5532e3d239cdc55c6a8',1,'Gadgetron::gtPlus::gtplusBSplineFFD3D::gtplusBSplineFFD3D(const Self &amp;bffd)']]],
  ['gtplusbsplineffd3d',['gtplusBSplineFFD3D',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d3_d.html',1,'Gadgetron::gtPlus']]],
  ['gtplusbsplineffd3d_2eh',['gtplusBSplineFFD3D.h',['../gtplus_b_spline_f_f_d3_d_8h.html',1,'']]],
  ['gtplusbsplineffd4d',['gtplusBSplineFFD4D',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d4_d.html#a21079508ab7dc0d632efe80c6a498b8a',1,'Gadgetron::gtPlus::gtplusBSplineFFD4D::gtplusBSplineFFD4D()'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d4_d.html#a6857e389e8a5848e562fbaf9c43cb3b1',1,'Gadgetron::gtPlus::gtplusBSplineFFD4D::gtplusBSplineFFD4D(const PointType &amp;start, const PointType &amp;end, CoordType dx, CoordType dy, CoordType dz, CoordType ds)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d4_d.html#a606e1b27f2dd8d9356ea081d5731c87a',1,'Gadgetron::gtPlus::gtplusBSplineFFD4D::gtplusBSplineFFD4D(const ImageType &amp;im, CoordType dx, CoordType dy, CoordType dz, CoordType ds)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d4_d.html#a33fb20cb1cc441caa40394cfee82dcd1',1,'Gadgetron::gtPlus::gtplusBSplineFFD4D::gtplusBSplineFFD4D(const ImageType &amp;im, size_t sx, size_t sy, size_t sz, size_t ss)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d4_d.html#a62ce20fe6742957bf52d500391b344f0',1,'Gadgetron::gtPlus::gtplusBSplineFFD4D::gtplusBSplineFFD4D(const ArrayType &amp;a, size_t sx, size_t sy, size_t sz, size_t ss)'],['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d4_d.html#a076e431c31e8ce7acece79909e076187',1,'Gadgetron::gtPlus::gtplusBSplineFFD4D::gtplusBSplineFFD4D(const Self &amp;bffd)']]],
  ['gtplusbsplineffd4d',['gtplusBSplineFFD4D',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d4_d.html',1,'Gadgetron::gtPlus']]],
  ['gtplusbsplineffd4d_2eh',['gtplusBSplineFFD4D.h',['../gtplus_b_spline_f_f_d4_d_8h.html',1,'']]],
  ['gtplusbsplineffd_3c_20t_2c_20coordtype_2c_202_2c_20dout_20_3e',['gtplusBSplineFFD&lt; T, CoordType, 2, DOut &gt;',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html',1,'Gadgetron::gtPlus']]],
  ['gtplusbsplineffd_3c_20t_2c_20coordtype_2c_203_2c_20dout_20_3e',['gtplusBSplineFFD&lt; T, CoordType, 3, DOut &gt;',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html',1,'Gadgetron::gtPlus']]],
  ['gtplusbsplineffd_3c_20t_2c_20coordtype_2c_204_2c_20dout_20_3e',['gtplusBSplineFFD&lt; T, CoordType, 4, DOut &gt;',['../class_gadgetron_1_1gt_plus_1_1gtplus_b_spline_f_f_d.html',1,'Gadgetron::gtPlus']]],
  ['gtpluscloudjobmessagereadercpfl',['GtPlusCloudJobMessageReaderCPFL',['../class_gadgetron_1_1_gt_plus_cloud_job_message_reader_c_p_f_l.html',1,'Gadgetron']]],
  ['gtpluscloudjobmessagewritercpfl',['GtPlusCloudJobMessageWriterCPFL',['../class_gadgetron_1_1_gt_plus_cloud_job_message_writer_c_p_f_l.html',1,'Gadgetron']]],
  ['gtpluscloudscheduler',['gtPlusCloudScheduler',['../class_gadgetron_1_1gt_plus_1_1gt_plus_cloud_scheduler.html',1,'Gadgetron::gtPlus']]],
  ['gtpluscloudscheduler_2ecpp',['gtPlusCloudScheduler.cpp',['../gt_plus_cloud_scheduler_8cpp.html',1,'']]],
  ['gtpluscloudscheduler_2eh',['gtPlusCloudScheduler.h',['../gt_plus_cloud_scheduler_8h.html',1,'']]],
  ['gtpluscloudschedulernodesorter',['gtPlusCloudSchedulerNodeSorter',['../struct_gadgetron_1_1gt_plus_1_1gt_plus_cloud_scheduler_node_sorter.html',1,'Gadgetron::gtPlus']]],
  ['gtplusexport_2eh',['GtPlusExport.h',['../_gt_plus_export_8h.html',1,'']]],
  ['gtplusffdbase',['gtplusFFDBase',['../class_gadgetron_1_1gt_plus_1_1gtplus_f_f_d_base.html',1,'Gadgetron::gtPlus']]],
  ['gtplusffdbase_2eh',['gtplusFFDBase.h',['../gtplus_f_f_d_base_8h.html',1,'']]],
  ['gtplusgadgetexport_2eh',['GtPlusGadgetExport.h',['../_gt_plus_gadget_export_8h.html',1,'']]],
  ['gtplusgadgetimagearray',['GtPlusGadgetImageArray',['../struct_gadgetron_1_1_gt_plus_gadget_image_array.html',1,'Gadgetron']]],
  ['gtplusgadgetimagearray_2eh',['GtPlusGadgetImageArray.h',['../_gt_plus_gadget_image_array_8h.html',1,'']]],
  ['gtplusgadgetimageext',['GtPlusGadgetImageExt',['../struct_gadgetron_1_1_gt_plus_gadget_image_ext.html',1,'Gadgetron']]],
  ['gtplusgadgetopenmp_2eh',['GtPlusGadgetOpenMP.h',['../_gt_plus_gadget_open_m_p_8h.html',1,'']]],
  ['gtplusgrappa',['gtPlusGRAPPA',['../class_gadgetron_1_1gt_plus_1_1gt_plus_g_r_a_p_p_a.html',1,'Gadgetron::gtPlus']]],
  ['gtplusgrappa_2eh',['gtPlusGRAPPA.h',['../gt_plus_g_r_a_p_p_a_8h.html',1,'']]],
  ['gtplusgrappa_3c_20valuetype_20_3e',['gtPlusGRAPPA&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_g_r_a_p_p_a.html',1,'Gadgetron::gtPlus']]],
  ['gtplusioanalyze',['gtPlusIOAnalyze',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_o_analyze.html',1,'Gadgetron::gtPlus']]],
  ['gtplusioanalyze_2ecpp',['gtPlusIOAnalyze.cpp',['../gt_plus_i_o_analyze_8cpp.html',1,'']]],
  ['gtplusioanalyze_2eh',['gtPlusIOAnalyze.h',['../gt_plus_i_o_analyze_8h.html',1,'']]],
  ['gtplusiobase',['gtPlusIOBase',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_o_base.html',1,'Gadgetron::gtPlus']]],
  ['gtplusiobase_2ecpp',['gtPlusIOBase.cpp',['../gt_plus_i_o_base_8cpp.html',1,'']]],
  ['gtplusiobase_2eh',['gtPlusIOBase.h',['../gt_plus_i_o_base_8h.html',1,'']]],
  ['gtplusiobase_3c_20dsr_20_3e',['gtPlusIOBase&lt; dsr &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_o_base.html',1,'Gadgetron::gtPlus']]],
  ['gtplusioexport_2eh',['GtPlusIOExport.h',['../_gt_plus_i_o_export_8h.html',1,'']]],
  ['gtplusioworker',['gtPlusIOWorker',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_o_worker.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconcoilmapestimation',['gtPlusISMRMRDReconCoilMapEstimation',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_coil_map_estimation.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconcoilmapestimation_2eh',['gtPlusISMRMRDReconCoilMapEstimation.h',['../gt_plus_i_s_m_r_m_r_d_recon_coil_map_estimation_8h.html',1,'']]],
  ['gtplusismrmrdreconutil',['gtPlusISMRMRDReconUtil',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_util.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconutil_2eh',['gtPlusISMRMRDReconUtil.h',['../gt_plus_i_s_m_r_m_r_d_recon_util_8h.html',1,'']]],
  ['gtplusismrmrdreconutil_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e',['gtPlusISMRMRDReconUtil&lt; std::complex&lt; float &gt; &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_util.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconutil_3c_20valuetype_20_3e',['gtPlusISMRMRDReconUtil&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_util.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconutilcomplex',['gtPlusISMRMRDReconUtilComplex',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_util_complex.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconutilcomplex_3c_20valuetype_20_3e',['gtPlusISMRMRDReconUtilComplex&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_util_complex.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworker_2eh',['gtPlusISMRMRDReconWorker.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker_8h.html',1,'']]],
  ['gtplusismrmrdreconworker2dt_2eh',['gtPlusISMRMRDReconWorker2DT.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker2_d_t_8h.html',1,'']]],
  ['gtplusismrmrdreconworker2dtgrappa_2eh',['gtPlusISMRMRDReconWorker2DTGRAPPA.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker2_d_t_g_r_a_p_p_a_8h.html',1,'']]],
  ['gtplusismrmrdreconworker2dtl1spiritncg_2eh',['gtPlusISMRMRDReconWorker2DTL1SPIRITNCG.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker2_d_t_l1_s_p_i_r_i_t_n_c_g_8h.html',1,'']]],
  ['gtplusismrmrdreconworker2dtnoacceleration_2eh',['gtPlusISMRMRDReconWorker2DTNoAcceleration.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker2_d_t_no_acceleration_8h.html',1,'']]],
  ['gtplusismrmrdreconworker2dtspirit_2eh',['gtPlusISMRMRDReconWorker2DTSPIRIT.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker2_d_t_s_p_i_r_i_t_8h.html',1,'']]],
  ['gtplusismrmrdreconworker3dt_2eh',['gtPlusISMRMRDReconWorker3DT.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker3_d_t_8h.html',1,'']]],
  ['gtplusismrmrdreconworker3dtgrappa_2eh',['gtPlusISMRMRDReconWorker3DTGRAPPA.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker3_d_t_g_r_a_p_p_a_8h.html',1,'']]],
  ['gtplusismrmrdreconworker3dtl1spiritncg_2eh',['gtPlusISMRMRDReconWorker3DTL1SPIRITNCG.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker3_d_t_l1_s_p_i_r_i_t_n_c_g_8h.html',1,'']]],
  ['gtplusismrmrdreconworker3dtnoacceleration_2eh',['gtPlusISMRMRDReconWorker3DTNoAcceleration.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker3_d_t_no_acceleration_8h.html',1,'']]],
  ['gtplusismrmrdreconworker3dtspirit_2eh',['gtPlusISMRMRDReconWorker3DTSPIRIT.h',['../gt_plus_i_s_m_r_m_r_d_recon_worker3_d_t_s_p_i_r_i_t_8h.html',1,'']]],
  ['gtplusismrmrdreconworkflow',['gtPlusISMRMRDReconWorkFlow',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworkflow_2eh',['gtPlusISMRMRDReconWorkFlow.h',['../gt_plus_i_s_m_r_m_r_d_recon_work_flow_8h.html',1,'']]],
  ['gtplusismrmrdreconworkflow_3c_20valuetype_20_3e',['gtPlusISMRMRDReconWorkFlow&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworkflowcartesian',['gtPlusISMRMRDReconWorkFlowCartesian',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworkflowcartesian_2eh',['gtPlusISMRMRDReconWorkFlowCartesian.h',['../gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian_8h.html',1,'']]],
  ['gtplusismrmrdreconworkflowcartesian2dt',['gtPlusISMRMRDReconWorkFlowCartesian2DT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian2_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworkflowcartesian2dt_2eh',['gtPlusISMRMRDReconWorkFlowCartesian2DT.h',['../gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian2_d_t_8h.html',1,'']]],
  ['gtplusismrmrdreconworkflowcartesian2dt_3c_20valuetype_20_3e',['gtPlusISMRMRDReconWorkFlowCartesian2DT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian2_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworkflowcartesian3dt',['gtPlusISMRMRDReconWorkFlowCartesian3DT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian3_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworkflowcartesian3dt_2eh',['gtPlusISMRMRDReconWorkFlowCartesian3DT.h',['../gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian3_d_t_8h.html',1,'']]],
  ['gtplusismrmrdreconworkflowcartesian3dt_3c_20valuetype_20_3e',['gtPlusISMRMRDReconWorkFlowCartesian3DT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian3_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworkflowcartesian_3c_20valuetype_20_3e',['gtPlusISMRMRDReconWorkFlowCartesian&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_i_s_m_r_m_r_d_recon_work_flow_cartesian.html',1,'Gadgetron::gtPlus']]],
  ['gtplusismrmrdreconworkorder_2eh',['gtPlusISMRMRDReconWorkOrder.h',['../gt_plus_i_s_m_r_m_r_d_recon_work_order_8h.html',1,'']]],
  ['gtplusismrmrdreconworkorder2dt_2eh',['gtPlusISMRMRDReconWorkOrder2DT.h',['../gt_plus_i_s_m_r_m_r_d_recon_work_order2_d_t_8h.html',1,'']]],
  ['gtplusismrmrdreconworkorder3dt_2eh',['gtPlusISMRMRDReconWorkOrder3DT.h',['../gt_plus_i_s_m_r_m_r_d_recon_work_order3_d_t_8h.html',1,'']]],
  ['gtplusmlffd',['gtplusMLFFD',['../class_gadgetron_1_1gt_plus_1_1gtplus_m_l_f_f_d.html',1,'Gadgetron::gtPlus']]],
  ['gtplusmlffd_2eh',['gtplusMLFFD.h',['../gtplus_m_l_f_f_d_8h.html',1,'']]],
  ['gtplusrecon2dtcloudpackage',['GtPlusRecon2DTCloudPackage',['../struct_gadgetron_1_1_gt_plus_recon2_d_t_cloud_package.html',1,'Gadgetron']]],
  ['gtplusrecon2dtcloudpackage_2eh',['GtPlusRecon2DTCloudPackage.h',['../_gt_plus_recon2_d_t_cloud_package_8h.html',1,'']]],
  ['gtplusrecon2dtgadget',['GtPlusRecon2DTGadget',['../class_gadgetron_1_1_gt_plus_recon2_d_t_gadget.html',1,'Gadgetron']]],
  ['gtplusrecon2dtgadget_2eh',['GtPlusRecon2DTGadget.h',['../_gt_plus_recon2_d_t_gadget_8h.html',1,'']]],
  ['gtplusrecon2dtgadgetcloud',['GtPlusRecon2DTGadgetCloud',['../class_gadgetron_1_1_gt_plus_recon2_d_t_gadget_cloud.html',1,'Gadgetron']]],
  ['gtplusrecon2dtgadgetcloud_2eh',['GtPlusRecon2DTGadgetCloud.h',['../_gt_plus_recon2_d_t_gadget_cloud_8h.html',1,'']]],
  ['gtplusrecon2dtgadgetcloudsender',['GtPlusRecon2DTGadgetCloudSender',['../class_gadgetron_1_1_gt_plus_recon2_d_t_gadget_cloud_sender.html',1,'Gadgetron']]],
  ['gtplusrecon2dtpara',['GtPlusRecon2DTPara',['../struct_gadgetron_1_1_gt_plus_recon2_d_t_para.html',1,'Gadgetron']]],
  ['gtplusrecon3dtgadget',['GtPlusRecon3DTGadget',['../class_gadgetron_1_1_gt_plus_recon3_d_t_gadget.html',1,'Gadgetron']]],
  ['gtplusrecon3dtgadget_2eh',['GtPlusRecon3DTGadget.h',['../_gt_plus_recon3_d_t_gadget_8h.html',1,'']]],
  ['gtplusrecon3dtpara',['GtPlusRecon3DTPara',['../struct_gadgetron_1_1_gt_plus_recon3_d_t_para.html',1,'Gadgetron']]],
  ['gtplusrecongadget',['GtPlusReconGadget',['../class_gadgetron_1_1_gt_plus_recon_gadget.html',1,'Gadgetron']]],
  ['gtplusrecongadget_2eh',['GtPlusReconGadget.h',['../_gt_plus_recon_gadget_8h.html',1,'']]],
  ['gtplusrecongadgetutil_2eh',['GtPlusReconGadgetUtil.h',['../_gt_plus_recon_gadget_util_8h.html',1,'']]],
  ['gtplusreconjob2dt',['gtPlusReconJob2DT',['../struct_gadgetron_1_1gt_plus_1_1gt_plus_recon_job2_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconjob2dtgadget',['GtPlusReconJob2DTGadget',['../class_gadgetron_1_1_gt_plus_recon_job2_d_t_gadget.html',1,'Gadgetron']]],
  ['gtplusreconjob2dtgadget_2eh',['GtPlusReconJob2DTGadget.h',['../_gt_plus_recon_job2_d_t_gadget_8h.html',1,'']]],
  ['gtplusreconjob2dtgadgetcloud',['GtPlusReconJob2DTGadgetCloud',['../class_gadgetron_1_1_gt_plus_recon_job2_d_t_gadget_cloud.html',1,'Gadgetron']]],
  ['gtplusreconjob2dtgadgetcloud_2eh',['GtPlusReconJob2DTGadgetCloud.h',['../_gt_plus_recon_job2_d_t_gadget_cloud_8h.html',1,'']]],
  ['gtplusreconjob3dtgadget',['GtPlusReconJob3DTGadget',['../class_gadgetron_1_1_gt_plus_recon_job3_d_t_gadget.html',1,'Gadgetron']]],
  ['gtplusreconjob3dtgadget_2eh',['GtPlusReconJob3DTGadget.h',['../_gt_plus_recon_job3_d_t_gadget_8h.html',1,'']]],
  ['gtplusreconworker',['gtPlusReconWorker',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dt',['gtPlusReconWorker2DT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dt_3c_20valuetype_20_3e',['gtPlusReconWorker2DT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dtgrappa',['gtPlusReconWorker2DTGRAPPA',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t_g_r_a_p_p_a.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dtgrappa_3c_20valuetype_20_3e',['gtPlusReconWorker2DTGRAPPA&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t_g_r_a_p_p_a.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dtl1spiritncg',['gtPlusReconWorker2DTL1SPIRITNCG',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t_l1_s_p_i_r_i_t_n_c_g.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dtnoacceleration',['gtPlusReconWorker2DTNoAcceleration',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t_no_acceleration.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dtnoacceleration_3c_20valuetype_20_3e',['gtPlusReconWorker2DTNoAcceleration&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t_no_acceleration.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dtspirit',['gtPlusReconWorker2DTSPIRIT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t_s_p_i_r_i_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker2dtspirit_3c_20valuetype_20_3e',['gtPlusReconWorker2DTSPIRIT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker2_d_t_s_p_i_r_i_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dt',['gtPlusReconWorker3DT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dt_3c_20valuetype_20_3e',['gtPlusReconWorker3DT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dtgrappa',['gtPlusReconWorker3DTGRAPPA',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t_g_r_a_p_p_a.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dtgrappa_3c_20valuetype_20_3e',['gtPlusReconWorker3DTGRAPPA&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t_g_r_a_p_p_a.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dtl1spiritncg',['gtPlusReconWorker3DTL1SPIRITNCG',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t_l1_s_p_i_r_i_t_n_c_g.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dtnoacceleration',['gtPlusReconWorker3DTNoAcceleration',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t_no_acceleration.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dtnoacceleration_3c_20valuetype_20_3e',['gtPlusReconWorker3DTNoAcceleration&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t_no_acceleration.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dtspirit',['gtPlusReconWorker3DTSPIRIT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t_s_p_i_r_i_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker3dtspirit_3c_20valuetype_20_3e',['gtPlusReconWorker3DTSPIRIT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker3_d_t_s_p_i_r_i_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworker_3c_20valuetype_20_3e',['gtPlusReconWorker&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_worker.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworkorder',['gtPlusReconWorkOrder',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_work_order.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworkorder2dt',['gtPlusReconWorkOrder2DT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_work_order2_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworkorder2dt_3c_20valuetype_20_3e',['gtPlusReconWorkOrder2DT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_work_order2_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworkorder3dt',['gtPlusReconWorkOrder3DT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_work_order3_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworkorder3dt_3c_20valuetype_20_3e',['gtPlusReconWorkOrder3DT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_work_order3_d_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworkorder_3c_20valuetype_20_3e',['gtPlusReconWorkOrder&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_recon_work_order.html',1,'Gadgetron::gtPlus']]],
  ['gtplusreconworkorderpara',['gtPlusReconWorkOrderPara',['../struct_gadgetron_1_1gt_plus_1_1gt_plus_recon_work_order_para.html',1,'Gadgetron::gtPlus']]],
  ['gtplusspirit',['gtPlusSPIRIT',['../class_gadgetron_1_1gt_plus_1_1gt_plus_s_p_i_r_i_t.html',1,'Gadgetron::gtPlus']]],
  ['gtplusspirit_2eh',['gtPlusSPIRIT.h',['../gt_plus_s_p_i_r_i_t_8h.html',1,'']]],
  ['gtplusspirit_3c_20valuetype_20_3e',['gtPlusSPIRIT&lt; ValueType &gt;',['../class_gadgetron_1_1gt_plus_1_1gt_plus_s_p_i_r_i_t.html',1,'Gadgetron::gtPlus']]]
];
