var searchData=
[
  ['s',['S',['../structcrow_1_1black__magic_1_1_s.html',1,'crow::black_magic']]],
  ['samplingdescription',['SamplingDescription',['../class_gadgetron_1_1_sampling_description.html',1,'Gadgetron::SamplingDescription'],['../classgadgetron_1_1_sampling_description.html',1,'gadgetron.SamplingDescription']]],
  ['samplinglimit',['SamplingLimit',['../classgadgetron_1_1_sampling_limit.html',1,'gadgetron.SamplingLimit'],['../class_gadgetron_1_1_sampling_limit.html',1,'Gadgetron::SamplingLimit']]],
  ['sbcsolver',['sbcSolver',['../class_gadgetron_1_1sbc_solver.html',1,'Gadgetron']]],
  ['sbcsolver_3c_20cundarray_3c_20realtype_3c_20gadgetron_3a_3acomplext_20_3e_3a_3atype_20_3e_2c_20cundarray_3c_20gadgetron_3a_3acomplext_20_3e_2c_20cucgsolver_3c_20gadgetron_3a_3acomplext_20_3e_20_3e',['sbcSolver&lt; cuNDArray&lt; realType&lt; Gadgetron::complext &gt;::Type &gt;, cuNDArray&lt; Gadgetron::complext &gt;, cuCgSolver&lt; Gadgetron::complext &gt; &gt;',['../class_gadgetron_1_1sbc_solver.html',1,'Gadgetron']]],
  ['sbcsolver_3c_20cundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20cundarray_3c_20t_20_3e_2c_20cucgsolver_3c_20t_20_3e_20_3e',['sbcSolver&lt; cuNDArray&lt; realType&lt; T &gt;::Type &gt;, cuNDArray&lt; T &gt;, cuCgSolver&lt; T &gt; &gt;',['../class_gadgetron_1_1sbc_solver.html',1,'Gadgetron']]],
  ['sbcsolver_3c_20cundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20cundarray_3c_20t_20_3e_2c_20culwsolver_3c_20t_20_3e_20_3e',['sbcSolver&lt; cuNDArray&lt; realType&lt; T &gt;::type &gt;, cuNDArray&lt; T &gt;, cuLwSolver&lt; T &gt; &gt;',['../class_gadgetron_1_1sbc_solver.html',1,'Gadgetron']]],
  ['sbcsolver_3c_20hocundarray_3c_20realtype_3c_20float_20_3e_3a_3atype_20_3e_2c_20hocundarray_3c_20float_20_3e_2c_20hocucgsolver_3c_20float_20_3e_20_3e',['sbcSolver&lt; hoCuNDArray&lt; realType&lt; float &gt;::Type &gt;, hoCuNDArray&lt; float &gt;, hoCuCgSolver&lt; float &gt; &gt;',['../class_gadgetron_1_1sbc_solver.html',1,'Gadgetron']]],
  ['sbcsolver_3c_20hocundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20hocundarray_3c_20t_20_3e_2c_20hocucgsolver_3c_20t_20_3e_20_3e',['sbcSolver&lt; hoCuNDArray&lt; realType&lt; T &gt;::Type &gt;, hoCuNDArray&lt; T &gt;, hoCuCgSolver&lt; T &gt; &gt;',['../class_gadgetron_1_1sbc_solver.html',1,'Gadgetron']]],
  ['sbl0groupregularizationoperator',['sbL0GroupRegularizationOperator',['../class_gadgetron_1_1sb_solver_1_1sb_l0_group_regularization_operator.html',1,'Gadgetron::sbSolver']]],
  ['sbl0regularizationoperator',['sbL0RegularizationOperator',['../class_gadgetron_1_1sb_solver_1_1sb_l0_regularization_operator.html',1,'Gadgetron::sbSolver']]],
  ['sbl1groupregularizationoperator',['sbL1GroupRegularizationOperator',['../class_gadgetron_1_1sb_solver_1_1sb_l1_group_regularization_operator.html',1,'Gadgetron::sbSolver']]],
  ['sbl1regularizationoperator',['sbL1RegularizationOperator',['../class_gadgetron_1_1sb_solver_1_1sb_l1_regularization_operator.html',1,'Gadgetron::sbSolver']]],
  ['sbl2regularizationoperator',['sbL2RegularizationOperator',['../class_gadgetron_1_1sb_solver_1_1sb_l2_regularization_operator.html',1,'Gadgetron::sbSolver']]],
  ['sbnonnegativityoperator',['sbNonNegativityOperator',['../class_gadgetron_1_1sb_solver_1_1sb_non_negativity_operator.html',1,'Gadgetron::sbSolver']]],
  ['sbregularizationoperator',['sbRegularizationOperator',['../class_gadgetron_1_1sb_solver_1_1sb_regularization_operator.html',1,'Gadgetron::sbSolver']]],
  ['sbsolver',['sbSolver',['../class_gadgetron_1_1sb_solver.html',1,'Gadgetron']]],
  ['sbsolver_3c_20cundarray_3c_20realtype_3c_20gadgetron_3a_3acomplext_20_3e_3a_3atype_20_3e_2c_20cundarray_3c_20gadgetron_3a_3acomplext_20_3e_2c_20cucgsolver_3c_20gadgetron_3a_3acomplext_20_3e_20_3e',['sbSolver&lt; cuNDArray&lt; realType&lt; Gadgetron::complext &gt;::Type &gt;, cuNDArray&lt; Gadgetron::complext &gt;, cuCgSolver&lt; Gadgetron::complext &gt; &gt;',['../class_gadgetron_1_1sb_solver.html',1,'Gadgetron']]],
  ['sbsolver_3c_20cundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20cundarray_3c_20t_20_3e_2c_20cucgsolver_3c_20t_20_3e_20_3e',['sbSolver&lt; cuNDArray&lt; realType&lt; T &gt;::Type &gt;, cuNDArray&lt; T &gt;, cuCgSolver&lt; T &gt; &gt;',['../class_gadgetron_1_1sb_solver.html',1,'Gadgetron']]],
  ['sbsolver_3c_20cundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20cundarray_3c_20t_20_3e_2c_20culwsolver_3c_20t_20_3e_20_3e',['sbSolver&lt; cuNDArray&lt; realType&lt; T &gt;::type &gt;, cuNDArray&lt; T &gt;, cuLwSolver&lt; T &gt; &gt;',['../class_gadgetron_1_1sb_solver.html',1,'Gadgetron']]],
  ['sbsolver_3c_20hocundarray_3c_20realtype_3c_20float_20_3e_3a_3atype_20_3e_2c_20hocundarray_3c_20float_20_3e_2c_20hocucgsolver_3c_20float_20_3e_20_3e',['sbSolver&lt; hoCuNDArray&lt; realType&lt; float &gt;::Type &gt;, hoCuNDArray&lt; float &gt;, hoCuCgSolver&lt; float &gt; &gt;',['../class_gadgetron_1_1sb_solver.html',1,'Gadgetron']]],
  ['sbsolver_3c_20hocundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20hocundarray_3c_20t_20_3e_2c_20hocucgsolver_3c_20t_20_3e_20_3e',['sbSolver&lt; hoCuNDArray&lt; realType&lt; T &gt;::Type &gt;, hoCuNDArray&lt; T &gt;, hoCuCgSolver&lt; T &gt; &gt;',['../class_gadgetron_1_1sb_solver.html',1,'Gadgetron']]],
  ['sbsolver_3c_20hondarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20hondarray_3c_20t_20_3e_2c_20hocgsolver_3c_20t_20_3e_20_3e',['sbSolver&lt; hoNDArray&lt; realType&lt; T &gt;::Type &gt;, hoNDArray&lt; T &gt;, hoCgSolver&lt; T &gt; &gt;',['../class_gadgetron_1_1sb_solver.html',1,'Gadgetron']]],
  ['senseoperator',['senseOperator',['../class_gadgetron_1_1sense_operator.html',1,'Gadgetron']]],
  ['senseoperator_3c_20cundarray_3c_20complext_3c_20real_20_3e_20_3e_2c_20d_20_3e',['senseOperator&lt; cuNDArray&lt; complext&lt; REAL &gt; &gt;, D &gt;',['../class_gadgetron_1_1sense_operator.html',1,'Gadgetron']]],
  ['seq',['seq',['../struct_gadgetron_1_1seq.html',1,'Gadgetron']]],
  ['seq',['seq',['../structcrow_1_1black__magic_1_1seq.html',1,'crow::black_magic']]],
  ['seq_3c_200_20_3e',['seq&lt; 0 &gt;',['../structcrow_1_1black__magic_1_1seq.html',1,'crow::black_magic']]],
  ['seq_3c_20i1_2e_2e_2e_2c_28sizeof_2e_2e_2e_28i1_29_2bi2_29_2e_2e_2e_3e',['seq&lt; I1...,(sizeof...(I1)+I2)...&gt;',['../structcrow_1_1black__magic_1_1seq.html',1,'crow::black_magic']]],
  ['server',['Server',['../classcrow_1_1_server.html',1,'crow']]],
  ['simplerecongadget',['SimpleReconGadget',['../class_gadgetron_1_1_simple_recon_gadget.html',1,'Gadgetron']]],
  ['single_5ftag_5fto_5ftype',['single_tag_to_type',['../structcrow_1_1black__magic_1_1single__tag__to__type.html',1,'crow::black_magic']]],
  ['single_5ftag_5fto_5ftype_3c_201_20_3e',['single_tag_to_type&lt; 1 &gt;',['../structcrow_1_1black__magic_1_1single__tag__to__type_3_011_01_4.html',1,'crow::black_magic']]],
  ['single_5ftag_5fto_5ftype_3c_202_20_3e',['single_tag_to_type&lt; 2 &gt;',['../structcrow_1_1black__magic_1_1single__tag__to__type_3_012_01_4.html',1,'crow::black_magic']]],
  ['single_5ftag_5fto_5ftype_3c_203_20_3e',['single_tag_to_type&lt; 3 &gt;',['../structcrow_1_1black__magic_1_1single__tag__to__type_3_013_01_4.html',1,'crow::black_magic']]],
  ['single_5ftag_5fto_5ftype_3c_204_20_3e',['single_tag_to_type&lt; 4 &gt;',['../structcrow_1_1black__magic_1_1single__tag__to__type_3_014_01_4.html',1,'crow::black_magic']]],
  ['single_5ftag_5fto_5ftype_3c_205_20_3e',['single_tag_to_type&lt; 5 &gt;',['../structcrow_1_1black__magic_1_1single__tag__to__type_3_015_01_4.html',1,'crow::black_magic']]],
  ['socketadaptor',['SocketAdaptor',['../structcrow_1_1_socket_adaptor.html',1,'crow']]],
  ['solver',['solver',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20array_5ftype_2c_20array_5ftype_20_3e',['solver&lt; ARRAY_TYPE, ARRAY_TYPE &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20array_5ftype_5felement_2c_20array_5ftype_5felement_20_3e',['solver&lt; ARRAY_TYPE_ELEMENT, ARRAY_TYPE_ELEMENT &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20cundarray_3c_20float_5fcomplext_20_3e_2c_20cundarray_3c_20float_5fcomplext_20_3e_20_3e',['solver&lt; cuNDArray&lt; float_complext &gt;, cuNDArray&lt; float_complext &gt; &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20cundarray_3c_20gadgetron_3a_3acomplext_20_3e_2c_20cundarray_3c_20gadgetron_3a_3acomplext_20_3e_20_3e',['solver&lt; cuNDArray&lt; Gadgetron::complext &gt;, cuNDArray&lt; Gadgetron::complext &gt; &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20cundarray_3c_20t_20_3e_2c_20cundarray_3c_20t_20_3e_20_3e',['solver&lt; cuNDArray&lt; T &gt;, cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20gadgetron_3a_3acundarray_3c_20gadgetron_3a_3acomplext_20_3e_2c_20gadgetron_3a_3acundarray_3c_20gadgetron_3a_3acomplext_20_3e_20_3e',['solver&lt; Gadgetron::cuNDArray&lt; Gadgetron::complext &gt;, Gadgetron::cuNDArray&lt; Gadgetron::complext &gt; &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20hocundarray_3c_20float_20_3e_2c_20hocundarray_3c_20float_20_3e_20_3e',['solver&lt; hoCuNDArray&lt; float &gt;, hoCuNDArray&lt; float &gt; &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20hocundarray_3c_20t_20_3e_2c_20hocundarray_3c_20t_20_3e_20_3e',['solver&lt; hoCuNDArray&lt; T &gt;, hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20hondarray_3c_20t_20_3e_2c_20hondarray_3c_20t_20_3e_20_3e',['solver&lt; hoNDArray&lt; T &gt;, hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20registrationdata_3c_20array_5ftype_20_3e_2c_20array_5ftype_20_3e',['solver&lt; registrationData&lt; ARRAY_TYPE &gt;, ARRAY_TYPE &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20registrationdata_3c_20array_5ftype_5freal_20_3e_2c_20array_5ftype_5freal_20_3e',['solver&lt; registrationData&lt; ARRAY_TYPE_REAL &gt;, ARRAY_TYPE_REAL &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['solver_3c_20registrationdata_3c_20cundarray_3c_20t_20_3e_20_3e_2c_20cundarray_3c_20t_20_3e_20_3e',['solver&lt; registrationData&lt; cuNDArray&lt; T &gt; &gt;, cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1solver.html',1,'Gadgetron']]],
  ['spiraltogenericgadget',['SpiralToGenericGadget',['../class_gadgetron_1_1_spiral_to_generic_gadget.html',1,'Gadgetron']]],
  ['spline',['Spline',['../class_spline.html',1,'']]],
  ['stdtype',['stdType',['../struct_gadgetron_1_1std_type.html',1,'Gadgetron']]],
  ['stdtype_3c_20double_20_3e',['stdType&lt; double &gt;',['../struct_gadgetron_1_1std_type_3_01double_01_4.html',1,'Gadgetron']]],
  ['stdtype_3c_20double_5fcomplext_20_3e',['stdType&lt; double_complext &gt;',['../struct_gadgetron_1_1std_type_3_01double__complext_01_4.html',1,'Gadgetron']]],
  ['stdtype_3c_20float_20_3e',['stdType&lt; float &gt;',['../struct_gadgetron_1_1std_type_3_01float_01_4.html',1,'Gadgetron']]],
  ['stdtype_3c_20float_5fcomplext_20_3e',['stdType&lt; float_complext &gt;',['../struct_gadgetron_1_1std_type_3_01float__complext_01_4.html',1,'Gadgetron']]],
  ['stdtype_3c_20std_3a_3acomplex_3c_20double_20_3e_20_3e',['stdType&lt; std::complex&lt; double &gt; &gt;',['../struct_gadgetron_1_1std_type_3_01std_1_1complex_3_01double_01_4_01_4.html',1,'Gadgetron']]],
  ['stdtype_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e',['stdType&lt; std::complex&lt; float &gt; &gt;',['../struct_gadgetron_1_1std_type_3_01std_1_1complex_3_01float_01_4_01_4.html',1,'Gadgetron']]],
  ['subsetoperator',['subsetOperator',['../class_gadgetron_1_1subset_operator.html',1,'Gadgetron']]],
  ['subsetoperator_3c_20array_20_3e',['subsetOperator&lt; ARRAY &gt;',['../class_gadgetron_1_1subset_operator.html',1,'Gadgetron']]]
];
