var searchData=
[
  ['ndarray',['NDArray',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20computing_5fvalue_5ftype_20_3e',['NDArray&lt; computing_value_type &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20coordtype_20_3e',['NDArray&lt; CoordType &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20float_20_3e',['NDArray&lt; float &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20float_5fcomplext_20_3e',['NDArray&lt; float_complext &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20gadgetron_3a_3acomplext_20_3e',['NDArray&lt; Gadgetron::complext &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20hist_5fvalue_5ftype_20_3e',['NDArray&lt; hist_value_type &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20ismrmrd_3a_3aacquisitionheader_20_3e',['NDArray&lt; ISMRMRD::AcquisitionHeader &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20ismrmrd_3a_3aimageheader_20_3e',['NDArray&lt; ISMRMRD::ImageHeader &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20real_5fvalue_5ftype_20_3e',['NDArray&lt; real_value_type &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20realtype_3c_20float_20_3e_3a_3atype_20_3e',['NDArray&lt; realType&lt; float &gt;::Type &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20realtype_3c_20gadgetron_3a_3acomplext_20_3e_3a_3atype_20_3e',['NDArray&lt; realType&lt; Gadgetron::complext &gt;::Type &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e',['NDArray&lt; realType&lt; T &gt;::Type &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron::NDArray&lt; realType&lt; T &gt;::Type &gt;'],['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron::NDArray&lt; realType&lt; T &gt;::type &gt;']]],
  ['ndarray_3c_20std_3a_3acomplex_3c_20double_20_3e_20_3e',['NDArray&lt; std::complex&lt; double &gt; &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e',['NDArray&lt; std::complex&lt; float &gt; &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['NDArray&lt; std::complex&lt; T &gt; &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20tobjecttype_20_2a_20_3e',['NDArray&lt; TObjectType * &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20typename_20gadgetron_3a_3arealtype_3c_20t_20_3e_3a_3atype_20_3e',['NDArray&lt; typename Gadgetron::realType&lt; T &gt;::Type &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20unsigned_20short_20_3e',['NDArray&lt; unsigned short &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20value_5ftype_20_3e',['NDArray&lt; value_type &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['ndarray_3c_20valuetype_20_3e',['NDArray&lt; ValueType &gt;',['../class_gadgetron_1_1_n_d_array.html',1,'Gadgetron']]],
  ['nfft2dgadget',['NFFT2DGadget',['../class_gadgetron_1_1_n_f_f_t2_d_gadget.html',1,'Gadgetron']]],
  ['nlcgsolver',['nlcgSolver',['../class_gadgetron_1_1nlcg_solver.html',1,'Gadgetron']]],
  ['nlcgsolver_3c_20cundarray_3c_20gadgetron_3a_3acomplext_20_3e_20_3e',['nlcgSolver&lt; cuNDArray&lt; Gadgetron::complext &gt; &gt;',['../class_gadgetron_1_1nlcg_solver.html',1,'Gadgetron']]],
  ['nlcgsolver_3c_20cundarray_3c_20t_20_3e_20_3e',['nlcgSolver&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1nlcg_solver.html',1,'Gadgetron']]],
  ['nlcgsolver_3c_20hocundarray_3c_20t_20_3e_20_3e',['nlcgSolver&lt; hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1nlcg_solver.html',1,'Gadgetron']]],
  ['node',['Node',['../structcrow_1_1_trie_1_1_node.html',1,'crow::Trie']]],
  ['noiseadj',['NoiseAdj',['../classtpat__snr__scale_1_1_noise_adj.html',1,'tpat_snr_scale']]],
  ['noiseadjustgadget',['NoiseAdjustGadget',['../class_gadgetron_1_1_noise_adjust_gadget.html',1,'Gadgetron']]],
  ['noiseadjustgadget_5funoptimized',['NoiseAdjustGadget_unoptimized',['../class_gadgetron_1_1_noise_adjust_gadget__unoptimized.html',1,'Gadgetron']]],
  ['noisecovarianceplottinggadget',['NoiseCovariancePlottingGadget',['../class_gadgetron_1_1_noise_covariance_plotting_gadget.html',1,'Gadgetron']]]
];
