var searchData=
[
  ['r_5fstring',['r_string',['../structcrow_1_1json_1_1detail_1_1r__string.html',1,'crow::json::detail']]],
  ['radialphasecorrectiongadget',['RadialPhaseCorrectionGadget',['../class_gadgetron_1_1_radial_phase_correction_gadget.html',1,'Gadgetron']]],
  ['radialsenseappmainwindow',['radialSenseAppMainWindow',['../classradial_sense_app_main_window.html',1,'']]],
  ['randnormgenerator',['RandNormGenerator',['../class_gadgetron_1_1_rand_norm_generator.html',1,'Gadgetron']]],
  ['reader',['Reader',['../struct_gadgetron_x_m_l_1_1_reader.html',1,'GadgetronXML']]],
  ['readoutbuffer',['ReadOutBuffer',['../struct_gadgetron_1_1_read_out_buffer.html',1,'Gadgetron']]],
  ['reald',['reald',['../struct_gadgetron_1_1reald.html',1,'Gadgetron']]],
  ['reald_3c_20float_2c_20d_20_3e',['reald&lt; float, D &gt;',['../struct_gadgetron_1_1reald.html',1,'Gadgetron']]],
  ['realtype',['realType',['../struct_gadgetron_1_1real_type.html',1,'Gadgetron']]],
  ['realtype_3c_20double_20_3e',['realType&lt; double &gt;',['../struct_gadgetron_1_1real_type_3_01double_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20double_5fcomplext_20_3e',['realType&lt; double_complext &gt;',['../struct_gadgetron_1_1real_type_3_01double__complext_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20element_5ftype_20_3e',['realType&lt; ELEMENT_TYPE &gt;',['../struct_gadgetron_1_1real_type.html',1,'Gadgetron']]],
  ['realtype_3c_20float_20_3e',['realType&lt; float &gt;',['../struct_gadgetron_1_1real_type_3_01float_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20float_5fcomplext_20_3e',['realType&lt; float_complext &gt;',['../struct_gadgetron_1_1real_type_3_01float__complext_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20gadgetron_3a_3acomplext_20_3e',['realType&lt; Gadgetron::complext &gt;',['../struct_gadgetron_1_1real_type.html',1,'Gadgetron']]],
  ['realtype_3c_20int_20_3e',['realType&lt; int &gt;',['../struct_gadgetron_1_1real_type_3_01int_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20short_20_3e',['realType&lt; short &gt;',['../struct_gadgetron_1_1real_type_3_01short_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20std_3a_3acomplex_3c_20double_20_3e_20_3e',['realType&lt; std::complex&lt; double &gt; &gt;',['../struct_gadgetron_1_1real_type_3_01std_1_1complex_3_01double_01_4_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e',['realType&lt; std::complex&lt; float &gt; &gt;',['../struct_gadgetron_1_1real_type_3_01std_1_1complex_3_01float_01_4_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20unsigned_20int_20_3e',['realType&lt; unsigned int &gt;',['../struct_gadgetron_1_1real_type_3_01unsigned_01int_01_4.html',1,'Gadgetron']]],
  ['realtype_3c_20unsigned_20short_20_3e',['realType&lt; unsigned short &gt;',['../struct_gadgetron_1_1real_type_3_01unsigned_01short_01_4.html',1,'Gadgetron']]],
  ['recon',['Recon',['../classtpat__snr__scale_1_1_recon.html',1,'tpat_snr_scale']]],
  ['reconwidget',['ReconWidget',['../class_recon_widget.html',1,'']]],
  ['registrationaveraginggadget',['RegistrationAveragingGadget',['../class_gadgetron_1_1_registration_averaging_gadget.html',1,'Gadgetron']]],
  ['registrationaveraginggadget_3c_20cundarray_3c_20float_20_3e_2c_202_20_3e',['RegistrationAveragingGadget&lt; cuNDArray&lt; float &gt;, 2 &gt;',['../class_gadgetron_1_1_registration_averaging_gadget.html',1,'Gadgetron']]],
  ['registrationaveraginggadget_3c_20hondarray_3c_20float_20_3e_2c_202_20_3e',['RegistrationAveragingGadget&lt; hoNDArray&lt; float &gt;, 2 &gt;',['../class_gadgetron_1_1_registration_averaging_gadget.html',1,'Gadgetron']]],
  ['registrationdata',['registrationData',['../class_gadgetron_1_1registration_data.html',1,'Gadgetron']]],
  ['registrationreconoperator',['registrationReconOperator',['../classregistration_recon_operator.html',1,'']]],
  ['registrationscatteringgadget',['RegistrationScatteringGadget',['../class_gadgetron_1_1_registration_scattering_gadget.html',1,'Gadgetron']]],
  ['registrationscatteringgadget_3c_20cundarray_3c_20float_20_3e_2c_202_20_3e',['RegistrationScatteringGadget&lt; cuNDArray&lt; float &gt;, 2 &gt;',['../class_gadgetron_1_1_registration_scattering_gadget.html',1,'Gadgetron']]],
  ['registrationsolver',['registrationSolver',['../class_gadgetron_1_1registration_solver.html',1,'Gadgetron']]],
  ['registrationsolver_3c_20array_5ftype_5freal_20_3e',['registrationSolver&lt; ARRAY_TYPE_REAL &gt;',['../class_gadgetron_1_1registration_solver.html',1,'Gadgetron']]],
  ['registrationsolver_3c_20cundarray_3c_20t_20_3e_20_3e',['registrationSolver&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1registration_solver.html',1,'Gadgetron']]],
  ['relativeresidualtcb',['relativeResidualTCB',['../class_gadgetron_1_1relative_residual_t_c_b.html',1,'Gadgetron']]],
  ['remos',['RemOS',['../classtpat__snr__scale_1_1_rem_o_s.html',1,'tpat_snr_scale']]],
  ['remove2xoversampling',['Remove2xOversampling',['../classremove__2x__oversampling_1_1_remove2x_oversampling.html',1,'remove_2x_oversampling']]],
  ['removerooversamplinggadget',['RemoveROOversamplingGadget',['../class_gadgetron_1_1_remove_r_o_oversampling_gadget.html',1,'Gadgetron']]],
  ['req_5fhandler_5fwrapper',['req_handler_wrapper',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1_wrapped_1_1req__handler__wrapper.html',1,'crow::detail::routing_handler_call_helper::Wrapped']]],
  ['request',['request',['../structcrow_1_1request.html',1,'crow']]],
  ['resampleoperator',['resampleOperator',['../class_gadgetron_1_1resample_operator.html',1,'Gadgetron']]],
  ['resampleoperator_3c_20cundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20cundarray_3c_20t_20_3e_20_3e',['resampleOperator&lt; cuNDArray&lt; realType&lt; T &gt;::Type &gt;, cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1resample_operator.html',1,'Gadgetron']]],
  ['resampleoperator_3c_20hondarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e_2c_20hondarray_3c_20t_20_3e_20_3e',['resampleOperator&lt; hoNDArray&lt; realType&lt; T &gt;::Type &gt;, hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1resample_operator.html',1,'Gadgetron']]],
  ['residualtcb',['residualTCB',['../class_gadgetron_1_1residual_t_c_b.html',1,'Gadgetron']]],
  ['response',['response',['../structcrow_1_1response.html',1,'crow']]],
  ['rest',['ReST',['../struct_gadgetron_x_m_l_1_1_re_s_t.html',1,'GadgetronXML']]],
  ['rest',['ReST',['../class_gadgetron_1_1_re_s_t.html',1,'Gadgetron']]],
  ['rgb_5ftype',['rgb_type',['../struct_gadgetron_1_1rgb__type.html',1,'Gadgetron']]],
  ['rgba_5ftype',['rgba_type',['../struct_gadgetron_1_1rgba__type.html',1,'Gadgetron']]],
  ['rmscoilcombine',['RMSCoilCombine',['../classrms__coil__combine_1_1_r_m_s_coil_combine.html',1,'rms_coil_combine']]],
  ['router',['Router',['../classcrow_1_1_router.html',1,'crow']]],
  ['routing_5fparams',['routing_params',['../structcrow_1_1routing__params.html',1,'crow']]],
  ['ruleparametertraits',['RuleParameterTraits',['../structcrow_1_1_rule_parameter_traits.html',1,'crow']]],
  ['ruleparametertraits_3c_20dynamicrule_20_3e',['RuleParameterTraits&lt; DynamicRule &gt;',['../structcrow_1_1_rule_parameter_traits.html',1,'crow']]],
  ['ruleparametertraits_3c_20taggedrule_3c_20args_2e_2e_2e_3e_20_3e',['RuleParameterTraits&lt; TaggedRule&lt; Args...&gt; &gt;',['../structcrow_1_1_rule_parameter_traits.html',1,'crow']]],
  ['runtime_5ferror',['runtime_error',['../class_gadgetron_1_1runtime__error.html',1,'Gadgetron']]],
  ['rvalue',['rvalue',['../classcrow_1_1json_1_1rvalue.html',1,'crow::json']]]
];
