var searchData=
[
  ['handler_5ftype_5fhelper',['handler_type_helper',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1_wrapped_1_1handler__type__helper.html',1,'crow::detail::routing_handler_call_helper::Wrapped']]],
  ['handler_5ftype_5fhelper_3c_20argswrapped_2e_2e_2e_3e',['handler_type_helper&lt; ArgsWrapped...&gt;',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1_wrapped_1_1handler__type__helper.html',1,'crow::detail::routing_handler_call_helper::Wrapped']]],
  ['handler_5ftype_5fhelper_3c_20const_20request_20_26_2c_20args_2e_2e_2e_3e',['handler_type_helper&lt; const request &amp;, Args...&gt;',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1_wrapped_1_1handler__type__helper_3_01176bac6491f2834cd36a05c30aa75bc3.html',1,'crow::detail::routing_handler_call_helper::Wrapped']]],
  ['handler_5ftype_5fhelper_3c_20const_20request_20_26_2c_20response_20_26_2c_20args_2e_2e_2e_3e',['handler_type_helper&lt; const request &amp;, response &amp;, Args...&gt;',['../structcrow_1_1detail_1_1routing__handler__call__helper_1_1_wrapped_1_1handler__type__helper_3_01506e35faa94646c63b5476ce8ce1df0a.html',1,'crow::detail::routing_handler_call_helper::Wrapped']]],
  ['harr_5fwav_5f',['harr_wav_',['../class_gadgetron_1_1ho_wavelet_operator.html#a9422c370eae9b4476633a507e7bf5498',1,'Gadgetron::hoWaveletOperator']]],
  ['has_5fidentical_5fdimensions',['has_identical_dimensions',['../class_gadgetron_1_1ho_n_d_image_container2_d.html#a83f2f0d042b434f5ec80848977f69e79',1,'Gadgetron::hoNDImageContainer2D']]],
  ['header_5fkey',['header_key',['../structheader__key.html',1,'']]],
  ['heev',['heev',['../namespace_gadgetron.html#a7bc6ffd078761c2422735997ed6031d8',1,'Gadgetron']]],
  ['herk',['herk',['../namespace_gadgetron.html#a71628fbf601596b83df53beb598dceeb',1,'Gadgetron']]],
  ['hesv',['hesv',['../namespace_gadgetron.html#ab9af50ad59472872ea0f6e26dd641644',1,'Gadgetron']]],
  ['hist_5f',['hist_',['../class_gadgetron_1_1ho_image_reg_dissimilarity_histogram_based.html#a40bd1ee91a4dd57a41e6d8943817fa5d',1,'Gadgetron::hoImageRegDissimilarityHistogramBased']]],
  ['ho2darray',['ho2DArray',['../class_gadgetron_1_1ho2_d_array.html',1,'Gadgetron']]],
  ['ho2darray_3c_20hist_5fvalue_5ftype_20_3e',['ho2DArray&lt; hist_value_type &gt;',['../class_gadgetron_1_1ho2_d_array.html',1,'Gadgetron']]],
  ['ho2darray_3c_20valuetype_20_3e',['ho2DArray&lt; ValueType &gt;',['../class_gadgetron_1_1ho2_d_array.html',1,'Gadgetron']]],
  ['ho3darray',['ho3DArray',['../class_gadgetron_1_1ho3_d_array.html',1,'Gadgetron']]],
  ['ho4darray',['ho4DArray',['../class_gadgetron_1_1ho4_d_array.html',1,'Gadgetron']]],
  ['ho5darray',['ho5DArray',['../class_gadgetron_1_1ho5_d_array.html',1,'Gadgetron']]],
  ['ho6darray',['ho6DArray',['../class_gadgetron_1_1ho6_d_array.html',1,'Gadgetron']]],
  ['ho7darray',['ho7DArray',['../class_gadgetron_1_1ho7_d_array.html',1,'Gadgetron']]],
  ['hocgpreconditioner',['hoCgPreconditioner',['../class_gadgetron_1_1ho_cg_preconditioner.html',1,'Gadgetron']]],
  ['hocgsolver',['hoCgSolver',['../class_gadgetron_1_1ho_cg_solver.html',1,'Gadgetron']]],
  ['hocgsolver_2eh',['hoCgSolver.h',['../ho_cg_solver_8h.html',1,'']]],
  ['hockopticalflowsolver',['hoCKOpticalFlowSolver',['../class_gadgetron_1_1ho_c_k_optical_flow_solver.html',1,'Gadgetron']]],
  ['hockopticalflowsolver_2eh',['hoCKOpticalFlowSolver.h',['../ho_c_k_optical_flow_solver_8h.html',1,'']]],
  ['hocompascending',['hoCompAscending',['../struct_gadgetron_1_1ho_comp_ascending.html',1,'Gadgetron']]],
  ['hocompdescending',['hoCompDescending',['../struct_gadgetron_1_1ho_comp_descending.html',1,'Gadgetron']]],
  ['hocucgsolver',['hoCuCgSolver',['../class_gadgetron_1_1ho_cu_cg_solver.html',1,'Gadgetron']]],
  ['hocuconebeamprojectionoperator',['hoCuConebeamProjectionOperator',['../class_gadgetron_1_1ho_cu_conebeam_projection_operator.html',1,'Gadgetron']]],
  ['hocudiagonaloperator',['hoCuDiagonalOperator',['../class_gadgetron_1_1ho_cu_diagonal_operator.html',1,'Gadgetron']]],
  ['hocudiagonaloperator_2eh',['hoCuDiagonalOperator.h',['../ho_cu_diagonal_operator_8h.html',1,'']]],
  ['hocuencodingoperatorcontainer',['hoCuEncodingOperatorContainer',['../class_gadgetron_1_1ho_cu_encoding_operator_container.html',1,'Gadgetron']]],
  ['hocugpbbsolver',['hoCuGpBbSolver',['../class_gadgetron_1_1ho_cu_gp_bb_solver.html',1,'Gadgetron']]],
  ['hocuidentityoperator',['hoCuIdentityOperator',['../class_gadgetron_1_1ho_cu_identity_operator.html',1,'Gadgetron']]],
  ['hocuidentityoperator_2eh',['hoCuIdentityOperator.h',['../ho_cu_identity_operator_8h.html',1,'']]],
  ['hocundarray',['hoCuNDArray',['../class_gadgetron_1_1ho_cu_n_d_array.html',1,'Gadgetron']]],
  ['hocundarray_3c_20realtype_3c_20float_20_3e_3a_3atype_20_3e',['hoCuNDArray&lt; realType&lt; float &gt;::Type &gt;',['../class_gadgetron_1_1ho_cu_n_d_array.html',1,'Gadgetron']]],
  ['hocundarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e',['hoCuNDArray&lt; realType&lt; T &gt;::Type &gt;',['../class_gadgetron_1_1ho_cu_n_d_array.html',1,'Gadgetron']]],
  ['hocundarray_5felemwise_2eh',['hoCuNDArray_elemwise.h',['../ho_cu_n_d_array__elemwise_8h.html',1,'']]],
  ['hocunlcgsolver',['hoCuNlcgSolver',['../class_gadgetron_1_1ho_cu_nlcg_solver.html',1,'Gadgetron']]],
  ['hocuofconebeamprojectionoperator',['hoCuOFConebeamProjectionOperator',['../class_gadgetron_1_1ho_cu_o_f_conebeam_projection_operator.html',1,'Gadgetron']]],
  ['hocuoperator',['hoCuOperator',['../class_gadgetron_1_1ho_cu_operator.html',1,'Gadgetron']]],
  ['hocupartialderivativeoperator',['hoCuPartialDerivativeOperator',['../class_gadgetron_1_1ho_cu_partial_derivative_operator.html',1,'Gadgetron']]],
  ['hocusbccgsolver',['hoCuSbcCgSolver',['../class_gadgetron_1_1ho_cu_sbc_cg_solver.html',1,'Gadgetron']]],
  ['hocusbccgsolver_3c_20float_20_3e',['hoCuSbcCgSolver&lt; float &gt;',['../class_gadgetron_1_1ho_cu_sbc_cg_solver.html',1,'Gadgetron']]],
  ['hocutvoperator',['hoCuTvOperator',['../class_gadgetron_1_1ho_cu_tv_operator.html',1,'Gadgetron']]],
  ['hocutvpicsoperator',['hoCuTvPicsOperator',['../class_gadgetron_1_1ho_cu_tv_pics_operator.html',1,'Gadgetron']]],
  ['hodiagonaloperator',['hoDiagonalOperator',['../class_gadgetron_1_1ho_diagonal_operator.html',1,'Gadgetron']]],
  ['hodiagonaloperator_2eh',['hoDiagonalOperator.h',['../ho_diagonal_operator_8h.html',1,'']]],
  ['hodiagonalsumoperator',['hoDiagonalSumOperator',['../class_gadgetron_1_1ho_diagonal_sum_operator.html',1,'Gadgetron']]],
  ['hodiagonalsumoperator_2eh',['hoDiagonalSumOperator.h',['../ho_diagonal_sum_operator_8h.html',1,'']]],
  ['hofftoperator',['hoFFTOperator',['../class_gadgetron_1_1ho_f_f_t_operator.html',1,'Gadgetron']]],
  ['hofftoperator_2eh',['hoFFTOperator.h',['../ho_f_f_t_operator_8h.html',1,'']]],
  ['hogpbbsolver',['hoGpBbSolver',['../class_gadgetron_1_1ho_gp_bb_solver.html',1,'Gadgetron']]],
  ['hohsopticalflowsolver',['hoHSOpticalFlowSolver',['../class_gadgetron_1_1ho_h_s_optical_flow_solver.html',1,'Gadgetron']]],
  ['hohsopticalflowsolver_2eh',['hoHSOpticalFlowSolver.h',['../ho_h_s_optical_flow_solver_8h.html',1,'']]],
  ['hoidentityoperator',['hoIdentityOperator',['../class_gadgetron_1_1ho_identity_operator.html',1,'Gadgetron']]],
  ['hoidentityoperator_2eh',['hoIdentityOperator.h',['../ho_identity_operator_8h.html',1,'']]],
  ['hoimageoperator',['hoImageOperator',['../class_gadgetron_1_1ho_image_operator.html',1,'Gadgetron']]],
  ['hoimageoperator_2eh',['hoImageOperator.h',['../ho_image_operator_8h.html',1,'']]],
  ['hoimageregcontainer2dregistration',['hoImageRegContainer2DRegistration',['../class_gadgetron_1_1ho_image_reg_container2_d_registration.html',1,'Gadgetron']]],
  ['hoimageregcontainer2dregistration_2eh',['hoImageRegContainer2DRegistration.h',['../ho_image_reg_container2_d_registration_8h.html',1,'']]],
  ['hoimageregdeformationfield',['hoImageRegDeformationField',['../class_gadgetron_1_1ho_image_reg_deformation_field.html',1,'Gadgetron']]],
  ['hoimageregdeformationfield_2eh',['hoImageRegDeformationField.h',['../ho_image_reg_deformation_field_8h.html',1,'']]],
  ['hoimageregdeformationfieldbidirectionalregister',['hoImageRegDeformationFieldBidirectionalRegister',['../class_gadgetron_1_1ho_image_reg_deformation_field_bidirectional_register.html',1,'Gadgetron']]],
  ['hoimageregdeformationfieldbidirectionalregister_2eh',['hoImageRegDeformationFieldBidirectionalRegister.h',['../ho_image_reg_deformation_field_bidirectional_register_8h.html',1,'']]],
  ['hoimageregdeformationfieldbidirectionalsolver',['hoImageRegDeformationFieldBidirectionalSolver',['../class_gadgetron_1_1ho_image_reg_deformation_field_bidirectional_solver.html',1,'Gadgetron']]],
  ['hoimageregdeformationfieldbidirectionalsolver_2eh',['hoImageRegDeformationFieldBidirectionalSolver.h',['../ho_image_reg_deformation_field_bidirectional_solver_8h.html',1,'']]],
  ['hoimageregdeformationfieldregister',['hoImageRegDeformationFieldRegister',['../class_gadgetron_1_1ho_image_reg_deformation_field_register.html',1,'Gadgetron']]],
  ['hoimageregdeformationfieldregister_2eh',['hoImageRegDeformationFieldRegister.h',['../ho_image_reg_deformation_field_register_8h.html',1,'']]],
  ['hoimageregdeformationfieldsolver',['hoImageRegDeformationFieldSolver',['../class_gadgetron_1_1ho_image_reg_deformation_field_solver.html',1,'Gadgetron']]],
  ['hoimageregdeformationfieldsolver_2eh',['hoImageRegDeformationFieldSolver.h',['../ho_image_reg_deformation_field_solver_8h.html',1,'']]],
  ['hoimageregdissimilarity',['hoImageRegDissimilarity',['../class_gadgetron_1_1ho_image_reg_dissimilarity.html',1,'Gadgetron']]],
  ['hoimageregdissimilarity_2eh',['hoImageRegDissimilarity.h',['../ho_image_reg_dissimilarity_8h.html',1,'']]],
  ['hoimageregdissimilarityhistogrambased',['hoImageRegDissimilarityHistogramBased',['../class_gadgetron_1_1ho_image_reg_dissimilarity_histogram_based.html',1,'Gadgetron']]],
  ['hoimageregdissimilarityhistogrambased_2eh',['hoImageRegDissimilarityHistogramBased.h',['../ho_image_reg_dissimilarity_histogram_based_8h.html',1,'']]],
  ['hoimageregdissimilaritylocalccr',['hoImageRegDissimilarityLocalCCR',['../class_gadgetron_1_1ho_image_reg_dissimilarity_local_c_c_r.html',1,'Gadgetron']]],
  ['hoimageregdissimilaritylocalccr_2eh',['hoImageRegDissimilarityLocalCCR.h',['../ho_image_reg_dissimilarity_local_c_c_r_8h.html',1,'']]],
  ['hoimageregdissimilaritymutualinformation',['hoImageRegDissimilarityMutualInformation',['../class_gadgetron_1_1ho_image_reg_dissimilarity_mutual_information.html',1,'Gadgetron']]],
  ['hoimageregdissimilaritymutualinformation_2eh',['hoImageRegDissimilarityMutualInformation.h',['../ho_image_reg_dissimilarity_mutual_information_8h.html',1,'']]],
  ['hoimageregdissimilaritynormalizedmutualinformation',['hoImageRegDissimilarityNormalizedMutualInformation',['../class_gadgetron_1_1ho_image_reg_dissimilarity_normalized_mutual_information.html',1,'Gadgetron']]],
  ['hoimageregdissimilaritynormalizedmutualinformation_2eh',['hoImageRegDissimilarityNormalizedMutualInformation.h',['../ho_image_reg_dissimilarity_normalized_mutual_information_8h.html',1,'']]],
  ['hoimageregdissimilarityssd',['hoImageRegDissimilaritySSD',['../class_gadgetron_1_1ho_image_reg_dissimilarity_s_s_d.html',1,'Gadgetron']]],
  ['hoimageregdissimilarityssd_2eh',['hoImageRegDissimilaritySSD.h',['../ho_image_reg_dissimilarity_s_s_d_8h.html',1,'']]],
  ['hoimagereghomogenoustransformation',['hoImageRegHomogenousTransformation',['../class_gadgetron_1_1ho_image_reg_homogenous_transformation.html',1,'Gadgetron']]],
  ['hoimagereghomogenoustransformation_2eh',['hoImageRegHomogenousTransformation.h',['../ho_image_reg_homogenous_transformation_8h.html',1,'']]],
  ['hoimagereghomogenoustransformation_3c_20valuetype_2c_202_20_3e',['hoImageRegHomogenousTransformation&lt; ValueType, 2 &gt;',['../class_gadgetron_1_1ho_image_reg_homogenous_transformation.html',1,'Gadgetron']]],
  ['hoimagereghomogenoustransformation_3c_20valuetype_2c_203_20_3e',['hoImageRegHomogenousTransformation&lt; ValueType, 3 &gt;',['../class_gadgetron_1_1ho_image_reg_homogenous_transformation.html',1,'Gadgetron']]],
  ['hoimageregnonparametricregister',['hoImageRegNonParametricRegister',['../class_gadgetron_1_1ho_image_reg_non_parametric_register.html',1,'Gadgetron']]],
  ['hoimageregnonparametricregister_2eh',['hoImageRegNonParametricRegister.h',['../ho_image_reg_non_parametric_register_8h.html',1,'']]],
  ['hoimageregnonparametricregister_3c_20valuetype_2c_20coordtype_2c_20d_2c_20d_20_3e',['hoImageRegNonParametricRegister&lt; ValueType, CoordType, D, D &gt;',['../class_gadgetron_1_1ho_image_reg_non_parametric_register.html',1,'Gadgetron']]],
  ['hoimageregnonparametricsolver',['hoImageRegNonParametricSolver',['../class_gadgetron_1_1ho_image_reg_non_parametric_solver.html',1,'Gadgetron']]],
  ['hoimageregnonparametricsolver_2eh',['hoImageRegNonParametricSolver.h',['../ho_image_reg_non_parametric_solver_8h.html',1,'']]],
  ['hoimageregnonparametricsolver_3c_20valuetype_2c_20coordtype_2c_20d_2c_20d_20_3e',['hoImageRegNonParametricSolver&lt; ValueType, CoordType, D, D &gt;',['../class_gadgetron_1_1ho_image_reg_non_parametric_solver.html',1,'Gadgetron']]],
  ['hoimageregnonparametrictransformation',['hoImageRegNonParametricTransformation',['../class_gadgetron_1_1ho_image_reg_non_parametric_transformation.html',1,'Gadgetron']]],
  ['hoimageregnonparametrictransformation_2eh',['hoImageRegNonParametricTransformation.h',['../ho_image_reg_non_parametric_transformation_8h.html',1,'']]],
  ['hoimageregnonparametrictransformation_3c_20valuetype_2c_20d_2c_20d_20_3e',['hoImageRegNonParametricTransformation&lt; ValueType, D, D &gt;',['../class_gadgetron_1_1ho_image_reg_non_parametric_transformation.html',1,'Gadgetron']]],
  ['hoimageregparametricdownhillsolver',['hoImageRegParametricDownHillSolver',['../class_gadgetron_1_1ho_image_reg_parametric_down_hill_solver.html',1,'Gadgetron']]],
  ['hoimageregparametricdownhillsolver_2eh',['hoImageRegParametricDownHillSolver.h',['../ho_image_reg_parametric_down_hill_solver_8h.html',1,'']]],
  ['hoimageregparametricgradientdescentsolver',['hoImageRegParametricGradientDescentSolver',['../class_gadgetron_1_1ho_image_reg_parametric_gradient_descent_solver.html',1,'Gadgetron']]],
  ['hoimageregparametricgradientdescentsolver_2eh',['hoImageRegParametricGradientDescentSolver.h',['../ho_image_reg_parametric_gradient_descent_solver_8h.html',1,'']]],
  ['hoimageregparametricregister',['hoImageRegParametricRegister',['../class_gadgetron_1_1ho_image_reg_parametric_register.html',1,'Gadgetron']]],
  ['hoimageregparametricregister_2eh',['hoImageRegParametricRegister.h',['../ho_image_reg_parametric_register_8h.html',1,'']]],
  ['hoimageregparametricsolver',['hoImageRegParametricSolver',['../class_gadgetron_1_1ho_image_reg_parametric_solver.html',1,'Gadgetron']]],
  ['hoimageregparametricsolver_2eh',['hoImageRegParametricSolver.h',['../ho_image_reg_parametric_solver_8h.html',1,'']]],
  ['hoimageregparametrictransformation',['hoImageRegParametricTransformation',['../class_gadgetron_1_1ho_image_reg_parametric_transformation.html',1,'Gadgetron']]],
  ['hoimageregparametrictransformation_2eh',['hoImageRegParametricTransformation.h',['../ho_image_reg_parametric_transformation_8h.html',1,'']]],
  ['hoimageregparametrictransformation_3c_20valuetype_2c_20d_2c_20d_20_3e',['hoImageRegParametricTransformation&lt; ValueType, D, D &gt;',['../class_gadgetron_1_1ho_image_reg_parametric_transformation.html',1,'Gadgetron']]],
  ['hoimageregregister',['hoImageRegRegister',['../class_gadgetron_1_1ho_image_reg_register.html',1,'Gadgetron']]],
  ['hoimageregregister_2eh',['hoImageRegRegister.h',['../ho_image_reg_register_8h.html',1,'']]],
  ['hoimageregrigid2dtransformation',['hoImageRegRigid2DTransformation',['../class_gadgetron_1_1ho_image_reg_rigid2_d_transformation.html',1,'Gadgetron']]],
  ['hoimageregrigid2dtransformation_2eh',['hoImageRegRigid2DTransformation.h',['../ho_image_reg_rigid2_d_transformation_8h.html',1,'']]],
  ['hoimageregrigid3dtransformation',['hoImageRegRigid3DTransformation',['../class_gadgetron_1_1ho_image_reg_rigid3_d_transformation.html',1,'Gadgetron']]],
  ['hoimageregrigid3dtransformation_2eh',['hoImageRegRigid3DTransformation.h',['../ho_image_reg_rigid3_d_transformation_8h.html',1,'']]],
  ['hoimageregsolver',['hoImageRegSolver',['../class_gadgetron_1_1ho_image_reg_solver.html',1,'Gadgetron']]],
  ['hoimageregsolver_2eh',['hoImageRegSolver.h',['../ho_image_reg_solver_8h.html',1,'']]],
  ['hoimageregtransformation',['hoImageRegTransformation',['../class_gadgetron_1_1ho_image_reg_transformation.html',1,'Gadgetron']]],
  ['hoimageregtransformation_2eh',['hoImageRegTransformation.h',['../ho_image_reg_transformation_8h.html',1,'']]],
  ['hoimageregwarper',['hoImageRegWarper',['../class_gadgetron_1_1ho_image_reg_warper.html',1,'Gadgetron']]],
  ['hoimageregwarper_2eh',['hoImageRegWarper.h',['../ho_image_reg_warper_8h.html',1,'']]],
  ['holinearresampleoperator',['hoLinearResampleOperator',['../class_gadgetron_1_1ho_linear_resample_operator.html',1,'Gadgetron']]],
  ['holinearresampleoperator_5feigen',['hoLinearResampleOperator_eigen',['../class_gadgetron_1_1ho_linear_resample_operator__eigen.html',1,'Gadgetron']]],
  ['holsqrsolver',['hoLsqrSolver',['../class_gadgetron_1_1ho_lsqr_solver.html',1,'Gadgetron']]],
  ['holsqrsolver_2eh',['hoLsqrSolver.h',['../ho_lsqr_solver_8h.html',1,'']]],
  ['homatrix',['hoMatrix',['../class_gadgetron_1_1ho_matrix.html',1,'Gadgetron']]],
  ['homatrix_3c_20hist_5fvalue_5ftype_20_3e',['hoMatrix&lt; hist_value_type &gt;',['../class_gadgetron_1_1ho_matrix.html',1,'Gadgetron']]],
  ['homatrix_3c_20valuetype_20_3e',['hoMatrix&lt; ValueType &gt;',['../class_gadgetron_1_1ho_matrix.html',1,'Gadgetron']]],
  ['homatrixreal',['hoMatrixReal',['../class_gadgetron_1_1ho_matrix_real.html',1,'Gadgetron']]],
  ['homotioncompensation2dtoperator',['hoMotionCompensation2DTOperator',['../class_gadgetron_1_1ho_motion_compensation2_d_t_operator.html',1,'Gadgetron']]],
  ['homotioncompensation2dtoperator_2eh',['hoMotionCompensation2DTOperator.h',['../ho_motion_compensation2_d_t_operator_8h.html',1,'']]],
  ['homotioncompensation2dtoperator_3c_20t_2c_20float_20_3e',['hoMotionCompensation2DTOperator&lt; T, float &gt;',['../class_gadgetron_1_1ho_motion_compensation2_d_t_operator.html',1,'Gadgetron']]],
  ['honda_5fclamp',['hoNDA_clamp',['../struct_gadgetron_1_1ho_n_d_a__clamp.html',1,'Gadgetron']]],
  ['honda_5fclamp_3c_20complext_3c_20t_20_3e_20_3e',['hoNDA_clamp&lt; complext&lt; T &gt; &gt;',['../struct_gadgetron_1_1ho_n_d_a__clamp_3_01complext_3_01_t_01_4_01_4.html',1,'Gadgetron']]],
  ['honda_5fclamp_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['hoNDA_clamp&lt; std::complex&lt; T &gt; &gt;',['../struct_gadgetron_1_1ho_n_d_a__clamp_3_01std_1_1complex_3_01_t_01_4_01_4.html',1,'Gadgetron']]],
  ['honda_5fclamp_5fmax',['hoNDA_clamp_max',['../struct_gadgetron_1_1ho_n_d_a__clamp__max.html',1,'Gadgetron']]],
  ['honda_5fclamp_5fmax_3c_20complext_3c_20t_20_3e_20_3e',['hoNDA_clamp_max&lt; complext&lt; T &gt; &gt;',['../struct_gadgetron_1_1ho_n_d_a__clamp__max_3_01complext_3_01_t_01_4_01_4.html',1,'Gadgetron']]],
  ['honda_5fclamp_5fmax_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['hoNDA_clamp_max&lt; std::complex&lt; T &gt; &gt;',['../struct_gadgetron_1_1ho_n_d_a__clamp__max_3_01std_1_1complex_3_01_t_01_4_01_4.html',1,'Gadgetron']]],
  ['honda_5fclamp_5fmin',['hoNDA_clamp_min',['../struct_gadgetron_1_1ho_n_d_a__clamp__min.html',1,'Gadgetron']]],
  ['honda_5fclamp_5fmin_3c_20complext_3c_20t_20_3e_20_3e',['hoNDA_clamp_min&lt; complext&lt; T &gt; &gt;',['../struct_gadgetron_1_1ho_n_d_a__clamp__min_3_01complext_3_01_t_01_4_01_4.html',1,'Gadgetron']]],
  ['honda_5fclamp_5fmin_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['hoNDA_clamp_min&lt; std::complex&lt; T &gt; &gt;',['../struct_gadgetron_1_1ho_n_d_a__clamp__min_3_01std_1_1complex_3_01_t_01_4_01_4.html',1,'Gadgetron']]],
  ['hondarray',['hoNDArray',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_2eh',['hoNDArray.h',['../ho_n_d_array_8h.html',1,'']]],
  ['hondarray_3c_20computing_5fvalue_5ftype_20_3e',['hoNDArray&lt; computing_value_type &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20coordtype_20_3e',['hoNDArray&lt; CoordType &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20float_20_3e',['hoNDArray&lt; float &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20hist_5fvalue_5ftype_20_3e',['hoNDArray&lt; hist_value_type &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20ismrmrd_3a_3aacquisitionheader_20_3e',['hoNDArray&lt; ISMRMRD::AcquisitionHeader &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20ismrmrd_3a_3aimageheader_20_3e',['hoNDArray&lt; ISMRMRD::ImageHeader &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20real_5fvalue_5ftype_20_3e',['hoNDArray&lt; real_value_type &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20realtype_3c_20float_20_3e_3a_3atype_20_3e',['hoNDArray&lt; realType&lt; float &gt;::Type &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20realtype_3c_20t_20_3e_3a_3atype_20_3e',['hoNDArray&lt; realType&lt; T &gt;::Type &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20std_3a_3acomplex_3c_20double_20_3e_20_3e',['hoNDArray&lt; std::complex&lt; double &gt; &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e',['hoNDArray&lt; std::complex&lt; float &gt; &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['hoNDArray&lt; std::complex&lt; T &gt; &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20tobjecttype_20_2a_20_3e',['hoNDArray&lt; TObjectType * &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20typename_20gadgetron_3a_3arealtype_3c_20t_20_3e_3a_3atype_20_3e',['hoNDArray&lt; typename Gadgetron::realType&lt; T &gt;::Type &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20unsigned_20short_20_3e',['hoNDArray&lt; unsigned short &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20value_5ftype_20_3e',['hoNDArray&lt; value_type &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_3c_20valuetype_20_3e',['hoNDArray&lt; ValueType &gt;',['../class_gadgetron_1_1ho_n_d_array.html',1,'Gadgetron']]],
  ['hondarray_5felemwise_2eh',['hoNDArray_elemwise.h',['../ho_n_d_array__elemwise_8h.html',1,'']]],
  ['hondarray_5ffrom_5fnumpy_5farray',['hoNDArray_from_numpy_array',['../struct_gadgetron_1_1ho_n_d_array__from__numpy__array.html',1,'Gadgetron']]],
  ['hondarray_5ffrom_5fnumpy_5farray_3c_20ismrmrd_3a_3aacquisitionheader_20_3e',['hoNDArray_from_numpy_array&lt; ISMRMRD::AcquisitionHeader &gt;',['../struct_gadgetron_1_1ho_n_d_array__from__numpy__array_3_01_i_s_m_r_m_r_d_1_1_acquisition_header_01_4.html',1,'Gadgetron']]],
  ['hondarray_5fmath_5futil_2eh',['hoNDArray_math_util.h',['../ho_n_d_array__math__util_8h.html',1,'']]],
  ['hondarray_5fto_5fnumpy_5farray',['hoNDArray_to_numpy_array',['../struct_gadgetron_1_1ho_n_d_array__to__numpy__array.html',1,'Gadgetron']]],
  ['hondarray_5fto_5fnumpy_5farray_3c_20ismrmrd_3a_3aacquisitionheader_20_3e',['hoNDArray_to_numpy_array&lt; ISMRMRD::AcquisitionHeader &gt;',['../struct_gadgetron_1_1ho_n_d_array__to__numpy__array_3_01_i_s_m_r_m_r_d_1_1_acquisition_header_01_4.html',1,'Gadgetron']]],
  ['hondarraytomatlab',['hoNDArrayToMatlab',['../namespace_gadgetron.html#a6abe4856997a6254a9411f8708ecd79a',1,'Gadgetron']]],
  ['hondboundaryhandler',['hoNDBoundaryHandler',['../class_gadgetron_1_1ho_n_d_boundary_handler.html',1,'Gadgetron']]],
  ['hondboundaryhandler_2eh',['hoNDBoundaryHandler.h',['../ho_n_d_boundary_handler_8h.html',1,'']]],
  ['hondboundaryhandler_2ehxx',['hoNDBoundaryHandler.hxx',['../ho_n_d_boundary_handler_8hxx.html',1,'']]],
  ['hondboundaryhandlerbordervalue',['hoNDBoundaryHandlerBorderValue',['../class_gadgetron_1_1ho_n_d_boundary_handler_border_value.html',1,'Gadgetron']]],
  ['hondboundaryhandlerfixedvalue',['hoNDBoundaryHandlerFixedValue',['../class_gadgetron_1_1ho_n_d_boundary_handler_fixed_value.html',1,'Gadgetron']]],
  ['hondboundaryhandlermirror',['hoNDBoundaryHandlerMirror',['../class_gadgetron_1_1ho_n_d_boundary_handler_mirror.html',1,'Gadgetron']]],
  ['hondboundaryhandlerperiodic',['hoNDBoundaryHandlerPeriodic',['../class_gadgetron_1_1ho_n_d_boundary_handler_periodic.html',1,'Gadgetron']]],
  ['hondbspline',['hoNDBSpline',['../class_gadgetron_1_1ho_n_d_b_spline.html',1,'Gadgetron']]],
  ['hondbspline_2eh',['hoNDBSpline.h',['../ho_n_d_b_spline_8h.html',1,'']]],
  ['hondbspline_2ehxx',['hoNDBSpline.hxx',['../ho_n_d_b_spline_8hxx.html',1,'']]],
  ['hondfft',['hoNDFFT',['../class_gadgetron_1_1ho_n_d_f_f_t.html',1,'Gadgetron']]],
  ['hondfft_2eh',['hoNDFFT.h',['../ho_n_d_f_f_t_8h.html',1,'']]],
  ['hondharrwavelet',['hoNDHarrWavelet',['../class_gadgetron_1_1ho_n_d_harr_wavelet.html',1,'Gadgetron']]],
  ['hondharrwavelet_2eh',['hoNDHarrWavelet.h',['../ho_n_d_harr_wavelet_8h.html',1,'']]],
  ['hondimage',['hoNDImage',['../class_gadgetron_1_1ho_n_d_image.html#acf90dca9a96d8559f5a71775efec111b',1,'Gadgetron::hoNDImage::hoNDImage()'],['../class_gadgetron_1_1ho_n_d_image.html#a6f35d4c614a36285d948ae29601f89bc',1,'Gadgetron::hoNDImage::hoNDImage(const std::vector&lt; size_t &gt; &amp;dimensions, T *data, bool delete_data_on_destruct=false)']]],
  ['hondimage',['hoNDImage',['../class_gadgetron_1_1ho_n_d_image.html',1,'Gadgetron']]],
  ['hondimage_2eh',['hoNDImage.h',['../ho_n_d_image_8h.html',1,'']]],
  ['hondimage_2ehxx',['hoNDImage.hxx',['../ho_n_d_image_8hxx.html',1,'']]],
  ['hondimage_3c_20t_2c_20din_20_3e',['hoNDImage&lt; T, DIn &gt;',['../class_gadgetron_1_1ho_n_d_image.html',1,'Gadgetron']]],
  ['hondimage_3c_20valuetype_2c_20d_20_3e',['hoNDImage&lt; ValueType, D &gt;',['../class_gadgetron_1_1ho_n_d_image.html',1,'Gadgetron']]],
  ['hondimage_3c_20valuetype_2c_20dout_20_3e',['hoNDImage&lt; ValueType, DOut &gt;',['../class_gadgetron_1_1ho_n_d_image.html',1,'Gadgetron']]],
  ['hondimage_5futil_2eh',['hoNDImage_util.h',['../ho_n_d_image__util_8h.html',1,'']]],
  ['hondimage_5futil_2ehxx',['hoNDImage_util.hxx',['../ho_n_d_image__util_8hxx.html',1,'']]],
  ['hondimageattrib',['hoNDImageAttrib',['../class_gadgetron_1_1ho_n_d_image_attrib.html',1,'Gadgetron']]],
  ['hondimageattrib',['hoNDImageAttrib',['../class_gadgetron_1_1ho_n_d_image_attrib.html#a42a95011ba8cc07a712d5de82a73beab',1,'Gadgetron::hoNDImageAttrib::hoNDImageAttrib()'],['../class_gadgetron_1_1ho_n_d_image_attrib.html#abc8ad1b84455443dd033091e7f2306d1',1,'Gadgetron::hoNDImageAttrib::hoNDImageAttrib(const std::vector&lt; size_t &gt; &amp;dimensions, T *data, bool delete_data_on_destruct=false)']]],
  ['hondimageattrib_2eh',['hoNDImageAttrib.h',['../ho_n_d_image_attrib_8h.html',1,'']]],
  ['hondimagecontainer2d',['hoNDImageContainer2D',['../class_gadgetron_1_1ho_n_d_image_container2_d.html',1,'Gadgetron']]],
  ['hondimagecontainer2d',['hoNDImageContainer2D',['../class_gadgetron_1_1ho_n_d_image_container2_d.html#a1a7df598e48a5ea43abcf3d51bb205ec',1,'Gadgetron::hoNDImageContainer2D']]],
  ['hondimagecontainer2d_2eh',['hoNDImageContainer2D.h',['../ho_n_d_image_container2_d_8h.html',1,'']]],
  ['hondimagecontainer2d_3c_20deformationfieldtype_20_3e',['hoNDImageContainer2D&lt; DeformationFieldType &gt;',['../class_gadgetron_1_1ho_n_d_image_container2_d.html',1,'Gadgetron']]],
  ['hondimagecontainer2d_3c_20targettype_20_3e',['hoNDImageContainer2D&lt; TargetType &gt;',['../class_gadgetron_1_1ho_n_d_image_container2_d.html',1,'Gadgetron']]],
  ['hondinterpolator',['hoNDInterpolator',['../class_gadgetron_1_1ho_n_d_interpolator.html',1,'Gadgetron']]],
  ['hondinterpolator_2eh',['hoNDInterpolator.h',['../ho_n_d_interpolator_8h.html',1,'']]],
  ['hondinterpolatorbspline',['hoNDInterpolatorBSpline',['../class_gadgetron_1_1ho_n_d_interpolator_b_spline.html',1,'Gadgetron']]],
  ['hondinterpolatorbspline_2ehxx',['hoNDInterpolatorBSpline.hxx',['../ho_n_d_interpolator_b_spline_8hxx.html',1,'']]],
  ['hondinterpolatorlinear',['hoNDInterpolatorLinear',['../class_gadgetron_1_1ho_n_d_interpolator_linear.html',1,'Gadgetron']]],
  ['hondinterpolatornearestneighbor',['hoNDInterpolatorNearestNeighbor',['../class_gadgetron_1_1ho_n_d_interpolator_nearest_neighbor.html',1,'Gadgetron']]],
  ['hondklt',['hoNDKLT',['../class_gadgetron_1_1ho_n_d_k_l_t.html',1,'Gadgetron']]],
  ['hondklt_2eh',['hoNDKLT.h',['../ho_n_d_k_l_t_8h.html',1,'']]],
  ['hondobjectarray',['hoNDObjectArray',['../class_gadgetron_1_1ho_n_d_object_array.html',1,'Gadgetron']]],
  ['hondobjectarray_2eh',['hoNDObjectArray.h',['../ho_n_d_object_array_8h.html',1,'']]],
  ['hondpoint',['hoNDPoint',['../class_gadgetron_1_1ho_n_d_point.html',1,'Gadgetron']]],
  ['hondpoint_2eh',['hoNDPoint.h',['../ho_n_d_point_8h.html',1,'']]],
  ['hondpoint_3c_20coord_5ftype_2c_203_20_3e',['hoNDPoint&lt; coord_type, 3 &gt;',['../class_gadgetron_1_1ho_n_d_point.html',1,'Gadgetron']]],
  ['hondpoint_3c_20coord_5ftype_2c_20d_20_3e',['hoNDPoint&lt; coord_type, D &gt;',['../class_gadgetron_1_1ho_n_d_point.html',1,'Gadgetron']]],
  ['hondredundantwavelet',['hoNDRedundantWavelet',['../class_gadgetron_1_1ho_n_d_redundant_wavelet.html',1,'Gadgetron']]],
  ['hondredundantwavelet_2eh',['hoNDRedundantWavelet.h',['../ho_n_d_redundant_wavelet_8h.html',1,'']]],
  ['hondwavelet',['hoNDWavelet',['../class_gadgetron_1_1ho_n_d_wavelet.html',1,'Gadgetron']]],
  ['hondwavelet_2eh',['hoNDWavelet.h',['../ho_n_d_wavelet_8h.html',1,'']]],
  ['hoopticalflowsolver',['hoOpticalFlowSolver',['../class_gadgetron_1_1ho_optical_flow_solver.html',1,'Gadgetron']]],
  ['hoopticalflowsolver_2eh',['hoOpticalFlowSolver.h',['../ho_optical_flow_solver_8h.html',1,'']]],
  ['hopartialderivativeoperator',['hoPartialDerivativeOperator',['../class_gadgetron_1_1ho_partial_derivative_operator.html',1,'Gadgetron']]],
  ['hopartialderivativeoperator_2eh',['hoPartialDerivativeOperator.h',['../ho_partial_derivative_operator_8h.html',1,'']]],
  ['horedundantwaveletoperator',['hoRedundantWaveletOperator',['../class_gadgetron_1_1ho_redundant_wavelet_operator.html',1,'Gadgetron']]],
  ['horedundantwaveletoperator_2eh',['hoRedundantWaveletOperator.h',['../ho_redundant_wavelet_operator_8h.html',1,'']]],
  ['hosbcgsolver',['hoSbCgSolver',['../class_gadgetron_1_1ho_sb_cg_solver.html',1,'Gadgetron']]],
  ['hospirit2doperator',['hoSPIRIT2DOperator',['../class_gadgetron_1_1ho_s_p_i_r_i_t2_d_operator.html',1,'Gadgetron']]],
  ['hospirit2doperator_2eh',['hoSPIRIT2DOperator.h',['../ho_s_p_i_r_i_t2_d_operator_8h.html',1,'']]],
  ['hospirit2dtoperator',['hoSPIRIT2DTOperator',['../class_gadgetron_1_1ho_s_p_i_r_i_t2_d_t_operator.html',1,'Gadgetron']]],
  ['hospirit2dtoperator_2eh',['hoSPIRIT2DTOperator.h',['../ho_s_p_i_r_i_t2_d_t_operator_8h.html',1,'']]],
  ['hospirit3doperator',['hoSPIRIT3DOperator',['../class_gadgetron_1_1ho_s_p_i_r_i_t3_d_operator.html',1,'Gadgetron']]],
  ['hospirit3doperator_2eh',['hoSPIRIT3DOperator.h',['../ho_s_p_i_r_i_t3_d_operator_8h.html',1,'']]],
  ['hospiritoperator',['hoSPIRITOperator',['../class_gadgetron_1_1ho_s_p_i_r_i_t_operator.html',1,'Gadgetron']]],
  ['hospiritoperator_2eh',['hoSPIRITOperator.h',['../ho_s_p_i_r_i_t_operator_8h.html',1,'']]],
  ['hotvoperator',['hoTvOperator',['../class_gadgetron_1_1ho_tv_operator.html',1,'Gadgetron']]],
  ['hotvpicsoperator',['hoTvPicsOperator',['../class_gadgetron_1_1ho_tv_pics_operator.html',1,'Gadgetron']]],
  ['howavelet1dbaseoperator',['hoWavelet1DBaseOperator',['../class_gadgetron_1_1ho_wavelet1_d_base_operator.html',1,'Gadgetron']]],
  ['howavelet1doperator',['hoWavelet1DOperator',['../class_gadgetron_1_1ho_wavelet1_d_operator.html',1,'Gadgetron']]],
  ['howavelet1doperator_2eh',['hoWavelet1DOperator.h',['../ho_wavelet1_d_operator_8h.html',1,'']]],
  ['howavelet1drealoperator',['hoWavelet1DREALOperator',['../class_gadgetron_1_1ho_wavelet1_d_r_e_a_l_operator.html',1,'Gadgetron']]],
  ['howavelet2dtoperator',['hoWavelet2DTOperator',['../class_gadgetron_1_1ho_wavelet2_d_t_operator.html',1,'Gadgetron']]],
  ['howavelet2dtoperator_2eh',['hoWavelet2DTOperator.h',['../ho_wavelet2_d_t_operator_8h.html',1,'']]],
  ['howavelet3doperator',['hoWavelet3DOperator',['../class_gadgetron_1_1ho_wavelet3_d_operator.html',1,'Gadgetron']]],
  ['howavelet3doperator_2eh',['hoWavelet3DOperator.h',['../ho_wavelet3_d_operator_8h.html',1,'']]],
  ['howaveletoperator',['hoWaveletOperator',['../class_gadgetron_1_1ho_wavelet_operator.html',1,'Gadgetron']]],
  ['howaveletoperator_2eh',['hoWaveletOperator.h',['../ho_wavelet_operator_8h.html',1,'']]],
  ['htgrappa_2eh',['htgrappa.h',['../htgrappa_8h.html',1,'']]],
  ['http_5fmajor',['http_major',['../structhttp__parser.html#ac994a4a8268652f5ce82de5bde5c3f9d',1,'http_parser']]],
  ['http_5fparser',['http_parser',['../structhttp__parser.html',1,'']]],
  ['http_5fparser_5fsettings',['http_parser_settings',['../structhttp__parser__settings.html',1,'']]],
  ['http_5fparser_5furl',['http_parser_url',['../structhttp__parser__url.html',1,'']]],
  ['httpparser',['HTTPParser',['../structcrow_1_1_h_t_t_p_parser.html',1,'crow']]],
  ['httpparser_3c_20crow_3a_3aconnection_20_3e',['HTTPParser&lt; crow::Connection &gt;',['../structcrow_1_1_h_t_t_p_parser.html',1,'crow']]],
  ['hy',['Hy',['../class_gadgetron_1_1ho_image_reg_dissimilarity_mutual_information.html#a8a60d1344d9b6dff8946bf781892e13f',1,'Gadgetron::hoImageRegDissimilarityMutualInformation']]]
];
