var searchData=
[
  ['l1gpregularizationoperator',['l1GPRegularizationOperator',['../class_gadgetron_1_1gp_solver_1_1l1_g_p_regularization_operator.html',1,'Gadgetron::gpSolver']]],
  ['l1groupgpregularizationoperator',['l1GroupGPRegularizationOperator',['../class_gadgetron_1_1gp_solver_1_1l1_group_g_p_regularization_operator.html',1,'Gadgetron::gpSolver']]],
  ['l2gpregularizationoperator',['l2GPRegularizationOperator',['../class_gadgetron_1_1gp_solver_1_1l2_g_p_regularization_operator.html',1,'Gadgetron::gpSolver']]],
  ['laplaceoperator',['laplaceOperator',['../class_gadgetron_1_1laplace_operator.html',1,'Gadgetron']]],
  ['laplaceoperator_3c_20d_2c_20cundarray_3c_20t_20_3e_20_3e',['laplaceOperator&lt; D, cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1laplace_operator.html',1,'Gadgetron']]],
  ['last_5felement_5ftype',['last_element_type',['../structcrow_1_1black__magic_1_1last__element__type.html',1,'crow::black_magic']]],
  ['last_5felement_5ftype_3c_3e',['last_element_type&lt;&gt;',['../structcrow_1_1black__magic_1_1last__element__type_3_4.html',1,'crow::black_magic']]],
  ['lbfgssolver',['lbfgsSolver',['../class_gadgetron_1_1lbfgs_solver.html',1,'Gadgetron']]],
  ['lbfgssolver_3c_20cundarray_3c_20t_20_3e_20_3e',['lbfgsSolver&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1lbfgs_solver.html',1,'Gadgetron']]],
  ['linearoperator',['linearOperator',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20array_20_3e',['linearOperator&lt; ARRAY &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20array_5ftype_5felement_20_3e',['linearOperator&lt; ARRAY_TYPE_ELEMENT &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20array_5ftype_5foperator_20_3e',['linearOperator&lt; ARRAY_TYPE_OPERATOR &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20complex_5farray_5ftype_20_3e',['linearOperator&lt; COMPLEX_ARRAY_TYPE &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20cundarray_3c_20complext_3c_20real_20_3e_20_3e_20_3e',['linearOperator&lt; cuNDArray&lt; complext&lt; REAL &gt; &gt; &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20cundarray_3c_20complext_3c_20t_20_3e_20_3e_20_3e',['linearOperator&lt; cuNDArray&lt; complext&lt; T &gt; &gt; &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20cundarray_3c_20float_5fcomplext_20_3e_20_3e',['linearOperator&lt; cuNDArray&lt; float_complext &gt; &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20cundarray_3c_20t_20_3e_20_3e',['linearOperator&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20hocundarray_3c_20float_20_3e_20_3e',['linearOperator&lt; hoCuNDArray&lt; float &gt; &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20hocundarray_3c_20t_20_3e_20_3e',['linearOperator&lt; hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20hondarray_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e_20_3e',['linearOperator&lt; hoNDArray&lt; std::complex&lt; T &gt; &gt; &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20hondarray_3c_20t_20_3e_20_3e',['linearOperator&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperator_3c_20real_20_3e',['linearOperator&lt; REAL &gt;',['../class_gadgetron_1_1linear_operator.html',1,'Gadgetron']]],
  ['linearoperatorsolver',['linearOperatorSolver',['../class_gadgetron_1_1linear_operator_solver.html',1,'Gadgetron']]],
  ['linearoperatorsolver_3c_20array_5ftype_5felement_20_3e',['linearOperatorSolver&lt; ARRAY_TYPE_ELEMENT &gt;',['../class_gadgetron_1_1linear_operator_solver.html',1,'Gadgetron']]],
  ['linearoperatorsolver_3c_20cundarray_3c_20float_5fcomplext_20_3e_20_3e',['linearOperatorSolver&lt; cuNDArray&lt; float_complext &gt; &gt;',['../class_gadgetron_1_1linear_operator_solver.html',1,'Gadgetron']]],
  ['linearoperatorsolver_3c_20cundarray_3c_20gadgetron_3a_3acomplext_20_3e_20_3e',['linearOperatorSolver&lt; cuNDArray&lt; Gadgetron::complext &gt; &gt;',['../class_gadgetron_1_1linear_operator_solver.html',1,'Gadgetron']]],
  ['linearoperatorsolver_3c_20cundarray_3c_20t_20_3e_20_3e',['linearOperatorSolver&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1linear_operator_solver.html',1,'Gadgetron']]],
  ['linearoperatorsolver_3c_20hocundarray_3c_20float_20_3e_20_3e',['linearOperatorSolver&lt; hoCuNDArray&lt; float &gt; &gt;',['../class_gadgetron_1_1linear_operator_solver.html',1,'Gadgetron']]],
  ['linearoperatorsolver_3c_20hocundarray_3c_20t_20_3e_20_3e',['linearOperatorSolver&lt; hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1linear_operator_solver.html',1,'Gadgetron']]],
  ['linearoperatorsolver_3c_20hondarray_3c_20t_20_3e_20_3e',['linearOperatorSolver&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1linear_operator_solver.html',1,'Gadgetron']]],
  ['logger',['logger',['../classcrow_1_1logger.html',1,'crow']]],
  ['lsqrsolver',['lsqrSolver',['../class_gadgetron_1_1lsqr_solver.html',1,'Gadgetron']]],
  ['lsqrsolver_3c_20hondarray_3c_20t_20_3e_20_3e',['lsqrSolver&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1lsqr_solver.html',1,'Gadgetron']]],
  ['lwsolver',['lwSolver',['../class_gadgetron_1_1lw_solver.html',1,'Gadgetron']]],
  ['lwsolver_3c_20cundarray_3c_20t_20_3e_20_3e',['lwSolver&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1lw_solver.html',1,'Gadgetron']]]
];
