var searchData=
[
  ['data_5fhistory',['data_history',['../structdata__history.html',1,'']]],
  ['dependencyquerygadget',['DependencyQueryGadget',['../class_gadgetron_1_1_dependency_query_gadget.html',1,'Gadgetron']]],
  ['dependencyqueryreader',['DependencyQueryReader',['../class_gadgetron_1_1_dependency_query_reader.html',1,'Gadgetron']]],
  ['dependencyquerywriter',['DependencyQueryWriter',['../class_gadgetron_1_1_dependency_query_writer.html',1,'Gadgetron']]],
  ['devicechannelsplittergadget',['DeviceChannelSplitterGadget',['../class_gadgetron_1_1_device_channel_splitter_gadget.html',1,'Gadgetron']]],
  ['devicechannelsplittergadget_3c_20ace_5fuint16_20_3e',['DeviceChannelSplitterGadget&lt; ACE_UINT16 &gt;',['../class_gadgetron_1_1_device_channel_splitter_gadget.html',1,'Gadgetron']]],
  ['devicechannelsplittergadget_3c_20float_20_3e',['DeviceChannelSplitterGadget&lt; float &gt;',['../class_gadgetron_1_1_device_channel_splitter_gadget.html',1,'Gadgetron']]],
  ['devicechannelsplittergadget_3c_20std_3a_3acomplex_3c_20float_20_3e_20_3e',['DeviceChannelSplitterGadget&lt; std::complex&lt; float &gt; &gt;',['../class_gadgetron_1_1_device_channel_splitter_gadget.html',1,'Gadgetron']]],
  ['devicechannelsplittergadgetcplx',['DeviceChannelSplitterGadgetCPLX',['../class_gadgetron_1_1_device_channel_splitter_gadget_c_p_l_x.html',1,'Gadgetron']]],
  ['devicechannelsplittergadgetfloat',['DeviceChannelSplitterGadgetFLOAT',['../class_gadgetron_1_1_device_channel_splitter_gadget_f_l_o_a_t.html',1,'Gadgetron']]],
  ['devicechannelsplittergadgetushort',['DeviceChannelSplitterGadgetUSHORT',['../class_gadgetron_1_1_device_channel_splitter_gadget_u_s_h_o_r_t.html',1,'Gadgetron']]],
  ['diagonaloperator',['diagonalOperator',['../class_gadgetron_1_1diagonal_operator.html',1,'Gadgetron']]],
  ['diagonaloperator_3c_20cundarray_3c_20t_20_3e_20_3e',['diagonalOperator&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1diagonal_operator.html',1,'Gadgetron']]],
  ['diagonaloperator_3c_20hocundarray_3c_20t_20_3e_20_3e',['diagonalOperator&lt; hoCuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1diagonal_operator.html',1,'Gadgetron']]],
  ['diagonaloperator_3c_20hondarray_3c_20t_20_3e_20_3e',['diagonalOperator&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1diagonal_operator.html',1,'Gadgetron']]],
  ['diagonalsumoperator',['diagonalSumOperator',['../class_gadgetron_1_1diagonal_sum_operator.html',1,'Gadgetron']]],
  ['diagonalsumoperator_3c_20cundarray_3c_20t_20_3e_20_3e',['diagonalSumOperator&lt; cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1diagonal_sum_operator.html',1,'Gadgetron']]],
  ['diagonalsumoperator_3c_20hondarray_3c_20t_20_3e_20_3e',['diagonalSumOperator&lt; hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1diagonal_sum_operator.html',1,'Gadgetron']]],
  ['dicomfinishgadget',['DicomFinishGadget',['../class_gadgetron_1_1_dicom_finish_gadget.html',1,'Gadgetron']]],
  ['dicomimagewriter',['DicomImageWriter',['../class_gadgetron_1_1_dicom_image_writer.html',1,'Gadgetron']]],
  ['dimensionrecordcompare',['DimensionRecordCompare',['../struct_gadgetron_1_1gt_plus_1_1_dimension_record_compare.html',1,'Gadgetron::gtPlus']]],
  ['distributegadget',['DistributeGadget',['../class_gadgetron_1_1_distribute_gadget.html',1,'Gadgetron']]],
  ['distributionconnector',['DistributionConnector',['../class_gadgetron_1_1_distribution_connector.html',1,'Gadgetron']]],
  ['doubled',['doubled',['../struct_gadgetron_1_1doubled.html',1,'Gadgetron']]],
  ['downsampleoperator',['downsampleOperator',['../class_gadgetron_1_1downsample_operator.html',1,'Gadgetron']]],
  ['downsampleoperator_3c_20cundarray_3c_20t_20_3e_2c_20d_20_3e',['downsampleOperator&lt; cuNDArray&lt; T &gt;, D &gt;',['../class_gadgetron_1_1downsample_operator.html',1,'Gadgetron']]],
  ['dsr',['dsr',['../structdsr.html',1,'']]],
  ['dumb_5ftimer_5fqueue',['dumb_timer_queue',['../classcrow_1_1detail_1_1dumb__timer__queue.html',1,'crow::detail']]],
  ['dynamicrule',['DynamicRule',['../classcrow_1_1_dynamic_rule.html',1,'crow']]]
];
