var searchData=
[
  ['parameter_5ftag',['parameter_tag',['../structcrow_1_1black__magic_1_1parameter__tag.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20char_20_3e',['parameter_tag&lt; char &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01char_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20double_20_3e',['parameter_tag&lt; double &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01double_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20int_20_3e',['parameter_tag&lt; int &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01int_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20long_20_3e',['parameter_tag&lt; long &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01long_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20long_20long_20_3e',['parameter_tag&lt; long long &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01long_01long_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20short_20_3e',['parameter_tag&lt; short &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01short_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20std_3a_3astring_20_3e',['parameter_tag&lt; std::string &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01std_1_1string_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20unsigned_20char_20_3e',['parameter_tag&lt; unsigned char &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01unsigned_01char_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20unsigned_20int_20_3e',['parameter_tag&lt; unsigned int &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01unsigned_01int_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20unsigned_20long_20_3e',['parameter_tag&lt; unsigned long &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01unsigned_01long_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20unsigned_20long_20long_20_3e',['parameter_tag&lt; unsigned long long &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01unsigned_01long_01long_01_4.html',1,'crow::black_magic']]],
  ['parameter_5ftag_3c_20unsigned_20short_20_3e',['parameter_tag&lt; unsigned short &gt;',['../structcrow_1_1black__magic_1_1parameter__tag_3_01unsigned_01short_01_4.html',1,'crow::black_magic']]],
  ['parameterparser',['ParameterParser',['../class_gadgetron_1_1_parameter_parser.html',1,'Gadgetron']]],
  ['parameterrelaygadget',['ParameterRelayGadget',['../class_gadgetron_1_1_parameter_relay_gadget.html',1,'Gadgetron']]],
  ['partial_5fcontext',['partial_context',['../structcrow_1_1detail_1_1partial__context.html',1,'crow::detail']]],
  ['partial_5fcontext_3c_20middlewares_2e_2e_2e_3e',['partial_context&lt; Middlewares...&gt;',['../structcrow_1_1detail_1_1partial__context.html',1,'crow::detail']]],
  ['partial_5fcontext_3c_3e',['partial_context&lt;&gt;',['../structcrow_1_1detail_1_1partial__context_3_4.html',1,'crow::detail']]],
  ['partialderivativeoperator',['partialDerivativeOperator',['../class_gadgetron_1_1partial_derivative_operator.html',1,'Gadgetron']]],
  ['partialderivativeoperator_3c_20d_2c_20cundarray_3c_20t_20_3e_20_3e',['partialDerivativeOperator&lt; D, cuNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1partial_derivative_operator.html',1,'Gadgetron']]],
  ['partialderivativeoperator_3c_20d_2c_20hondarray_3c_20t_20_3e_20_3e',['partialDerivativeOperator&lt; D, hoNDArray&lt; T &gt; &gt;',['../class_gadgetron_1_1partial_derivative_operator.html',1,'Gadgetron']]],
  ['partialfourieradjustrogadget',['PartialFourierAdjustROGadget',['../class_gadgetron_1_1_partial_fourier_adjust_r_o_gadget.html',1,'Gadgetron']]],
  ['passthrough',['Passthrough',['../classpassthrough_1_1_passthrough.html',1,'passthrough']]],
  ['pca',['PCA',['../classtpat__snr__scale_1_1_p_c_a.html',1,'tpat_snr_scale']]],
  ['pcacoilgadget',['PCACoilGadget',['../class_gadgetron_1_1_p_c_a_coil_gadget.html',1,'Gadgetron']]],
  ['permutationoperator',['permutationOperator',['../class_gadgetron_1_1permutation_operator.html',1,'Gadgetron']]],
  ['physiointerpolationgadget',['PhysioInterpolationGadget',['../class_gadgetron_1_1_physio_interpolation_gadget.html',1,'Gadgetron']]],
  ['pop_5fback',['pop_back',['../structcrow_1_1black__magic_1_1pop__back.html',1,'crow::black_magic']]],
  ['pop_5fback_3c_3e',['pop_back&lt;&gt;',['../structcrow_1_1black__magic_1_1pop__back_3_4.html',1,'crow::black_magic']]],
  ['pop_5fback_5fhelper',['pop_back_helper',['../structcrow_1_1black__magic_1_1pop__back__helper.html',1,'crow::black_magic']]],
  ['pop_5fback_5fhelper_3c_20seq_3c_20n_2e_2e_2e_3e_2c_20tuple_20_3e',['pop_back_helper&lt; seq&lt; N...&gt;, Tuple &gt;',['../structcrow_1_1black__magic_1_1pop__back__helper_3_01seq_3_01_n_8_8_8_4_00_01_tuple_01_4.html',1,'crow::black_magic']]],
  ['pow',['Pow',['../struct_gadgetron_1_1_pow.html',1,'Gadgetron']]],
  ['pow_3c_20i_2c_201_20_3e',['Pow&lt; i, 1 &gt;',['../struct_gadgetron_1_1_pow_3_01i_00_011_01_4.html',1,'Gadgetron']]],
  ['promote',['promote',['../structcrow_1_1black__magic_1_1promote.html',1,'crow::black_magic']]],
  ['promote_3c_20char_20_3e',['promote&lt; char &gt;',['../structcrow_1_1black__magic_1_1promote_3_01char_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20float_20_3e',['promote&lt; float &gt;',['../structcrow_1_1black__magic_1_1promote_3_01float_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20int_20_3e',['promote&lt; int &gt;',['../structcrow_1_1black__magic_1_1promote_3_01int_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20long_20_3e',['promote&lt; long &gt;',['../structcrow_1_1black__magic_1_1promote_3_01long_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20long_20long_20_3e',['promote&lt; long long &gt;',['../structcrow_1_1black__magic_1_1promote_3_01long_01long_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20short_20_3e',['promote&lt; short &gt;',['../structcrow_1_1black__magic_1_1promote_3_01short_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20unsigned_20char_20_3e',['promote&lt; unsigned char &gt;',['../structcrow_1_1black__magic_1_1promote_3_01unsigned_01char_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20unsigned_20int_20_3e',['promote&lt; unsigned int &gt;',['../structcrow_1_1black__magic_1_1promote_3_01unsigned_01int_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20unsigned_20long_20_3e',['promote&lt; unsigned long &gt;',['../structcrow_1_1black__magic_1_1promote_3_01unsigned_01long_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20unsigned_20long_20long_20_3e',['promote&lt; unsigned long long &gt;',['../structcrow_1_1black__magic_1_1promote_3_01unsigned_01long_01long_01_4.html',1,'crow::black_magic']]],
  ['promote_3c_20unsigned_20short_20_3e',['promote&lt; unsigned short &gt;',['../structcrow_1_1black__magic_1_1promote_3_01unsigned_01short_01_4.html',1,'crow::black_magic']]],
  ['pseudoreplicagather',['PseudoreplicaGather',['../classpseudoreplicagather_1_1_pseudoreplica_gather.html',1,'pseudoreplicagather']]],
  ['pseudoreplicatorgadget',['PseudoReplicatorGadget',['../class_gadgetron_1_1_pseudo_replicator_gadget.html',1,'Gadgetron']]],
  ['python_5fconverter',['python_converter',['../struct_gadgetron_1_1python__converter.html',1,'Gadgetron']]],
  ['python_5fconverter_3c_20hondarray_3c_20t_20_3e_20_3e',['python_converter&lt; hoNDArray&lt; T &gt; &gt;',['../struct_gadgetron_1_1python__converter_3_01ho_n_d_array_3_01_t_01_4_01_4.html',1,'Gadgetron']]],
  ['python_5fconverter_3c_20ismrmrd_3a_3aacquisitionheader_20_3e',['python_converter&lt; ISMRMRD::AcquisitionHeader &gt;',['../struct_gadgetron_1_1python__converter_3_01_i_s_m_r_m_r_d_1_1_acquisition_header_01_4.html',1,'Gadgetron']]],
  ['python_5fconverter_3c_20ismrmrd_3a_3aimageheader_20_3e',['python_converter&lt; ISMRMRD::ImageHeader &gt;',['../struct_gadgetron_1_1python__converter_3_01_i_s_m_r_m_r_d_1_1_image_header_01_4.html',1,'Gadgetron']]],
  ['python_5fconverter_3c_20ismrmrdrecondata_20_3e',['python_converter&lt; IsmrmrdReconData &gt;',['../struct_gadgetron_1_1python__converter_3_01_ismrmrd_recon_data_01_4.html',1,'Gadgetron']]],
  ['python_5fconverter_3c_20std_3a_3atuple_3c_20ts_2e_2e_2e_3e_20_3e',['python_converter&lt; std::tuple&lt; TS...&gt; &gt;',['../struct_gadgetron_1_1python__converter_3_01std_1_1tuple_3_01_t_s_8_8_8_4_01_4.html',1,'Gadgetron']]],
  ['python_5fconverter_3c_20std_3a_3avector_3c_20t_20_3e_20_3e',['python_converter&lt; std::vector&lt; T &gt; &gt;',['../struct_gadgetron_1_1python__converter_3_01std_1_1vector_3_01_t_01_4_01_4.html',1,'Gadgetron']]],
  ['pythonfunction',['PythonFunction',['../class_gadgetron_1_1_python_function.html',1,'Gadgetron']]],
  ['pythonfunction_3c_20rettype_20_3e',['PythonFunction&lt; RetType &gt;',['../class_gadgetron_1_1_python_function_3_01_ret_type_01_4.html',1,'Gadgetron']]],
  ['pythonfunction_3c_3e',['PythonFunction&lt;&gt;',['../class_gadgetron_1_1_python_function_3_4.html',1,'Gadgetron']]],
  ['pythonfunctionbase',['PythonFunctionBase',['../class_gadgetron_1_1_python_function_base.html',1,'Gadgetron']]],
  ['pythongadget',['PythonGadget',['../class_gadgetron_1_1_python_gadget.html',1,'Gadgetron']]],
  ['pytuple2cpptuple_5fwrapper',['pytuple2cpptuple_wrapper',['../struct_gadgetron_1_1pytuple2cpptuple__wrapper.html',1,'Gadgetron']]]
];
